### ISSUE TITLE
Support modify `prometheus.yml` in `tiup cluster`.

### ISSUE THREAD

**Issue by LittleFall** [pingcap/tiup#1004]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Following https://docs.pingcap.com/zh/tidb/dev/tiup-cluster#%E6%9B%B4%E6%96%B0%E9%85%8D%E7%BD%AE, I can modify *.rules.yml, but I can't modify the promethus.yml.

**Describe the feature you'd like:**

Support modify `prometheus.yml` in `tiup cluster`.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

I want to modify the config in prometheus.yml, such as `scrape_interval`.

**Comment by nexustar** [comment]
partly done by #1641
