### ISSUE TITLE
v1.3.0 check thp always fail

### ISSUE THREAD

**Issue by sultan8252** [pingcap/tiup#1006]
## Bug Report
When split string result, there is a \n at the end, resulting in an additional'' element in the list. Therefore, it is necessary to enter the fail process when determining whether it contains the [never] string.
bug point: https://github.com/pingcap/tiup/blob/v1.3.0/pkg/cluster/operation/check.go#L672-L677
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
tiup cluster check --cluster {cluster-name}

2. What did you expect to see?
always report fail

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?
v1.3.0

**Comment by dveeden** [comment]
This has been fixed by @lucklove in #1005
/close
