### ISSUE TITLE
Disable space_placeholder_file for playgrounds

### ISSUE THREAD

**Issue by wwar** [pingcap/tiup#101]
## Feature Request

I think what you are doing with tiup is great! I have a small nit:

**Is your feature request related to a problem? Please describe:**

Each of the playgrounds create TiKV's `space_placeholder_file` (2GB). I think this makes sense for production environments, but less so on a desktop where you might have multiple playgrounds.

**Describe the feature you'd like:**

Disable space place holders.

**Describe alternatives you've considered:**

It's not that harmful, alternative would be to keep as is. That will limit having multiple playgrounds.

**Teachability, Documentation, Adoption, Migration Strategy:**

N/A

**Comment by lonng** [comment]
@BusyJay @stn PTAL

**Comment by BusyJay** [comment]
@lonng playground can set `storage.reserve-space` to zero by default.

**Comment by lonng** [comment]
@BusyJay Thanks, I will fix it.
