### ISSUE TITLE
improve error log output：log dir and host ip

### ISSUE THREAD

**Issue by King-Dylan** [pingcap/tiup#1023]
## Feature Request

If the current deployment fails, it is not very intuitive to see which machine and log information it is.

**Is your feature request related to a problem? Please describe:**

If an error occurs during the deployment process, tiup does not have detailed log information for the time being, so users cannot quickly locate the cause of tiup failure. So we need to guide the user to see which log on which machine when reporting an error.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by AstroProfundis** [comment]
This is already done in #923
