### ISSUE TITLE
support configure exists alertmanager target

### ISSUE THREAD

**Issue by King-Dylan** [pingcap/tiup#1025]
## Feature Request
support configure exists alertmanager target
**Is your feature request related to a problem? Please describe:**

Some customers may have more than one set of clusters. It is obviously inappropriate to configure a separate alertmanager for each set of clusters. Therefore, tiup is required to support the configuration of the existing alertmanager.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by AstroProfundis** [comment]
We can add an argument for prometheus instance to set a custom alertmanager address
