### ISSUE TITLE
Reduct jitter feature

### ISSUE THREAD

**Issue by King-Dylan** [pingcap/tiup#1033]
## Feature Request
Reduct jitter feature
**Is your feature request related to a problem? Please describe:**

 - [ ] before upgrade check pd miss-peer pending-peer and give a suggestion :solve miss-peer or ignore . Check the status of the region before the upgrade to reduce upgrade jitter or failure caused by the abnormal region before the upgrade.
 - [ ] before eviting tikv leader configure leader-scheduler-limit store-limit region-scheduler-limit.speed up leader transfer, after upgrade change to default value。can take the original value and add a number, and make a judgment of not greater than leader-scheduler-limit(64) store-limit(1024) region-scheduler-limit(1024) example:
 1.tiup cluster  upgrade xxxx 
 2.background(get default value) 
      tiup ctl pd -u xxx.xxx.xxx.xxx:2379 config show |grep  leader-schedule-limit 
      tiup ctl pd -u xxx.xxx.xxx.xxx:2379 config show |grep  region-schedule-limit
      tiup ctl pd -u xxx.xxx.xxx.xxx:2379 store limit
3.background
      tiup ctl pd -u xxx.xxx.xxx.xxx:2379 config set  leader-schedule-limit {default value}+32
      tiup ctl pd -u xxx.xxx.xxx.xxx:2379 config set  region-schedule-limit  {default value}+512
      tiup ctl pd -u xxx.xxx.xxx.xxx:2379 store limit all  {default value}+512
4.tikv rolling upgrade end
5.background(get value and check default >=0) 
      tiup ctl pd -u xxx.xxx.xxx.xxx:2379 config show |grep  leader-schedule-limit 
      tiup ctl pd -u xxx.xxx.xxx.xxx:2379 config show |grep  region-schedule-limit
      tiup ctl pd -u xxx.xxx.xxx.xxx:2379 store limit
6.background (setback default value)
      tiup ctl pd -u xxx.xxx.xxx.xxx:2379 config set  leader-schedule-limit {value}-32
      tiup ctl pd -u xxx.xxx.xxx.xxx:2379 config set  region-schedule-limit {value}-512
      tiup ctl pd -u xxx.xxx.xxx.xxx:2379 store limit all {value}-512

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by King-Dylan** [comment]
pd reduce jitter https://github.com/pingcap/tiup/pull/1032

**Comment by AstroProfundis** [comment]
I'm closing this as both linked issues are closed, please reopen if there's anything more need to be done.
