### ISSUE TITLE
please update document for ansible backup directory to  "ansible-imported-configs"

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tiup#1035]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
in this document: https://docs.pingcap.com/zh/tidb/stable/upgrade-tidb-using-tiup
3.2 编辑 TiUP 拓扑配置文件
注意：

以下情况可跳过该步骤：

原集群没有修改过配置参数。
升级后希望使用 4.0 默认参数。
进入 TiDB Ansible 的备份目录 ~/.tiup/storage/cluster/clusters/{cluster_name}/config，确认配置模板中修改过的参数。

2. What did you expect to see?

the backup directory is not clusters/{cluster_name}/config; 
should be  ansible-imported-configs
─tidb@localhost ~/.tiup/storage/cluster/clusters/test-cluster 
╰─$ ls
ansible-backup  ansible-imported-configs  backup  meta.yaml  ssh

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?

**Comment by lucklove** [comment]
https://github.com/pingcap/docs-cn/pull/5220
