### ISSUE TITLE
tiup deployed prometheus can't generate alertmanager configurations correctly

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/tiup#1038]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Use tiup cluster to deploy a tidb cluster and enable alertmanager.

2. What did you expect to see?
Alertmanger's configuration is generated in `prometheus.yaml`.

3. What did you see instead?
No alertmanger configuration is found.

4. What version of TiUP are you using (`tiup --version`)?
tiup version v1.3.1 tiup
Go Version: go1.13
Git Branch: release-1.3
GitHash: d51bd0c

**Comment by lichunzhu** [comment]
I guess that's because we have typo at these two places.
https://github.com/pingcap/tiup/blob/cbc4e18f6bbce97c187222e8533f5795510491de/pkg/cluster/spec/prometheus.go#L216 should be 
```go
	if servers, found := topoHasField("Grafanas"); found {
```
https://github.com/pingcap/tiup/blob/cbc4e18f6bbce97c187222e8533f5795510491de/pkg/cluster/spec/prometheus.go#L223 should be 
```go
	if servers, found := topoHasField("Alertmanagers"); found {
```
The definition of `spec` is here: https://github.com/pingcap/tiup/blob/cbc4e18f6bbce97c187222e8533f5795510491de/pkg/cluster/spec/spec.go#L111

**Comment by lichunzhu** [comment]
@lucklove PTAL

**Comment by 9547** [comment]
@lichunzhu This was introduced in #890, I'll try to fix it ASAP.
