### ISSUE TITLE
Write to .bashrc if .bash_profile doesn't exist?

### ISSUE THREAD

**Issue by wwar** [pingcap/tiup#104]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Ran the tiup installer.

2. What did you expect to see?

I am not a bash expert, but after running the install the `tiup` binary was not in my `PATH`. I debugged it, and it looks like it created+wrote to `.bash_profile` (which Ubuntu doesn't use).

I thought that it would use `.bash_profile` if it existed.. but it seems not. So I moved the contents to my `.bashrc` file and it works reliably. I also tried `.profile`, but that didn't work.

I am using a pretty much stock Ubuntu 20.04 beta with bash 5.0.16(1)-release.

3. What did you see instead?

```
$ tiup

Command 'tiup' not found, did you mean:

  command 'tilp' from deb tilp2 (1.18-3)
  command 'tup' from deb tup (0.7.8-3)

Try: sudo apt install <deb name>
```

4. What version of TiUP are you using (`tiup --version`)?

```
tiup version v0.0.3 tiup
```

**Comment by lonng** [comment]
@wwar Thanks for your feedback.
@lucklove PTAL
