### ISSUE TITLE
Deploy cluster like playground?

### ISSUE THREAD

**Issue by xhebox** [pingcap/tiup#1045]
## Feature Request

**Is your feature request related to a problem? Please describe:**
No

**Describe the feature you'd like:**
`tiup cluster` has more advanced functions and **a great yaml** configuration file. But it can only deploy the cluster by SSH. I wonder if tiup can port more commands from `tiup cluster` to `tiup playground`, or `tiup cluster deploy` can run without ssh, sudo or so, just like `tiup playground`. Maybe `tiup cluster deploy --local`.

**Comment by AstroProfundis** [comment]
Try `cluster deploy xxx --ssh=none`, that's an experimental feature and not ganrenteed to work perfectly. You'll have to set **all** `host`s to `127.0.0.1` in this mode.

**Comment by xhebox** [comment]
OK, it works. But some points:

1. It still checks my `~/.ssh` dir, even with `--ssh=none`.
2. It uses `sudo` to switch user/group. But I got stuck when `deploy xxx`, the password prompt messages from sudo are redirected to somewhere other than stdout. I typed my password[enter], then it completes the deployment.
3. I wonder if `tiup` can give a switch like `--sudo=none`. I can accept a local user: that is what I want, an advanced playground. `tiup` can use `~/.config/systemd/user/tiup/[cluster name]` to manage its services. `systemctl --user daemon-reload && systemctl --user start xxx` would do the work.

And another not that related suggestion: we can prefix the services installed by `tiup`. I mean, there are other services in `/etc/systemd/system`, it will be more easier to delete unit files from tiup, if I somehow failed to clean it by `tiup`.

**Comment by recoilme** [comment]
unlike playground ```cluster deploy xxx --ssh=none``` - start download binary for linux on my mac( 
Persistent playground will be very usefull for developing

**Comment by AstroProfundis** [comment]
> systemctl --user daemon-reload && systemctl --user start xxx would do the work.

Actually we have tried this way, but unfortunately CentOS 7 is not fully supporting that, and CentOS 7 is the recommended OS for TiDB production usage as of now.

The "reduce or avoid usage of sudo" thing is on our list, but we don't have any actual plan now, so I don't expect it be implemented soon.

**Comment by AstroProfundis** [comment]
We don't support deploying TiDB cluster on Mac servers.

> Persistent playground will be very usefull for developing

Please try `-T/--tag` argument of `tiup` to see if that meets your need. e.g., `tiup -T mydevcluster playground xxx`, this will make the context of this call of playground persistent, and next time you call it with the same tag, you'll get the same data.
