### ISSUE TITLE
before upgrade check owner and Authority of deploy and data directory

### ISSUE THREAD

**Issue by King-Dylan** [pingcap/tiup#1062]
## Feature Request
before upgrade check owner and Authority deploy and data directory
**Is your feature request related to a problem? Please describe:**

The permissions of the actual user environment may be changed by mistake after running for a period of time, so it is best to check the users and permissions before upgrading.
**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lucklove** [comment]
Task: add directory permissions check for the `check command` when `--cluster` is specified
