### ISSUE TITLE
write monitor data to remote storage

### ISSUE THREAD

**Issue by XSHui** [pingcap/tiup#1063]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I need write monitor data of all tidb cluster to a remote storage .

**Describe the feature you'd like:**

support prometheus remote_write/remote_read

**Describe alternatives you've considered:**

support prometheus remote_write/remote_read

**Teachability, Documentation, Adoption, Migration Strategy:**

https://prometheus.io/docs/prometheus/latest/configuration/configuration/

**Comment by AstroProfundis** [comment]
I think we can add `config` filed to prometheus spec as we do with core components.
