### ISSUE TITLE
 Support network bandwidth check

### ISSUE THREAD

**Issue by jacktd9** [pingcap/tiup#1064]
生产集群部署时往往需要先压测机器间网络的带宽，避免网络组或者服务器网卡配置不一、交换机错误配置等

希望能支持集群间网络带宽的 check 
server: nc -l -p 1234 < /dev/zero
client: nc xxx 1234 > /dev/null
流量监控：ifstat em1 -p
	RX Data/Rate 数据接收流量
	TX Data/Rate 数据发送流量

**Comment by 9547** [comment]
IMHO, this check is hard to implement,  you need to start the client and server first, and specify the interface name to check the bandwidth, in our current implementation, we only support run commands in each node independent.

AFAIK, if we need to check the interface bandwidth, maybe we can check with tools such as `ethtool` to see if it has 10G or higher interface seems enough?

**Comment by AstroProfundis** [comment]
This should be done when the server is set and boot up, not when someone trying to deploy application on it. We can add interface information in `check` to see if it's working on 1G/10G/etc mode, but it's not reasonable for us to run `iperf` between servers.
