### ISSUE TITLE
`tiup playground` keyword check

### ISSUE THREAD

**Issue by glkappe** [pingcap/tiup#1067]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

This command has been output but cannot be found. ```Error: use `tiup install playyground` to install `playyground` first``` Is it unnecessary to output?

![image](https://user-images.githubusercontent.com/21033020/104540117-d1fc8f00-5659-11eb-9695-587884e4189f.png)

2. What did you expect to see?

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?

**Comment by 9547** [comment]
As TiUP is a component manager, if the command is not found, then TiUP will think this is a new component and try to automatically download and install it, if failed then TiUP will ask you to install it manually.
