### ISSUE TITLE
white space issues in https://pingcap.com/blog/get-tidb-cluster-up-in-only-one-minute to install tiup command

### ISSUE THREAD

**Issue by sjmudd** [pingcap/tiup#1076]
## Bug Report

1. What did you do?

Follow the instructions on: https://pingcap.com/blog/get-tidb-cluster-up-in-only-one-minute to try to install `tiup`

Suggested (incorrect) command is: `curl --proto '= https' --tlsv1.2 -sSf https: / /tiup-mirrors.pingcap.com/install.sh | sh`

2. What did you expect to see?

Downloading of the tiup command succeeding.

3. What did you see instead?

```
$ curl --proto '= https' --tlsv1.2 -sSf https: / /tiup-mirrors.pingcap.com/install.sh | sh
curl: option --proto: is badly used here
curl: try 'curl --help' or 'curl --manual' for more information
$
```

4. What version of TiUP are you using (`tiup --version`)?

N/A applicable as the download did not complete.

6. Solution.

Change the command shown, removing unintended whitespace:

```
$ curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4412k  100 4412k    0     0  2268k      0  0:00:01  0:00:01 --:--:-- 2267k
WARN: adding root certificate via internet: https://tiup-mirrors.pingcap.com/root.json
You can revoke this by remove /home/user/.tiup/bin/7b8e153f2e2d0928.root.json
Set mirror to https://tiup-mirrors.pingcap.com success
Detected shell: bash
Shell profile:  /home/user/.bash_profile
/home/user/.bash_profile has been modified to to add tiup to PATH
open a new terminal or source /home/user/.bash_profile to use it
Installed path: /home/user/.tiup/bin/tiup
===============================================
Have a try:     tiup playground
===============================================
$
```

Thanks for building this new command as it simplifies management of the software so saves time and reduces mistakes.

**Comment by 9547** [comment]
thanks for your report and fix suggest, we'll fix it in the blog.

**Comment by lucklove** [comment]
@hi-rustin I don't think we have a role called collaborator: https://github.com/pingcap/community/blob/master/special-interest-groups/sig-tiup/membership.json

Is there something missing?

**Comment by hi-rustin** [comment]
> @hi-rustin I don't think we have a role called collaborator: https://github.com/pingcap/community/blob/master/special-interest-groups/sig-tiup/membership.json
> 
> Is there something missing?

Collaborator is a member of the organization.

**Comment by hi-rustin** [comment]
You can request to invite him to the org.

**Comment by lucklove** [comment]
> > @hi-rustin I don't think we have a role called collaborator: https://github.com/pingcap/community/blob/master/special-interest-groups/sig-tiup/membership.json
> > Is there something missing?
> 
> Collaborator is a member of the organization.

IMO, the robot should check authority only by https://github.com/pingcap/community/blob/master/special-interest-groups/sig-tiup/membership.json since we cooperate by https://github.com/pingcap/community. And there is nothing mentioned the collaborator:


![image](https://user-images.githubusercontent.com/8718109/105274648-8c4f4180-5bd8-11eb-84ad-f8d47ff0672b.png)

**Comment by lucklove** [comment]
If a committer can merge a PR, why he can't close an issue?

**Comment by lucklove** [comment]
> You can request to invite him to the org.

What org? PingCAP? I think we must hire him before invite him...

**Comment by hi-rustin** [comment]
> > You can request to invite him to the org.
> 
> What org? PingCAP? I think we must hire him before invite him...

Reviewer and above roles can be invited to the org.

**Comment by hi-rustin** [comment]
> > > @hi-rustin I don't think we have a role called collaborator: https://github.com/pingcap/community/blob/master/special-interest-groups/sig-tiup/membership.json
> > > Is there something missing?
> > 
> > 
> > Collaborator is a member of the organization.
> 
> IMO, the robot should check authority only by https://github.com/pingcap/community/blob/master/special-interest-groups/sig-tiup/membership.json since we cooperate by https://github.com/pingcap/community. And there is nothing mentioned the collaborator:
> 
> ![image](https://user-images.githubusercontent.com/8718109/105274648-8c4f4180-5bd8-11eb-84ad-f8d47ff0672b.png)
> 
> The current mechanism makes us not transparent enough, and it's confusing: what mechanism are we running under? https://github.com/pingcap/community can't explain how things run at this time.

It is difficult to explain the usage of all the plugins in this repository, you can refer to the [command help](https://prow.tidb.io/command-help?repo=pingcap%2Ftiup) or the instruction manual [book(WIP)](https://book.prow.tidb.io/#/).
