### ISSUE TITLE
When using --kv.config to specify a custom config file, it will be overwritten by the default config

### ISSUE THREAD

**Issue by HunDunDM** [pingcap/tiup#108]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

`tiup playground nightly --kv.config=~/tiup/tikv.toml`

2. What did you expect to see?

Start a custom configured TiKV.

3. What did you see instead?

The custom config file is overwritten by the default config.

4. What version of TiUP are you using (`tiup --version`)?
tiup version v0.0.3 tiup

**Comment by lucklove** [comment]
It's fixed in newest version (v1.0.7)
