### ISSUE TITLE
Add more accurate error notification

### ISSUE THREAD

**Issue by King-Dylan** [pingcap/tiup#1090]
## Feature Request

**Is your feature request related to a problem? Please describe:**

 tiup cluster xxxx tidb-test
Starting component `cluster`: /root/.tiup/components/cluster/v1.3.1/tiup-cluster xxxx tidb-test
This operation will xxxx tidb v4.0.9 cluster tidb-test and its data.
Do you want to continue? [y/N]:  yy

Error: Operation aborted by user (cliutil.operation_aborted)
Error: run `/root/.tiup/components/cluster/v1.3.1/tiup-cluster` (wd:/root/.tiup/data/SMojwNC) failed: exit status 1

**Describe the feature you'd like:**

tiup cluster xxxx tidb-test
Starting component `cluster`: /root/.tiup/components/cluster/v1.3.1/tiup-cluster xxxx tidb-test
This operation will xxxx tidb v4.0.9 cluster tidb-test and its data.
Do you want to continue? [y/N]:  yy

Error: Operation aborted by user **【wrong input character: "  yy"】**
Error: run `/root/.tiup/components/cluster/v1.3.1/tiup-cluster` (wd:/root/.tiup/data/SMojwNC) failed: exit status 1

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by 9547** [comment]
The prompt default to `No` and ONLY return true if the user input is `y` or `Yes`, Ref https://github.com/pingcap/tiup/blob/2f4bdc0bfb5ffc7f0a0425f947c09fa7c9836edb/pkg/cliutil/tui.go#L71-L81

So, IMHO, I don't think we need to add more error messages.

**Comment by AstroProfundis** [comment]
We don't need to change much, just print the user's answer in the message so that we can debug easier with some non-ASCII chars.
