### ISSUE TITLE
make unit-test failed

### ISSUE THREAD

**Issue by XSHui** [pingcap/tiup#1094]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

make unit-test on master branch

2. What did you expect to see?
make unit-test success

3. What did you see instead?
make unit-test failed
```

----------------------------------------------------------------------
FAIL: init_config_test.go:75: initConfigSuite.TestCheckConfig

init_config_test.go:100:
    c.Assert(t.Execute(ctx), check.IsNil)
... value *errors.errorString = &errors.errorString{s:"no executor"} ("no executor")

OOPS: 0 passed, 1 FAILED
--- FAIL: Test (0.00s)
FAIL
```

4. What version of TiUP are you using (`tiup --version`)?
tiup-v1.3.1
commit d85cb884420bd54273210787c1af54d7641816d1

**Comment by AstroProfundis** [comment]
Please use `make test` instead, it runs `failpoint-enable unit-test failpoint-disable`, we use failpoint for some tests so the unit tests will fail if it's not enabled.
