### ISSUE TITLE
tiup cluster restart failed because of the node_expoter binary path

### ISSUE THREAD

**Issue by Win-Man** [pingcap/tiup#1097]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

 1. Import from ansible to tiup
 2. Upgrade the cluster to v4.0 using tiup
 3. tiup cluster restart failed 

2. What did you expect to see?
tiup cluster restart execute successfully

3. What did you see instead?
tiup cluster restart execute failed.

The failed reason is that the node_exporter and blackbox_exporter binary path  is wrong.
The path in tiup is `bin/node_exporter/node_exporter`, but in ansible is `bin/node_exporter`
![image](https://user-images.githubusercontent.com/12085878/105806839-ad9c9d00-5fdf-11eb-882b-badfd570b605.png)
![image](https://user-images.githubusercontent.com/12085878/105806849-b0978d80-5fdf-11eb-9211-9094c42217c9.png)

4. What version of TiUP are you using (`tiup --version`)?
![image](https://user-images.githubusercontent.com/12085878/105806597-3961f980-5fdf-11eb-8016-dba95ac14f4d.png)

**Comment by lucklove** [comment]
We are trying to fix this, and plan to release the fix in v1.3.2 this week
