### ISSUE TITLE
Support testing of filesystem artefacts in integration tests

### ISSUE THREAD

**Issue by nrc** [pingcap/tiup#110]
We should be able to test which files are generated, where they are, and what they contain. This is necessary to test actions like installing and upgrading components.

**Comment by lucklove** [comment]
So do we need something like fuse?

**Comment by nrc** [comment]
I don't think it needs to be so complicated, we can just use a tempdir, its more about having some helper functions to make it easy to write those unit tests.

**Comment by lucklove** [comment]
I think we can use some utils like https://github.com/pingcap/tiup/pull/822/files#diff-50b6ebd7c046e884af9b0fbca1679289R34 to do this.
