### ISSUE TITLE
"tiup mirror clone _ nightly" does not download the actual nightly version of pump/drainer/br/dm/lightning etc.

### ISSUE THREAD

**Issue by kennytm** [pingcap/tiup#1108]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

First, clone the tiup mirror following https://docs.pingcap.com/tidb/dev/production-offline-deployment-using-tiup:

```sh
tiup mirror clone mirror2 nightly -o linux -a amd64
```

Then, get a list of components with nightly version but not properly filled in:

```sh
cd mirror2
grep -l '"nightly":"".*-nightly-' *.json
```

2. What did you expect to see?

Empty list

3. What did you see instead?

```console
$ grep -l '"nightly":"".*-nightly-' *.json
267.dmctl.json
270.dm-worker.json
271.dm-master.json
446.dumpling.json
479.br.json
519.tidb-lightning.json
578.drainer.json
587.pump.json
590.pd-recover.json
```

4. What version of TiUP are you using (`tiup --version`)?

```console
$ tiup --version
v1.3.2 tiup
Go Version: go1.13
Git Branch: release-1.3
GitHash: 2d88460
```

----

The reason we get this is because #271 is incomplete. 

https://github.com/pingcap/tiup/blob/74dfe6f7bb2c435510412859338d64a8f8ca921e/pkg/repository/clone_mirror.go#L420-L421

https://github.com/pingcap/tiup/blob/74dfe6f7bb2c435510412859338d64a8f8ca921e/pkg/repository/clone_mirror.go#L432-L435

Pump, Drainer, BR, DM and Lightning are not listed as a `coreSuites`, so when encountering the pseudo-version "nightly", it enters the branch in line 434 and get the latest stable version instead (v5.0.0-rc).  This in turn *yanks* the true nightly version, and set the `"nightly"` field in the manifest to empty. So when we deploy a nightly cluster [containing binlog](https://docs.pingcap.com/tidb/stable/tidb-binlog-deployment-topology) using this local mirror, it fails with "component not found" error.

```
...
2021-01-29T01:37:13.252+0800    DEBUG   TaskFinish      {"task": "Download: component=drainer, version=nightly, os=linux, arch=amd64", "error": "version nightly on linux/amd64 for component drainer not found"}
2021-01-29T01:37:13.252+0800    DEBUG   TaskFinish      {"task": "Download: component=drainer, version=nightly, os=linux, arch=amd64", "error": "version nightly on linux/amd64 for component drainer not found"}
2021-01-29T01:37:13.257+0800    DEBUG   TaskFinish      {"task": "Download: component=pump, version=nightly, os=linux, arch=amd64", "error": "version nightly on linux/amd64 for component pump not found"}
2021-01-29T01:37:13.257+0800    DEBUG   TaskFinish      {"task": "Download: component=pump, version=nightly, os=linux, arch=amd64", "error": "version nightly on linux/amd64 for component pump not found"}
...
```

----

This bug can be worked-around by specifying the exact nightly version (e.g. using `v5.0.0-nightly-20210128` instead of `nightly` everywhere).

**Comment by lucklove** [comment]
I think it's not a good idea to clone nightly because many components don't have `nightly` at all...

And I'm sure you can't run the single command `tiup tidb` at all because there is no stable version in that package.

**Comment by kennytm** [comment]
The bug here is that components that *do* have nightly version aren't using nightly due to the whitelist. In particular this breaks pump/drainer cluster when using a mirror of nightly version.

**Comment by lucklove** [comment]
> The bug here is that components that _do_ have nightly version aren't using nightly due to the whitelist. In particular this breaks pump/drainer cluster when using a mirror of nightly version.

For each mirror and each component, tiup need at least one stable version for that component (the component could be pre release but not nightly only). So clone nightly (even with `v5.0.0-nightly-20210128`) will result to a not working mirror.

BTW, what's your use case to clone a nightly version? Maybe we can find some way else.
