### ISSUE TITLE
tiup dm doesn't have a config to "enable" a system service, so can't handle reboot

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiup#1110]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

use tiup deploy DM, then reboot a node

2. What did you expect to see?
dm-worker on that node autostarts after reboot

3. What did you see instead?
not start

4. What version of TiUP are you using (`tiup --version`)?
1.3.1

tiup dm --version: 1.3.2

**Comment by lance6716** [comment]
cc @lichunzhu

**Comment by 9547** [comment]
It's been fixed in #1114 Please have another try
