### ISSUE TITLE
tiup clone mirror --full break when not found resource

### ISSUE THREAD

**Issue by mianhk** [pingcap/tiup#1111]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

As I want to use a full offline mirror which convenients for me to update it by command like:
```
tiup mirror clone path/to/dir --full --os=linux --arch=amd64
```
and it may output and break:
```
Error: download resource: cluster: url https://tiup-mirrors.pingcap.com/cluster-v0.7.0-linux-amd64.tar.gz: not found
```
The problem is it won't continue even the `not found` component can be skipped.  
  

2. What did you expect to see?

Continue when `not found` component appears.

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?

**Comment by lucklove** [comment]
I have fixed this by removing the 0.x versions (which are out of date). I think it should success when you retry.

**Comment by mianhk** [comment]
OK，thanks!
