### ISSUE TITLE
Traking issue: developer support

### ISSUE THREAD

**Issue by nrc** [pingcap/tiup#112]
Running and testing TiDB and TiKV when developing is tricky. TiUp has potential to make it easy and thus to encourage contribution. This issue is for tracking ideas for ways in which TiUp could help developers. Good ideas should be spun out into their own issues.

**Comment by nrc** [comment]
Some initial ideas:

* Specify that specified or all nodes in a cluster should use a locally supplied (presumably built by the dev) version of TiDB/TiKV/PD
* Support for automatically setting up clusters and running common benchmark suites (e.g., YCSB, sysbench). Seems like the tpc component does this?
* run tools like a debugger or perf
* support for finding and reading logs
* scripting for setting up clusters

**Comment by lonng** [comment]
@nrc Great ideas.

**Comment by lonng** [comment]
I will close this issue because most of them have been implemented.
