### ISSUE TITLE
Add support for darwin/arm64 (Apple M1)

### ISSUE THREAD

**Issue by terasum** [pingcap/tiup#1122]
## General Question

I'm using the new Apple Macbook Pro with M1 chip, and when I'm running this command
```
 curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh 
```

Error occured:

```
tar: Error opening archive: Unrecognized archive format
Failed to download and/or extract tiup archive.
```

and I printed out the download URL:
```
https://tiup-mirrors.pingcap.com/tiup-darwin-arm64.tar.gz?20210202131357 -o /tmp/tiup-darwin-arm64.tar.gz
```
opened the URL, and It returns:

```
{
"error": "Document not found"
}
```

So, will you support the new Apple Mac with M1 chip?

**Comment by AstroProfundis** [comment]
Apple Silicon is supported since Go 1.16, but we build and release TiUP and buildin components with 1.13, so there would be some works to do:

 - [ ] Wait until Go 1.16 is released
 - [ ] Switch our release CI piplines to use Go 1.16, this may need rebuilding of the base image of packaging container
 - [ ] Add a new release target for `darwin/arm64`
 - [ ] Remove the error message in installer scripts
 - [ ] Testing

**Comment by terasum** [comment]
@AstroProfundis is there any resolution with Rosetta?

**Comment by AstroProfundis** [comment]
I don't use apple, have you tried to run current TiUP binaries for `darwin/amd64` with Rosetta? Is there any particular error?

**Comment by AstroProfundis** [comment]
I think we need some contributors holding M1 devices to help with the basic tests... @baurine are you using an M1 Mac?

**Comment by baurine** [comment]
> I think we need some contributors holding M1 devices to help with the basic tests... @baurine are you using an M1 Mac?

Our new colleague @shhdgit uses it and he bases Hangzhou office.

**Comment by shhdgit** [comment]
@AstroProfundis I used darwin/amd64 binary with Rosetta yesterday, but tikv does not support apple silicon yet.
[tikv/rocksdb#219](https://github.com/tikv/rocksdb/pull/219)
[tikv/tikv#9192](https://github.com/tikv/tikv/issues/9192)

And I can help test tiup.

**Comment by terasum** [comment]
Hi @AstroProfundis, according to @shhdgit, until the tikv and the rust-rocksdb fixes the Apple Silicon related issues, we can't resolve this problem.

**Comment by AstroProfundis** [comment]
Thanks for the tests.

I'm only talking about TiUP and its buildin components in this issue, AFAIK we don't support deploying tidb cluster on darwin servers in general. So it does not block this issue if only `tikv-server` is not working with Rosetta. (But `playground` might not be working on M1 devices)

I think we could support using an M1 device as console to run `tiup` once Go 1.16 is released and we have updated our release CI jobs for TiUP itself. As for the components of a TiDB cluster, that would be another (much complex) thing to figure out.

**Comment by BusyJay** [comment]
FYI, TiKV can be built on m1 natively 12 days ago. The support will also be included in 5.0.

**Comment by dragonly** [comment]
And go1.16.2 is released. Let's get rock!

**Comment by AstroProfundis** [comment]
The version 1.4.0 is [released](https://github.com/pingcap/tiup/releases/tag/v1.4.0) some minutes ago with native support of `darwin-arm64`, you can use the installer script from https://tiup.io to install `tiup` on your Apple M1 now.

Please note that this is still an experimental support of Apple ARM64 devices, some functions may not work as expected. e.g., `playground` may not fully work yet as some components may still not having their `darwin-arm64` binaries released, but we do believe that `cluster` should work as on other platforms (when you are not trying to deploy components to M1 Mac servers).

Have fun~

**Comment by Ehco1996** [comment]
> The version 1.4.0 is [released](https://github.com/pingcap/tiup/releases/tag/v1.4.0) some minutes ago with native support of `darwin-arm64`, you can use the installer script from https://tiup.io to install `tiup` on your Apple M1 now.
> 
> Please note that this is still an experimental support of Apple ARM64 devices, some functions may not work as expected. e.g., `playground` may not fully work yet as some components may still not having their `darwin-arm64` binaries released, but we do believe that `cluster` should work as on other platforms (when you are not trying to deploy components to M1 Mac servers).
> 
> Have fun~

---

latest ver `v1.4.1` tiup playgroud still can not run on m1

logs
```
Error: Playground bootstrapping failed: component pd doesn't have nightly version on platform darwin/arm64
```

so

**Comment by southwolf** [comment]
Today it still not working since Prometheus repo is not up to date - Prometheus 2.26 has M1 support but tiup only got 2.16
https://github.com/prometheus/prometheus/issues/8577

**Comment by AstroProfundis** [comment]
The `playground` component may fail to start on M1 devices as some of our released components (such as TiDB, and such as Prometheus) does not yet have am M1 package in the repository. We are already working on upgrading our release CI jobs of these components to release M1 packages for future releases.

Other TiUP builtin components such as `cluster` are not effected by this nature, they have `darwin/arm64` releases already and are working as expected.

**Comment by c4pt0r** [comment]
playground still not working 

```
╭─dongxu at dongxumba in ~ 21-07-19 - 11:30:51
╰─○  curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6305k  100 6305k    0     0  5931k      0  0:00:01  0:00:01 --:--:-- 5931k
Successfully set mirror to https://tiup-mirrors.pingcap.com
Detected shell: zsh
Shell profile:  /Users/dongxu/.zshrc
Installed path: /Users/dongxu/.tiup/bin/tiup
===============================================
Have a try:     tiup playground
===============================================
╭─dongxu at dongxumba in ~ 21-07-19 - 11:32:04
╰─○  tiup playground

Starting component `playground`: /Users/dongxu/.tiup/components/playground/v1.5.3/tiup-playground
Error: Playground bootstrapping failed: component tidb doesn't support platform darwin/arm64
Error: run `/Users/dongxu/.tiup/components/playground/v1.5.3/tiup-playground` (wd:/Users/dongxu/.tiup/data/SdZqmlw) failed: exit status 1
```

**Comment by BusyJay** [comment]
> The playground component may fail to start on M1 devices as some of our released components (such as TiDB, and such as Prometheus) does not yet have am M1 package in the repository.

Is it still true after 3 months?

**Comment by AstroProfundis** [comment]
@BusyJay Sadly, yes. The `darwin/arm64` binaries for TiDB/TiKV/PD, etc are still not released.

**Comment by zhouqiang-cl** [comment]
We will release soon

**Comment by lilyjazz** [comment]
@terasum  
We can run `tiup playground` on Apple M1 silicon. 
Only TiDB v5.1.1 and above support M1 silicon, so we suggest using `tiup playground`. 
If you try `tiup playground v5.1.0` or other lower versions, you will still run errors.

**Comment by terasum** [comment]
@lilyjazz okay, thanks
