### ISSUE TITLE
ctl: choose the matching version for ctl component by parsing args.

### ISSUE THREAD

**Issue by leoppro** [pingcap/tiup#1138]
### Background

In the current implementation, the ctl component using the latest stable version by default. but the default version usually doesn't match with the cluster version. And it's really a hard job to make sure any version of the `ctl` and `server` are compatible.(both forward-compatible and backward-compatible). So I hope that the ctl component can choose a version which is equal to the cluster version.

#### Get cluster version by pd url

when I want create a changefeed using cdc cli:
```
tiup ctl cdc cli changefeed create --sink-uri="xxx" --pd=xxxxxx
```

the ctl component can parse the args of cdc command, and know the url of PD, and then the ctl component can get the version of PD, choose a correct version for ctl-tools.

#### Get cluster version by cluster name

```
tiup ctl --cluster-name=xxx cdc cli changefeed create --sink-uri="xxx" --pd=xxxxxx
```
the ctl component can get cluster version by name.

#### `tiup cdc cli xxx` can bypass the logic about choose version in the ctl component 

maybe we can disable the command like `tiup cdc cli xxx` or redirect `tiup cdc cli xxx` to `tiup ctl cdc cli xxx` .

**Comment by AstroProfundis** [comment]
Currently one can use `tiup install ctl:v4.0.10` to install `ctl` package for a specific version, and use it with `tiup ctl:v4.0.10 cdc cli xxx`.

As for matching version of cluster, I think it's better to tell `tiup ctl` the cluster name instead of a PD URL.

**Comment by BusyJay** [comment]
I think it's a completely wrong design to make ctl a standalone component, specifying versions explicitly just make things worse. The correct design should make ctl a subcommand of cluster, and using the cluster name to decide what version should be used. For example:
```
tiup cluster ctl cluster-name tikv xxx
```

**Comment by AstroProfundis** [comment]
Since `v1.4.0`, the `ctl` requires user to set a version number when calling it.
