### ISSUE TITLE
tiup start some roles is blocked.can not continue.

### ISSUE THREAD

**Issue by mengling2012** [pingcap/tiup#1141]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

no error
[tidb@ip-172-16-4-31 ~]$ tiup cluster start tidb-vivo -R grafana,prometheus
Starting component `cluster`: /home/tidb/.tiup/components/cluster/v1.3.2/tiup-cluster start tidb-vivo -R grafana,prometheus
Starting cluster tidb-vivo...
+ [ Serial ] - SSHKeySet: privateKey=/home/tidb/.tiup/storage/cluster/clusters/tidb-vivo/ssh/id_rsa, publicKey=/home/tidb/.tiup/storage/cluster/clusters/tidb-vivo/ssh/id_rsa.pub
+ [Parallel] - UserSSH: user=tidb, host=172.16.4.31
+ [Parallel] - UserSSH: user=tidb, host=172.16.4.31
+ [Parallel] - UserSSH: user=tidb, host=172.16.4.32
+ [Parallel] - UserSSH: user=tidb, host=172.16.4.35
+ [Parallel] - UserSSH: user=tidb, host=172.16.4.33
+ [Parallel] - UserSSH: user=tidb, host=172.16.4.33
+ [Parallel] - UserSSH: user=tidb, host=172.16.4.31
+ [Parallel] - UserSSH: user=tidb, host=172.16.4.34
+ [Parallel] - UserSSH: user=tidb, host=172.16.4.33
+ [Parallel] - UserSSH: user=tidb, host=172.16.4.31
+ [Parallel] - UserSSH: user=tidb, host=172.16.4.31
+ [Parallel] - UserSSH: user=tidb, host=172.16.4.32
+ [Parallel] - UserSSH: user=tidb, host=172.16.4.34
+ [Parallel] - UserSSH: user=tidb, host=172.16.4.35
+ [ Serial ] - StartCluster
Starting component prometheus
	Starting instance prometheus 172.16.4.31:29090
	Start prometheus 172.16.4.31:29090 success
Starting component node_exporter
	Starting instance 172.16.4.31
	Start 172.16.4.31 success
Starting component blackbox_exporter
	Starting instance 172.16.4.31
	Start 172.16.4.31 success
Starting component grafana
	Starting instance grafana 172.16.4.31:23000
	Start grafana 172.16.4.31:23000 success
+ [ Serial ] - UpdateTopology: cluster=tidb-vivo

2. What did you expect to see?
tiup start role grafana and prometheus,should give shell control,but blocked shell.

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?
[tidb@ip-172-16-4-31 ~]$ tiup --version
v1.3.1 tiup
Go Version: go1.13
Git Branch: release-1.3
GitHash: d51bd0c
[tidb@ip-172-16-4-31 ~]$

**Comment by mengling2012** [comment]
![image](https://user-images.githubusercontent.com/48919190/108582404-17edf680-736e-11eb-9b63-15fabfe736ef.png)

![image](https://user-images.githubusercontent.com/48919190/108582408-1de3d780-736e-11eb-8383-251191aee3dc.png)

thanks.

**Comment by AstroProfundis** [comment]
Thanks for the report, since this is a duplicated issue, we'll follow it there.
