### ISSUE TITLE
 the 4000/4001 port check result is wrong

### ISSUE THREAD

**Issue by kkxue** [pingcap/tiup#1143]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
`tiup playground v4.0.0 --db 2 --pd 3 --kv 3 --monitor --host 192.168.0.111`
everything is ok, but the 4000/4001 port check result is wrong, it's up but tiup show Error.

2. What did you expect to see?
```
Waiting for tidb instances ready  
192.168.0.111:4000 ... Done
192.168.0.111:4001 ... Done
```

3. What did you see instead?
```
Waiting for tidb instances ready  
192.168.0.111:4000 ... Error  
192.168.0.111:4001 ... Error  
```

4. What version of TiUP are you using (`tiup --version`)?
```
v1.3.2 tiup
Go Version: go1.13
Git Branch: release-1.3
GitHash: 2d88460
```

**Comment by kkxue** [comment]
```
[root@k8s~]# nc 192.168.0.111 4000
V
5.7.25-TiDB-v4.0.0hZ{_f6)¦.{n2h7tJZsdmysql_native_password
^C
[root@k8s ~]# nc 192.168.0.111 4001
V
5.7.25-TiDB-v4.0.0)6l_jma¦.LV-x
                               #!>mysql_native_password^C

```

**Comment by kkxue** [comment]
`tiup clean --all`
do it again, all the same.

**Comment by 9547** [comment]
TiUP will check the port with mysql protocol, could you please test the ports(4000, 4001) it with MySQL client?

eg:

```bash
mysql --host 192.168.0.111 --port 4000 -u root
```

**Comment by kkxue** [comment]
@9547 thanks for your reply!
yes, i can't connect to 4000 port with mysql client in the shell, but i can connect to it with windows client like HeidiSQL.
```
[root@k8s ~]# mysql --host 192.168.0.111 -port 4000 -u root -p
Enter password: 
ERROR 1045 (28000): Access denied for user 'root'@'192.168.0.111' (using password: NO)
```

**Comment by 9547** [comment]
The log you provided shows that the connection was working, but the authentication failed

>
```
[root@k8s ~]# mysql --host 192.168.0.111 -port 4000 -u root
ERROR 1045 (28000): Access denied for user 'root'@'192.168.0.111' (using password: YES)
```

be careful, `-port 4000` parsed as database password, not the port, use `--port 4000` instead.

But what makes me curious is that the connection is normal, but TiDB reports failed :thinking:

**Comment by kkxue** [comment]
yes, let's do some code debugging

**Comment by kkxue** [comment]
just add db.timeout:
`tiup playground v4.0.0 --db 2 --db.timeout 180 --pd 3 --kv 3 --monitor --host 192.168.0.111`
