### ISSUE TITLE
tiup dm patch didn't replace json files

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiup#1146]
## Feature Request

**Is your feature request related to a problem? Please describe:**

found there's something wrong in prometheus & grafana config files, so I build a patch tar file (the monitor config is included in dm-master tar file) and want to use `tiup dm patch` to replace the config files. But seems patch will only replace binary file.

**Describe the feature you'd like:**

provide a way to patch the prometheus & grafana config files

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
cc @lichunzhu

**Comment by lucklove** [comment]
Prefer to use [dashboards_dir and rules_dir](https://docs.pingcap.com/zh/tidb/stable/tiup-cluster#%E6%9B%B4%E6%96%B0%E9%85%8D%E7%BD%AE) instead of patch.

**Comment by lance6716** [comment]
> Prefer to use [dashboards_dir and rules_dir](https://docs.pingcap.com/zh/tidb/stable/tiup-cluster#%E6%9B%B4%E6%96%B0%E9%85%8D%E7%BD%AE) instead of patch.

When providing hotfix, I think we should try reducing user's action. Seems above method requires a builtin linux editor, is there a programmable, non-interactive builtin linux editor so we could write a script to replace json?

**Comment by lucklove** [comment]
> > Prefer to use [dashboards_dir and rules_dir](https://docs.pingcap.com/zh/tidb/stable/tiup-cluster#%E6%9B%B4%E6%96%B0%E9%85%8D%E7%BD%AE) instead of patch.
> 
> When providing hotfix, I think we should try reducing user's action. Seems above method requires a builtin linux editor, is there a programmable, non-interactive builtin linux editor so we could write a script to replace json?

If you are using a script, you can just overwrite `~/.tiup/storage/cluster/clusters/<cluster-name>/meta.yaml` instead of using an editor.
