### ISSUE TITLE
Question: how to set multiple port of TiDB when cluster start via playground

### ISSUE THREAD

**Issue by hidehalo** [pingcap/tiup#1160]
## General Question

How to set multiple port of TiDB when cluster start via playground?

**Comment by 9547** [comment]
Currently in `tiup playground`, TiDB's port was dynamically allocated, don't support to manually set.

**Comment by hidehalo** [comment]
> Currently in `tiup playground`, TiDB's port was dynamically allocated, don't support to manually set.

Thx! it's seems statically for now.
