### ISSUE TITLE
When installing tiup cluster, an error occurred 'Error: checksum mismatch'

### ISSUE THREAD

**Issue by kecikeci** [pingcap/tiup#1169]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

tiup cluster

It appeared during the installation last night, I think there is a new cluster version last night

2. What did you expect to see?
install success

3. What did you see instead?
![image](https://user-images.githubusercontent.com/32811349/109584609-d6fb9c00-7b3c-11eb-8714-973ebeba23cb.png)

4. What version of TiUP are you using (`tiup --version`)?
v1.3.2 tiup

**Comment by kagb** [comment]
Same error message, tiup playground failed at my first attempt.
![image](https://user-images.githubusercontent.com/20009087/109591243-26939500-7b48-11eb-8daf-cbfb2f8148f6.png)

**Comment by kecikeci** [comment]
下载下来看了下包，昨晚20点多更新了新的安装包，可能没更新效验文件。

![image](https://user-images.githubusercontent.com/32811349/109592038-91919b80-7b49-11eb-9cb4-605e94fd34d0.png)

**Comment by yangzhenlong** [comment]
@kecikeci 现在依然有这个问题
![image](https://user-images.githubusercontent.com/17606242/109609129-e17e5b80-7b65-11eb-91ed-5fc2476f815e.png)

**Comment by AstroProfundis** [comment]
Thanks for the report, we are currently working on it.

**Comment by AstroProfundis** [comment]
We have just force re-synced files on CDN, it should be fixed in few minutes.

**Comment by dragonly** [comment]
we should design a local usable TiUP, regardless of the CDN and network issues.

**Comment by AstroProfundis** [comment]
It does not, the error in issue was only affecting users when they want to install new components, it does not affect ones already installed.

In the mean time, we're also working on reducing polling of manifests from network, and you can always use an offline mirror to get rid of all network requests.
