### ISSUE TITLE
Require specifying version when running `tiup br/cdc/tidb-lightning`

### ISSUE THREAD

**Issue by overvenus** [pingcap/tiup#1190]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Prior tiup v1.3.2, `tiup br/cdc/tidb-lightning` uses the latest release to run commands.
However there is a compatibility bug between TiCDC 4.0.10 and TiCDC 5.0.0-rc. Creating a changefeed via 5.0.0-rc will cause TiCDC v4.0.10 cluster hang. This issue is reported by https://asktug.com/t/topic/68081

**Describe the feature you'd like:**

To void potential compatibility bug between major releases, I suggest that tiup requires specifying version when running `tiup br/cdc/tidb-lightning`.

```
// Should return an error that states cdc version is required.
$ tiup cdc version

// OK
$ tiup cdc:v4.0.11 version
Starting component `cdc`: /home/stn/.tiup/components/cdc/v4.0.11/cdc version
Release Version: v4.0.11
Git Commit Hash: 52a6d9ea6da595b869a43e13ae2d3680354f89b8
Git Branch: heads/refs/tags/v4.0.11
UTC Build Time: 2021-02-25 16:40:37
Go Version: go version go1.13 linux/amd64
```

**Describe alternatives you've considered:**

N/A

**Teachability, Documentation, Adoption, Migration Strategy:**

N/A

**Comment by lucklove** [comment]
We will add an environment variable called `TIUP_USER_INPUT_VERSION`, when there is a specifying version, the variable will be set, otherwise, it will be empty. 

The component who doesn't want to run in TiUP env when the user doesn't specify a version can refuse to execute like this:

```go
if os.Getenv("TIUP_WORK_DIR") != "" && os.Getenv("TIUP_USER_INPUT_VERSION") == "" {
    return errrors.New("you must specify a version like tiup br:v4.0.0")
}
```
