### ISSUE TITLE
Unable to patch a stopped cluster

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tiup#1199]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```
% tiup cluster stop test-cluster
% tiup cluster patch -R tikv test-cluster tikv-server.tar.gz
```

2. What did you expect to see?

Patch successfully.

3. What did you see instead?

It fails as it tries to evict leader on a **stopped** cluster.

4. What version of TiUP are you using (`tiup --version`)?

```
v1.3.2 tiup
Go Version: go1.13
Git Branch: release-1.3
GitHash: 2d88460
```

**Comment by lucklove** [comment]
We will enable this by `--offline` flag after [v1.4.0](https://github.com/pingcap/tiup/pull/1204/files) released ([#1096](https://github.com/pingcap/tiup/pull/1096))
