### ISSUE TITLE
Manifest structure

### ISSUE THREAD

**Issue by nrc** [pingcap/tiup#120]
We should properly design the various manifests. We might want to follow TUF (see #114). In any case we should consider the following points:

* Manifests should contain the URLs of components
* Manifests should contain the hashes of components
* Manifests should be read-only: they should have permanent URLs and should not be updated (other than the top-level manifest which specifies the current versions and should be as small as possible).

See also #117 #119

**Comment by lucklove** [comment]
I think this is finished
