### ISSUE TITLE
Unable to update nightly version

### ISSUE THREAD

**Issue by HunDunDM** [pingcap/tiup#1203]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

`tiup update --nightly --all`

2. What did you expect to see?

* Update the nightly version of pd, tidb, tikv to the latest version.

3. What did you see instead?

The nightly version has not been updated.

```
❯ tiup update --nightly --all
component cluster version v1.3.4 is already installed
component ctl version v4.0.11 is already installed
component grafana version v4.0.11 is already installed
component pd version v4.0.11 is already installed
component playground version v1.3.4 is already installed
component prometheus version v4.0.11 is already installed
component tidb version v4.0.11 is already installed
component tikv version v4.0.11 is already installed
Updated successfully!
```

I can only use `tiup update pd:nightly tikv:nightly tidb:nightly` to update.

4. What version of TiUP are you using (`tiup --version`)?

* v1.3.4

**Comment by lucklove** [comment]
Fixed in https://github.com/pingcap/tiup/pull/1248
