### ISSUE TITLE
Permanent URLs

### ISSUE THREAD

**Issue by nrc** [pingcap/tiup#121]
All artifacts (other than the top-level manifest) should have permanent URLs, that is once a resource is available at a URL, it should never change, nor should it ever disappear.

See [post about similar issues in Rustup](https://internals.rust-lang.org/t/future-updates-to-the-rustup-distribution-format/4196)

**Comment by lonng** [comment]
@nrc Now this method is the same for offline mirroring and online mirroring, and it is relatively simple. If we use Permanent URLs, this seems not easy to handle.

**Comment by lucklove** [comment]
For the same mirror, it does have permanent URLs, I think. The cloned offline-mirror is a different mirror from the online one, so their URLs are not the same.
