### ISSUE TITLE
tiup 1.3.4 br& cdc nightly not found after install br&cdc

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiup#1221]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

- [root@172.16.5.106 br]$ tiup install br:nightly
download https://tiup-mirrors.pingcap.com/br-v5.0.0-nightly-20210317-linux-amd64.tar.gz 40.83 MiB / 40.83 MiB 100.00% 10.11 MiB p/s

- [root@172.16.5.106 br]$ tiup br:nightly -V
Failed to start component `br`
Error: version v5.0.0-nightly-20210314 on linux/amd64 for component br not found

2. What did you expect to see?

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?

1.3.4

**Comment by lucklove** [comment]
This is a known issue and has been fixed in v1.3.5
