### ISSUE TITLE
scale-out action doesn't start tiflash success

### ISSUE THREAD

**Issue by lucklove** [pingcap/tiup#1226]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I deployed a cluster which doesn't has any TiFlash node, and then scale-out one TiFlash with the command `tiup cluster scale-out test tiflash.yaml` and execute `tiup cluster display test`.

2. What did you expect to see?
The status of TiFlash node should be `UP`

3. What did you see instead?
The status of TiFlash node is `N/A`. And after I execute `tiup cluster start test -R tiflash`, It's `UP`.

And I tried to debug why this happens, I found the [guide to scale-out tiflash](https://docs.pingcap.com/zh/tidb/stable/scale-tidb-using-tiup#%E6%89%A9%E5%AE%B9-tiflash-%E8%8A%82%E7%82%B9) which says you should `tiup ctl pd -u <pd-host>:<pd-port> config set enable-placement-rules true` before scale-out TiFlash. 

But I found we have do this in the scale-out stage: https://github.com/pingcap/tiup/blob/master/pkg/cluster/spec/tiflash.go#L657

Then I debug the result of `pdClient.UpdateReplicateConfig(bytes.NewBuffer(enablePlacementRules))`, I found that it returns nil error in both `scale-out` and `start` action, but only changes `enable-placement-rules` (`curl pd:port/pd/api/v1/config|grep enable-placement-rules`) to `true` in `start` action. 

In another word, the `pdClient.UpdateReplicateConfig` not work when you `scale-out` tiflash but work when you start `tiflash`. That's not reasonable.

4. What version of TiUP are you using (`tiup --version`)?
v1.3.5 and master

**Comment by 9547** [comment]
I've reproduced this bug, and found what's going on.

In the `scale-out` phase, the PD endpoints are empty, so the POST request is not sent out:

https://github.com/pingcap/tiup/blob/998926208ab2b8eb77b877f1b530ab00d4295fbf/pkg/cluster/spec/tiflash.go#L652-L664


I'll try to fix it.

**Comment by lucklove** [comment]
> I've reproduced this bug, and found what's going on.
> 
> In the `scale-out` phase, the PD endpoints are empty, so the POST request is not sent out:
> 
> https://github.com/pingcap/tiup/blob/998926208ab2b8eb77b877f1b530ab00d4295fbf/pkg/cluster/spec/tiflash.go#L652-L664
> 
> I'll try to fix it.

Awesome!!! Then we don't need the user to set `enable-placement-rules` before scale-out, this improve user experience a lot.
