### ISSUE TITLE
tiup ctl not support “dmctl”

### ISSUE THREAD

**Issue by buggithubs** [pingcap/tiup#1232]
## Feature Request

**Describe the feature you'd like:**

**tiup ctl not support “dmctl”**

```
# tiup ctl dm
Starting component `ctl`: /root/.tiup/components/ctl/v5.0.0-rc/ctl dm
Error: ctl only supports tidb, tikv, pd, binlog, etcd and cdc currently


Usage:
  tiup ctl {tidb/pd/tikv/binlog/etcd/cdc} [flags]
```

```
# tiup dm ctl
Starting component `dm`: /root/.tiup/components/dm/v1.3.6/tiup-dm ctl

Error: unknown command "ctl" for "tiup"
```

**Comment by 9547** [comment]
Two things to do:

- [ ] enable `dmctl` in [tiup/main.go · pingcap/tiup](https://github.com/pingcap/tiup/blob/4d5347df369991ee99ad203085d18c0c2eacc9ae/components/ctl/main.go#L1)
- [ ] publish `ctl` contains the binary of `dmctl`

**Comment by lucklove** [comment]
> @buggithubs Currently, `ctl` only contains the TiDB related components, if you want to use `dmctl`, you can use directly:
> 
> ```shell
> tiup dmctl -h
> ```
> 
> If we want to add `dmctl` into `ctl`, two things need to do:
> 
> * [ ]  enable `dmctl` in [tiup/main.go · pingcap/tiup](https://github.com/pingcap/tiup/blob/4d5347df369991ee99ad203085d18c0c2eacc9ae/components/ctl/main.go#L1)
> * [ ]  publish `ctl` contains the binary of `dmctl`
> 
> But we did not add it, @lucklove do you know the reason, is it the reason that we think DM and TIDB should be separated?

You are right, DM and TiDB should be separated because their versions are asynchronous. So there is no plan to add `dmctl` to `ctl` unless DM use the same version with TiDB.

**Comment by lucklove** [comment]
Solution: use `tiup dmctl` please. If in the future, DM keep synchronous version with TiDB, we will add it to `ctl`.
