### ISSUE TITLE
Only self-update when necessary

### ISSUE THREAD

**Issue by nrc** [pingcap/tiup#124]
If there are no updates, self-update should not do anything, rather than re-install the old version.

**Comment by lonng** [comment]
@nrc, I think we can save the md5 file in ~/.tiup/bin/ and do nothing while the md5 was unchanged. How do you think?

**Comment by nrc** [comment]
I think it is a good plan to do initially. When we are thinking about overall architecture we should consider self-update. We probably want a manifest for tiup and then just check the current and new version numbers. We may even be able to treat TiUp like any other component in terms of how and whether we download and install (though actually installing will always be a bit different).

**Comment by nrc** [comment]
This is covered by the design in #193

**Comment by lonng** [comment]
Fixed
