### ISSUE TITLE
add check command for  scale-out cluster

### ISSUE THREAD

**Issue by King-Dylan** [pingcap/tiup#1244]
## Feature Request
add check command for  scale-out cluster
**Is your feature request related to a problem? Please describe:**

Reduce the probability of error reporting during scale-out cluster
**Describe the feature you'd like:**

support tiup cluster check {cluster-name} scale-out.yaml (Check content refer to deployment check command)
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by 9547** [comment]
@King-Dylan  you can directly use `tiup cluster check scale-out.yaml` to check the scaled part.

**Comment by kolbe** [comment]
@9547 when I do `tiup cluster check scale-out.yaml`, tiup seems to make some assumptions about which cluster this operation will apply to. How does it decide? I haven't given a cluster name anywhere, so where does it get the "GlobalOptions" from?

**Comment by jsvisa** [comment]
> @9547 when I do `tiup cluster check scale-out.yaml`, tiup seems to make some assumptions about which cluster this operation will apply to. How does it decide? I haven't given a cluster name anywhere, so where does it get the "GlobalOptions" from?

Firstly, this command doesn't know which cluster this operation will apply to. 
So the `cluster check` subcommand will check the new topology file compared with all existing clusters(the  meta file under `$TIUP_HOME/storage/cluster/`

**Comment by 9547** [comment]
> tiup seems to make some assumptions about which cluster this operation will apply to. How does it decide? I haven't given a cluster name anywhere, so where does it get the "GlobalOptions" from?

Firstly, this command doesn't know which cluster this operation will apply to.
So the cluster check subcommand will check the new topology file compared with all existing clusters(the meta file under $TIUP_HOME/storage/cluster/

**Comment by kolbe** [comment]
Part of the `check --apply` operation is to add entries to /etc/security/limits.conf for global.user. Are you saying that `tiup check` will scan through all clusters in $TIUP_HOME/storage/cluster/ and ... create and apply the limit to all of the users?

**Comment by srstack** [comment]
https://github.com/pingcap/tiup/pull/1659
