### ISSUE TITLE
Fail to start grafana

### ISSUE THREAD

**Issue by Fullstop000** [pingcap/tiup#125]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```
tiup grafana
```

2. What did you expect to see?

Run grafana maybe

3. What did you see instead?
```
~ tiup grafana
Failed to start component `grafana`
Error: fork/exec /home/fullstop/.tiup/components/grafana/v6.7.1/bin/grafana: no such file or directory
```

4. What version of TiUP are you using (`tiup --version`)?
```
~ tiup --version
tiup version v0.0.3 tiup
```

**Comment by Fullstop000** [comment]
I find the package script using entry `bin/grafana` but the binary should be `grafana-server` actually ?
```
~/.tiup/components/grafana/v6.7.1/bin ls
grafana-cli  grafana-cli.md5  grafana-server  grafana-server.md
```

**Comment by lonng** [comment]
@Fullstop000 Currently, the playground doesn't support the Grafana. You can track this via issue #63

**Comment by Fullstop000** [comment]
I just want to set up a Grafana individually. Is this feature supported?

**Comment by lonng** [comment]
@Fullstop000 not yet.

**Comment by lonng** [comment]
Fixed
