### ISSUE TITLE
tiup patch & configuration

### ISSUE THREAD

**Issue by buggithubs** [pingcap/tiup#1254]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

tiup cluster patch xxx -R tikv tikv.tgz

**Update tikv binary and expect to update tikv configuration file**

At present: I need to operate in two steps, `patch` binary + `reload` config

**Comment by AstroProfundis** [comment]
We are not going to implement this, as combining two commands with arguments will make them non-idempotent. i.e., you can not retry a command like `patch -R tikv tikv.tgz --reload` without any side affect.

For the same reason, we don't support things like `deploy --start`.
