### ISSUE TITLE
tiup cluster ”patch、reload“ add “Do you want to continue”

### ISSUE THREAD

**Issue by buggithubs** [pingcap/tiup#1255]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

```
tiup cluster reload bigcluster -R tikv
tiup cluster patch bigcluster -R tikv

```

It is expected that the above two functions will be confirmed again

`Do you want to continue? [y/N]:(default=N) 
`

**Comment by 9547** [comment]
The same to `rename`
