### ISSUE TITLE
support deploy ctl program

### ISSUE THREAD

**Issue by kevinbin** [pingcap/tiup#1282]
## Feature Request

**Is your feature request related to a problem? Please describe:**
There is no ctl program in the bin directory of the cluster deployed by tiup

**Describe the feature you'd like:**
I hope that the deployment cluster of tiup can also automatically deploy the ctl program to the bin directory

**Comment by AstroProfundis** [comment]
It is by design not to distribute `*-ctl` binaries during `deploy` process of a cluster. You can use `tiup ctl:vx.y.z xxx` to use them on the console server, where `www` is the prefix of `*.ctl`, e.g., `tiup ctl:v4.0.12 pd xxx` means using `pd-ctl` version `4.0.12` and with argument `xxx`.

**Comment by kevinbin** [comment]
Local operations are not supported in this way

**Comment by lucklove** [comment]
What about install tiup on that tikv host then?

```sh 
curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh 
source ~/.bash_profile
tiup ctl:<cluster_version> xxx
```
