### ISSUE TITLE
Tiup version is not match after update

### ISSUE THREAD

**Issue by lhy1024** [pingcap/tiup#1283]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

update tiup version

2. What did you expect to see?

tiup version is the newest

3. What did you see instead?

![image](https://user-images.githubusercontent.com/19542290/113677517-3f1b4000-96f0-11eb-89e1-de623e0f8dc3.png)

4. What version of TiUP are you using (`tiup --version`)?
```
tiup --version                                                                                                                                                                                 ~
1.4.0 tiup
Go Version: go1.16.2
Git Ref: v1.4.0
GitHash: eb335e6ad9d0dc19d1c43db422cd409d62bc3cea
```

**Comment by AstroProfundis** [comment]
playground is an independent component of tiup, you can use `tiup update playground` to upgrade it. Also, you can use `tiup list <component>` to check what version(s) are currently installed.

**Comment by lhy1024** [comment]
'tiup update playground' is valid!

**Comment by lhy1024** [comment]
but `tiup list tiup` doesn't show which version is installed.
![image](https://user-images.githubusercontent.com/19542290/113679968-f3b66100-96f2-11eb-9a93-baab2612a584.png)

**Comment by AstroProfundis** [comment]
yeah `tiup` itself is special, you can't use `tiup install` to install a specific `tiup` binary either. the only proper way to check currently tiup version is `tiup --version` at present. hint that you can also use `--version` for some components, like `tiup playground --version` and `tiup cluster --version` to see the version of component (not the version of `tiup`), but not all components have the same arguments.
