### ISSUE TITLE
Support fish shell

### ISSUE THREAD

**Issue by sykp241095** [pingcap/tiup#129]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When using fish, tiup can be installed, but no shell profile generated, so still can not use properly.

**Describe the feature you'd like:**

Support tiup in fish shell, by steps:
* curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | **sh**
* \# set PATH in .config/fish/config.fish
* source .config/fish/config.fish

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

Fish docs: https://fishshell.com/

**Comment by Max-Cheng** [comment]
```
set -x TIUPPATH $HOME/.tiup
set -x PATH $PATH $TIUPPATH/bin
```

Work for me
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/21263915/113552640-fe0c2880-9628-11eb-9163-98b987ae2309.png">

**Comment by sykp241095** [comment]
@Max-Cheng Thanks a lot !

Maybe we can put these two command into docs or even command line help message.
