### ISSUE TITLE
tiup playground can not stop in some case

### ISSUE THREAD

**Issue by lhy1024** [pingcap/tiup#1290]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
stop playground

2. What did you expect to see?

can stop

3. What did you see instead?

can not
![image](https://user-images.githubusercontent.com/19542290/113809432-a988ba80-979a-11eb-9e68-54516fb9dac2.png)

4. What version of TiUP are you using (`tiup --version`)?

1.4

**Comment by AstroProfundis** [comment]
The `playground` component does have an `stop` subcommand, it stops the cluster when you interrupt the process (Ctrl + C).

Or did you find any process remains running after the playground process exited?
