### ISSUE TITLE
`tiup mirror init` does not work

### ISSUE THREAD

**Issue by daniel-nichter** [pingcap/tiup#1299]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
% ./tiup mirror init
Error: initial repository from mirror(https://tiup-mirrors.pingcap.com/) failed: cannot open the initial root.json at /Users/dn/.tiup/bin/root.json
```

That was run in the root dir of this repo.

Note: I have _zero_ setup of anything TiDB related--a completely empty env. `$HOME/.tiup/` doesn't exist. No `TI*` env vars.

2. What did you expect to see?

Expect `tiup mirror init` to "Just Work", or give more specific error message about what pre-conditions aren't met.

3. What did you see instead?

No matter how I run it, or what dirs I create, or even if I use a blank `/Users/dn/.tiup/bin/root.json`, it errors as shown above.

4. What version of TiUP are you using (`tiup --version`)?

Commit f3f35be371c76889258f821b459ed0d6d9cf53cd
Mac
Local build (just `go build`)
go1.16

**Comment by kolbe** [comment]
This is caused by incorrect setup of the TiUP environment. No root.json file was installed after `tiup` was built. I think the handling for that situation should be much better. #829 and #837 try to address this but I don't think they do a very thorough job.
