### ISSUE TITLE
Improve documentation for `tiup mirror`

### ISSUE THREAD

**Issue by kolbe** [pingcap/tiup#1304]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The required steps to create a tiup mirror are not very clear. There's already some documentation about the process at https://docs.pingcap.com/tidb/dev/tiup-mirror-reference but there's nothing that really explains the full set of steps:

`tiup mirror init`
`tiup mirror genkey`
`tiup mirror grant`
`tiup mirror publish`

**Describe the feature you'd like:**

A thorough set of documentation that explains the steps required to create a TiDB mirror.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by dveeden** [comment]
Let's combine this with https://github.com/pingcap/docs/issues/7362
