### ISSUE TITLE
the content of 'The stable version' should follow the actual release version when a user uses 'tiup playground'.

### ISSUE THREAD

**Issue by lilyjazz** [pingcap/tiup#1315]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

`$ tiup playground`

2. What did you expect to see?
```
Starting component `playground`: /root/.tiup/components/playground/v1.4.1/tiup-playground
Use the latest stable version: v5.0.0

    Specify version manually:   tiup playground <version>
    The stable version:         tiup playground v 4.0.0 
    The nightly version:        tiup playground nightly
```
The stable version is incorrect. 'v5.0.0' should be dispalyed.

3. What did you see instead?
```
Starting component `playground`: /root/.tiup/components/playground/v1.4.1/tiup-playground
Use the latest stable version: v5.0.0

    Specify version manually:   tiup playground <version>
    The stable version:         tiup playground v4.0.0
    The nightly version:        tiup playground nightly
```
the content of 'The stable version' should follow the actual release version. 

4. What version of TiUP are you using (`tiup --version`)?
```
$ tiup --version
1.4.0 tiup
Go Version: go1.16.2
Git Ref: v1.4.0
GitHash: eb335e6ad9d0dc19d1c43db422cd409d62bc3cea
```

**Comment by AstroProfundis** [comment]
This is a prompted example to show user how to start `playground` with a  specified version of TiDB. So the `v4.0.0` part in it is hard coded and does not reflect any actual version used.

I'll try to update the message to make it less confusing.
