### ISSUE TITLE
Check system info throws an error “os vendor rhel not supported”

### ISSUE THREAD

**Issue by 7yyo** [pingcap/tiup#1332]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

run `tiup check`

2. What did you expect to see?

run success.

3. What did you see instead?

os vendor `rhel` not supported

4. What version of TiUP are you using (`tiup --version`)?

I think it should be `rhel` ?
https://github.com/pingcap/tiup/blob/fa0a7ce14e067b1377b58079788d74ef693f82d6/pkg/cluster/operation/check.go#L153

```go
switch si.OS.Vendor {
	case "debian":
		si.OS.Release = slurpFile("/etc/debian_version")
	case "ubuntu":
		if m := reUbuntu.FindStringSubmatch(si.OS.Name); m != nil {
			si.OS.Release = m[1]
		}
	case "centos":
		if release := slurpFile("/etc/centos-release"); release != "" {
			if m := reCentOS.FindStringSubmatch(release); m != nil {
				si.OS.Release = m[2]
			}
		}
	case "rhel":
		if release := slurpFile("/etc/redhat-release"); release != "" {
			if m := reRHEL.FindStringSubmatch(release); m != nil {
				si.OS.Release = m[1] + " " + m[2]
			}
		}
	}
```

**Comment by AstroProfundis** [comment]
Thanks for the report, could you also share with us the content of your `/etc/os-release`?

**Comment by 7yyo** [comment]
> Thanks for the report, could you also share with us the content of your `/etc/os-release` and `/etc/redhat-release`?

Red Hat Enterprise Linux Server release 7.9 (Maipo)
