### ISSUE TITLE
tiup cluster upgrade dba-test --force "code 500"

### ISSUE THREAD

**Issue by jacktd9** [pingcap/tiup#1339]
## Bug Report

     适用 tiup upgrade .. force 升级集群，

     发现滚动 pd 过程因 leader 选举没成功 “redirect to not leader” ，而做了其他节点的 restart，

     但在 Upgrading component tikv 过程中，需要从 PD 里拿信息，因 get 不到 pd leader ，进而升级进程被中断。

1. What did you do?

    tiup cluster upgrade xxx v4.0.12 --force

2. What did you expect to see?

    Upgraded cluster `xxx` successfully

3. What did you see instead?

        1).     tiup:

        Error: no endpoint available, the last err was: error requesting http://172.16.4.51:4799/pd/api/v1/config, response: redirect to not leader, code 500
 ![image](https://user-images.githubusercontent.com/63033738/116644321-a5207d80-a9a5-11eb-8de4-cc60c19df596.png)

        2).     pd:

        redirect to not leader

 ![image](https://user-images.githubusercontent.com/63033738/116644347-b4073000-a9a5-11eb-8e9e-9cdfc54a181f.png)

4. What version of TiUP are you using (`tiup --version`)?

```
    1.4.0 tiup
    Go Version: go1.16.2
    Git Ref: v1.4.0
    GitHash: eb335e6ad9d0dc19d1c43db422cd409d62bc3cea
```

**Comment by lucklove** [comment]
@AstroProfundis we should ignore the `no leader` error, too.

**Comment by AstroProfundis** [comment]
I'm not comfortable with the "all errors are 500" implementation of PD :(
