### ISSUE TITLE
Support json output

### ISSUE THREAD

**Issue by kolbe** [pingcap/tiup#1355]
## Feature Request

**Is your feature request related to a problem? Please describe:**

It would be nice to be able to get information about clusters in a machine-readable format, such as json.

**Describe the feature you'd like:**

`tiup cluster display` (and maybe some other commands) should support a flag like `--format` or `--output` that can accept `json` (and maybe other options?) as an output format.

**Why the featue is needed:**

I want a machine-readable output format for cluster information so I can automatically configure my application to connect to the set of tidb instances in the cluster.

**Describe alternatives you've considered:**

Trying to parse the output of `tiup cluster display` in its current format is really unwieldy and unrealistic.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by dveeden** [comment]
I think we can close this. We have #1208 for long term solutions. And #1358 for `tiup cluster display --json` which is for the specific usecase mentioned here.

**Comment by AstroProfundis** [comment]
Thanks, please update in #1208 if any new idea comes.
