### ISSUE TITLE
tiup cluster display warnings when placement rules are set

### ISSUE THREAD

**Issue by pcqz** [pingcap/tiup#1371]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

- Set placement-rules and add label_constraints using pd-ctl
- Execute `tiup cluster display <cluster-name>`

2. What did you expect to see?
The cluster info display normal. 

3. What did you see instead?
There are some warnings and 'xxxx' below refers to label_constraits key name.

  ```
  WARN: there is something wrong with TiKV labels, which may cause data losing:
      label name 'xxxx' is not specified in pd config (replication.location-labels: [host])
  ```

4. What version of TiUP are you using (`tiup --version`)?
tiup cluster v1.4.3

**Comment by AstroProfundis** [comment]
This is by design, this warning is shown when the label setting in `meta.yaml` is different with what PD actually holds.

**Comment by pcqz** [comment]
TiKV nodes label in 'tikv.toml' is the same with PD localtion-lables settting, but `tiup cluster display` get labels by pd client, including TiKV nodes label and placement rule label. There is [an example of placement rule setting](https://docs.pingcap.com/tidb/stable/configure-placement-rules#scenario-4-add-two-follower-replicas-for-a-table-in-the-beijing-node-with-high-performance-disks), the location_label setting here is '[host]', but store labels maybe include host, zone and disk.

**Comment by AstroProfundis** [comment]
@lucklove PTAL

**Comment by lucklove** [comment]
We will disable this check once the user enable placement rule
