### ISSUE TITLE
 tiup dumpling command issue:  flag needs an argument: 'h' in -h

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiup#1379]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

- Execute "]$ tiup dumpling -u root -P 4000 -h 172.16.4.96 --filetype sql -t 8 -o /data3/tidb-800g-data -F 25600MiB", output:
   
![image](https://user-images.githubusercontent.com/78345569/119121977-9e46d100-ba60-11eb-9b40-79c32ba9d1a7.png)

- Actually this command can execute sucessfully if without tiup:

![image](https://user-images.githubusercontent.com/78345569/119122398-0e555700-ba61-11eb-8925-02b2e4f2ffb6.png)

2. What did you expect to see?

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?
 1.4.3 tiup
Go Version: go1.16.4
Git Ref: v1.4.3
GitHash: 0faec47a553138b68c4e1529a771746cc2e17011

**Comment by AstroProfundis** [comment]
dupe w/ #1335
