### ISSUE TITLE
Partially destroy cluster

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tiup#138]
## Feature Request

**Describe the feature you'd like:**

Tiup seems to only support destroy the whole cluster. But during development or re-deploy, not all data are expected to be cleaned, especially metrics. In short, we need a cluster version `clean`, working similar to `unsafe_cleanup_data` playbook from tidb-ansible.

**Comment by lonng** [comment]
@BusyJay How about `tiup cluster clean <cluster-name>`

**Comment by BusyJay** [comment]
LGTM

**Comment by lonng** [comment]
Dup with #396 and fixed in #644
