### ISSUE TITLE
Port conflicts between DM and TIDB are not detected

### ISSUE THREAD

**Issue by together-wang** [pingcap/tiup#1381]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Deploy DM and TIDB clusters, Prometheus and Grafana port conflicts not detected

2. What did you expect to see?

Add port conflict detection for DM and tidb cluster before deployment

3. What did you see instead?

![image](https://user-images.githubusercontent.com/44355590/119292743-8f8c3400-bc83-11eb-8f9a-c3723caa9e30.png)
![image](https://user-images.githubusercontent.com/44355590/119292820-b77b9780-bc83-11eb-913d-c1669d2daff2.png)

4. What version of TiUP are you using (`tiup --version`)?
```
[tidb@node127 dm]$ tiup --version
1.4.1 tiup
Go Version: go1.16.3
Git Ref: v1.4.1
GitHash: cd19b75b6418f627d121d43d4b1e41af673526cf
```

**Comment by AstroProfundis** [comment]
`dm` and `cluster` are totally different components, and they don't share any storage on the console at all. So it's not possible as of now to detect conflict between them.

We'd also be appreciated if there's any suggestion about how to solve similar issues.
