### ISSUE TITLE
Support cluster new/init

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tiup#139]
## Feature Request

**Describe the feature you'd like:**
I would like a command "new" or "init" to help build up a cluster configuration. It's very inconvenient to write topology.yaml now. I have to search and then copy/paste and do customization.

With the new command, user doesn't need to search around anymore. A `new` command should create a folder and then create an example topology.yaml inside the folder. An `init` command should just create an the file in current directory.

`new` can also accept a template name to indicate what the deploy topology is. So users just need to update the details like hosts and ports without remembering the boilerplate.

**Comment by lonng** [comment]
@BusyJay This feature in our roadmap. And we will implement it in Apri.

**Comment by AstroProfundis** [comment]
The `tiup-cluster template` subcommand is supported in `v1.4.0`.
