### ISSUE TITLE
"tiup dumpling" doesn't accept short parameter -B or -h

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiup#1392]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Run below command to dump TiDB:
  tiup dumpling -B test --filetype csv -o /home/tidb/dumpling/test/csv
  tiup dumpling -u root -P 4000 -h 172.16.5.161 --database test --filetype csv -o /home/tidb/dumpling/test/csv

2. What did you expect to see?
  Dump TiDB should be successful.

3. What did you see instead?
Below errors are seen when running "tiup dumpling" with -B or -h parameter, while it is OK for long option --database or --host.

>>>>
[root@CentOS76_VM ~]# tiup dumpling -B test --filetype csv -o /home/tidb/dumpling/test/csv             
Error: use `tiup install test` to install component `test` first: component not installed

[root@CentOS76_VM ~]# tiup dumpling -u root -P 4000 -h 172.16.5.161 --database test --filetype csv -o /home/tidb/dumpling/test/csv
flag needs an argument: 'h' in -h
Dumpling is a CLI tool that helps you dump MySQL/TiDB data
...
Cannot fetch help message from /root/.tiup/components/dumpling/v5.0.1/dumpling failed: exit status 2

4. What version of TiUP are you using (`tiup --version`)?
[root@CentOS76_VM ~]# tiup --version
1.4.4 tiup
Go Version: go1.16.4
Git Ref: v1.4.4
GitHash: 0d0507355211fe16f95e1d00ed00c39f09c7565d

**Comment by AstroProfundis** [comment]
dupe w/ #1335
