### ISSUE TITLE
Support SSH agent in "builtin" SSH

### ISSUE THREAD

**Issue by kolbe** [pingcap/tiup#1393]
## Feature Request

**Is your feature request related to a problem? Please describe:**

`tiup cluster` cannot use an SSH agent forwarded via SSH:

```
ubuntu@ip-10-0-6-134:~$ echo $SSH_AUTH_SOCK
/tmp/ssh-R7FnLPR1Yf/agent.2280

$ tiup cluster  check --apply topology.yaml
Starting component `cluster`: /home/ubuntu/.tiup/components/cluster/v1.4.4/tiup-cluster check --apply topology.yaml

Error: Failed to read SSH identity file '/home/ubuntu/.ssh/id_rsa' (cliutil.id_read_failed)
  caused by: open /home/ubuntu/.ssh/id_rsa: no such file or directory

Please check whether your SSH identity file /home/ubuntu/.ssh/id_rsa exists and have access permission.
Error: run `/home/ubuntu/.tiup/components/cluster/v1.4.4/tiup-cluster` (wd:/home/ubuntu/.tiup/data/SYjw9S6) failed: exit status 1
```

**Describe the feature you'd like:**

According to https://github.com/appleboy/easyssh-proxy:
> Optional key or Password without either we try to contact your agent SOCKET

We should check whether ~/.ssh/id_rsa exists before we use it as an argument to easyssh-proxy.

**Why the featue is needed:**

It would be nice to not have to copy the private SSH key to the TiUP management node in order to use TiUP. It might also increase security to not keep the SSH key on the TiUP node.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by 9547** [comment]
> It would be nice to not have to copy the private SSH key to the TiUP management node in order to use TiUP. It might also increase security to not keep the SSH key on the TiUP node.

Just be curious, if you are using `ssh-agent`, you need to add your private key with `ssh-add`, this step is also required to add the private key to your management machine, so I think the security risk is the same. If there is anything wrong with my understanding, would you please correct me.

**Comment by kolbe** [comment]
@9547 you can start ssh-agent on your local machine and then forward the agent connection over ssh, so that you never have to copy the key itself to the management node.

**Comment by 9547** [comment]
> @9547 you can start ssh-agent on your local machine and then forward the agent connection over ssh, so that you never have to copy the key itself to the management node.

Thanks for your advice, I'll have a try.

**Comment by 9547** [comment]
> @9547 you can start ssh-agent on your local machine and then forward the agent connection over ssh, so that you never have to copy the key itself to the management node.

I'm still curious, how does this work. AFAIK, `ssh-agent` runs in your local machine, and you can `ssh-add` your private key into `ssh-agent`, then you can ssh into the management node via ssh-agent's stored key. But, in the management node, you can't directly ssh into the ti{db,kv}...'s node without ssh private key. Is there anything I'm missing, please let me know?

**Comment by kolbe** [comment]
> I'm still curious, how does this work. AFAIK, `ssh-agent` runs in your local machine, and you can `ssh-add` your private key into `ssh-agent`, then you can ssh into the management node via `ssh-agent`'s stored key. But, in the management node, you can't directly ssh into the ti{db,kv}...'s node without the private key. Is there anything I'm missing, please let me know?

This is where the ssh client's ability to forward the ssh-agent socket is valuable. For example:

```
$ ssh ubuntu@"34.222.57.182"
ubuntu@34.222.57.182's password:
^C

$ ssh-add key
$ ssh ubuntu@"34.222.57.182"
Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1049-aws x86_64)
ubuntu@ip-10-0-0-107:~$ echo "$SSH_AUTH_SOCK"

ubuntu@ip-10-0-0-107:~$ logout
Connection to 34.222.57.182 closed.

$ ssh ubuntu@"34.222.57.182" -A
Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1049-aws x86_64)
ubuntu@ip-10-0-0-107:~$ echo $SSH_AUTH_SOCK
/tmp/ssh-Q5n45WKYuX/agent.3320
ubuntu@ip-10-0-0-107:~$ logout
Connection to 34.222.57.182 closed.
```

The ssh client acts as a proxy between the ssh-agent running on your local host and any ssh clients on the remote that want to use the agent.

```
     -A      Enables forwarding of the authentication agent connection.  This can also be specified on a per-host basis in a configuration file.

             Agent forwarding should be enabled with caution.  Users with the ability to bypass file permissions on the remote host (for the agent's UNIX-domain socket) can access the local agent through the forwarded
             connection.  An attacker cannot obtain key material from the agent, however they can perform operations on the keys that enable them to authenticate using the identities loaded into the agent.
```

**Comment by 9547** [comment]
@kolbe Thank you very much for your detailed answer.
