### ISSUE TITLE
tiup upgrade cluster failed

### ISSUE THREAD

**Issue by shldreams** [pingcap/tiup#1398]
When using tiup to upgrade, because pd did not select a leader in time, the upgrade exited, but the exit prompted the upgrade to be successful.
tidb 4.0.0 >> tidb5.0.1
Upgrading component tikv
failed increasing schedule limit: no endpoint available, the last err was: error requesting http://xx.xx.xx.xx:2379/pd/api/v1/config/replication-mode, response: no leader, code 503, ignore
Upgrading component prometheus
Upgrading component grafana
Upgrading component alertmanager
Upgraded cluster `tablestore` successfully

**Comment by jsvisa** [comment]
What's the TiUP version are you using? If it is convenient, could you please paste the topology.yaml file?

**Comment by 9547** [comment]
What's the TiUP version are you using? If it is convenient, could you please paste the topology.yaml file?
