### ISSUE TITLE
Why is the deployment path "/deploy_dir/data/service_name"?

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tiup#140]
If `data_dir` is empty, tiup seems to use "/deploy_dir/service_name" for deploy directory and "/deploy_dir/data/service_name" as data directory. What's the consideration of the choice? Why not choose "/deploy_dir/service_name" or "/deploy_dir/service_name/deploy" for deploy directory and "/deploy_dir/service_name/data" for data directory? The latter schema seems more consistent with historical choice and makes service log and data united.

**Comment by lonng** [comment]
@BusyJay I think you have some misunderstanding about the default data directory. If the data directory is empty, it will be set to `global.data_dir/service_name`. We can configure the global data directory individually because the data directory maybe mounts to a different devices.

**Comment by BusyJay** [comment]
I'm not object to customize the data directory. I'm just talking about the default behavior. When global.data_dir is not configured, it should be default to "/deploy_dir". But now tiup will leave it empty.

**Comment by lonng** [comment]
> I'm not object to customize the data directory. I'm just talking about the default behavior. When global.data_dir is not configured, it should be default to "/deploy_dir". But now tiup will leave it empty.

TiUP will not leave the `global.data_dir` empty if it is not configured, the default value of `global.data_dir` is `/home/${user}/data`

**Comment by BusyJay** [comment]
Then the output of deploy may need to be polished, as it says the output path is
```
pd          ip  2379/2380    /mnt/tidb/stability/pd-2379,data/pd-2379
tikv        ip 20160/20180  /mnt/tidb/stability/tikv-20160,data/tikv-20160
tikv        ip 20160/20180  /mnt/tidb/stability/tikv-20160,data/tikv-20160
tikv        ip  20160/20180  /mnt/tidb/stability/tikv-20160,data/tikv-20160
tidb        ip  4000/10080   /mnt/tidb/stability/tidb-4000
prometheus  ip 9090         /mnt/tidb/stability/prometheus-9090,data/prometheus-9090
grafana     ip 3000         /mnt/tidb/stability/grafana-3000
```
I suggest to make the default to `${deploy_dir}/data`.
