### ISSUE TITLE
Tiup deploy Failed in arm64 platform

### ISSUE THREAD

**Issue by jiayang-zheng** [pingcap/tiup#1413]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I try to use Tiup to deploy tidb v5.0.0 in arm64 platform. (running kylin v10 OS)

2. What did you expect to see?
command "tiup cluster deploy tidb-test v5.0.0 ./topology.yaml --user root -p " works successfully.

3. What did you see instead?
[root@test28 ~]# tiup cluster deploy tidb-test v5.0.0 ./topology.yaml --user root -p
Starting component `cluster`: /root/.tiup/components/cluster/v1.4.4/tiup-cluster deploy tidb-test v5.0.0 ./topology.yaml --user root -p
Please confirm your topology:
Cluster type:    tidb
Cluster name:    tidb-test
Cluster version: v5.0.0
Role          Host        Ports        OS/Arch        Directories
----          ----        -----        -------        -----------
pd            10.9.20.28  2379/2380    linux/aarch64  /tidb-deploy/pd-2379,/tidb-data/pd-2379
pd            10.9.20.29  2379/2380    linux/aarch64  /tidb-deploy/pd-2379,/tidb-data/pd-2379
pd            10.9.20.30  2379/2380    linux/aarch64  /tidb-deploy/pd-2379,/tidb-data/pd-2379
tikv          10.9.20.28  20160/20180  linux/aarch64  /tidb-deploy/tikv-20160,/data1/tikv-20160
tikv          10.9.20.29  20160/20180  linux/aarch64  /tidb-deploy/tikv-20160,/data1/tikv-20160
tikv          10.9.20.30  20160/20180  linux/aarch64  /tidb-deploy/tikv-20160,/data1/tikv-20160
tidb          10.9.20.28  4000/10080   linux/aarch64  /tidb-deploy/tidb-4000
tidb          10.9.20.29  4000/10080   linux/aarch64  /tidb-deploy/tidb-4000
tidb          10.9.20.30  4000/10080   linux/aarch64  /tidb-deploy/tidb-4000
prometheus    10.9.20.28  9090         linux/aarch64  /tidb-deploy/prometheus-9090,/tidb-data/prometheus-9090
grafana       10.9.20.28  3000         linux/aarch64  /tidb-deploy/grafana-3000
alertmanager  10.9.20.28  9093/9094    linux/aarch64  /tidb-deploy/alertmanager-9093,/tidb-data/alertmanager-9093
Attention:
    1. If the topology is not what you expected, check your yaml file.
    2. Please confirm there is no port/directory conflicts in same host.
Do you want to continue? [y/N]: (default=N) y
Input SSH password:
+ Generate SSH keys ... Done
+ Download TiDB components
  - Download pd:v5.0.0 (linux/arm64) ... Done
  - Download tikv:v5.0.0 (linux/arm64) ... Done
  - Download tidb:v5.0.0 (linux/arm64) ... Done
  - Download prometheus:v5.0.0 (linux/arm64) ... Done
  - Download grafana:v5.0.0 (linux/arm64) ... Done
  - Download alertmanager: (linux/arm64) ... Done
  - Download node_exporter: (linux/arm64) ... Done
  - Download blackbox_exporter: (linux/arm64) ... Done
+ Initialize target host environments
  - Prepare 10.9.20.28:22 ... Done
  - Prepare 10.9.20.29:22 ... Done
  - Prepare 10.9.20.30:22 ... Done
+ Copy files
  - Copy pd -> 10.9.20.28 ... Error
  - Copy pd -> 10.9.20.29 ... Error
  - Copy pd -> 10.9.20.30 ... Error
  - Copy tikv -> 10.9.20.28 ... Error
  - Copy tikv -> 10.9.20.29 ... Error
  - Copy tikv -> 10.9.20.30 ... Error
  - Copy tidb -> 10.9.20.28 ... Error
  - Copy tidb -> 10.9.20.29 ... Error
  - Copy tidb -> 10.9.20.30 ... Error
  - Copy prometheus -> 10.9.20.28 ... Error
  - Copy grafana -> 10.9.20.28 ... Error
  - Copy alertmanager -> 10.9.20.28 ... Error
  - Copy node_exporter -> 10.9.20.28 ... Error
  - Copy node_exporter -> 10.9.20.29 ... Error
  - Copy node_exporter -> 10.9.20.30 ... Error
  - Copy blackbox_exporter -> 10.9.20.28 ... Error
  - Copy blackbox_exporter -> 10.9.20.29 ... Error
  - Copy blackbox_exporter -> 10.9.20.30 ... Error

Error: executor.ssh.execute_failed: Failed to execute command over SSH for 'tidb@10.9.20.29:22' {ssh_stderr: We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:
    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.
sudo: no tty present and no askpass program specified
, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/usr/bin:/usr/sbin sudo -H bash -c "test -d /tidb-deploy || (mkdir -p /tidb-deploy && chown tidb:$(id -g -n tidb) /tidb-deploy)"}, cause: Process exited with status 1

Verbose debug logs has been written to /root/.tiup/logs/tiup-cluster-debug-2021-06-07-23-34-19.log.
Error: run `/root/.tiup/components/cluster/v1.4.4/tiup-cluster` (wd:/root/.tiup/data/SZfCSWK) failed: exit status 1

The Log says:
2021-06-07T22:49:48.052+0800    INFO    Execute command finished        {"code": 1, "error": "executor.ssh.execute_failed: Failed to execute command over SSH for 'tidb@10.9.20.30:22' {ssh_stderr: We trust you have received the usual lecture from the local System\nAdministrator. It usually boils down to these three things:
    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.
sudo: no tty present and no askpass program specified
, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/usr/bin:/usr/sbin sudo -H bash -c \"test -d /tidb-deploy || (mkdir -p /tidb-deploy && chown tidb:$(id -g -n tidb) /tidb-deploy)\"}, cause: Process exited with status 1", "errorVerbose": "executor.ssh.execute_failed: Failed to execute command over SSH for 'tidb@10.9.20.30:22' {ssh_stderr: We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:
    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.
sudo: no tty present and no askpass program specified
, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/usr/bin:/usr/sbin sudo -H bash -c \"test -d /tidb-deploy || (mkdir -p /tidb-deploy && chown tidb:$(id -g -n tidb) /tidb-deploy)\"}, cause: Process exited with status 1
 at github.com/pingcap/tiup/pkg/cluster/executor.(*EasySSHExecutor).Execute()
        github.com/pingcap/tiup/pkg/cluster/executor/ssh.go:154
 at github.com/pingcap/tiup/pkg/cluster/executor.(*CheckPointExecutor).Execute()
        github.com/pingcap/tiup/pkg/cluster/executor/checkpoint.go:85
 at github.com/pingcap/tiup/pkg/cluster/task.(*Mkdir).Execute()
        github.com/pingcap/tiup/pkg/cluster/task/mkdir.go:61          <--- Mkdir failed????
 at github.com/pingcap/tiup/pkg/cluster/task.(*Serial).Execute()
        github.com/pingcap/tiup/pkg/cluster/task/task.go:85
 at github.com/pingcap/tiup/pkg/cluster/task.(*StepDisplay).Execute()
        github.com/pingcap/tiup/pkg/cluster/task/step.go:87
 at github.com/pingcap/tiup/pkg/cluster/task.(*Parallel).Execute.func1()
        github.com/pingcap/tiup/pkg/cluster/task/task.go:134
 at runtime.goexit()
        runtime/asm_arm64.s:1130
github.com/pingcap/errors.AddStack
        github.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/errors.go:174
github.com/pingcap/errors.Trace
        github.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/juju_adaptor.go:15
github.com/pingcap/tiup/pkg/cluster/task.(*Mkdir).Execute
        github.com/pingcap/tiup/pkg/cluster/task/mkdir.go:63
github.com/pingcap/tiup/pkg/cluster/task.(*Serial).Execute
        github.com/pingcap/tiup/pkg/cluster/task/task.go:85
github.com/pingcap/tiup/pkg/cluster/task.(*StepDisplay).Execute
        github.com/pingcap/tiup/pkg/cluster/task/step.go:87
github.com/pingcap/tiup/pkg/cluster/task.(*Parallel).Execute.func1
        github.com/pingcap/tiup/pkg/cluster/task/task.go:134
runtime.goexit
        runtime/asm_arm64.s:1130"}

But I run ssh_command: export LANG=C; PATH=$PATH:/usr/bin:/usr/sbin sudo -H bash -c "test -d /tidb-deploy || (mkdir -p /tidb-deploy && chown tidb:$(id -g -n tidb) /tidb-deploy)" succeed in every node.
[root@test30 ~]# export LANG=C; PATH=$PATH:/usr/bin:/usr/sbin sudo -H bash -c "test -d /tidb-deploy || (mkdir -p /tidb-deploy && chown tidb:$(id -g -n tidb) /tidb-deploy)"
[root@test30 ~]# echo $?
0

4. What version of TiUP are you using (`tiup --version`)?
[root@test28 ~]# tiup --version
1.4.4 tiup
Go Version: go1.16.4
Git Ref: v1.4.4
GitHash: 0d0507355211fe16f95e1d00ed00c39f09c7565d

**Comment by AstroProfundis** [comment]
It seems you haven't configured `sudo` with `NOPASSWD` on the remote. Please configure the user you use (with `-u/--user` argument) to have `sudo` priviledge, or use `root` instead.

**Comment by AstroProfundis** [comment]
We add sudoers config in `/etc/sudoers.d/` during the environment init process, so that when we destroy the cluster, it can be easily and cleanly removed.

However, the Kylin v10 does not have `/etc/sudoers.d` included in the sudoers file. So the file we generated is not applied.

The solution is to add the following lines to the end of `/etc/sudoers` file: (Use `visudo` is recommended)
```
## Read drop-in files from /etc/sudoers.d
## (the '#' here does not indicate a comment)
#includedir /etc/sudoers.d
```

**Comment by jiayang-zheng** [comment]
Tiup deploy works. Thanks.
