### ISSUE TITLE
ead manifest from mirror(https://tiup-mirrors.pingcap.com) failed: manifest timestamp.json has expired at: 2021-05-26T11:18:30+08:00？

### ISSUE THREAD

**Issue by lddlww** [pingcap/tiup#1436]
rm -rf ./tiup/manifests/*，can't resolve

tiup mirror set https://tiup-mirrors.pingcap.com，can't resolve

how can i do to resolve the problem？

**Comment by AstroProfundis** [comment]
Could you try `curl https://tiup-mirrors.pingcap.com/timestamp.json` and show us the content? The `timestamp.json` you got seems to be a quite old and expired one.

**Comment by CedrusZhao** [comment]
I also meet this problem.
when I exec `curl https://tiup-mirrors.pingcap.com/timestamp.json`.the content is :
{"signatures":[{"keyid":"66d4ea1da00076c822a6e1b4df5eb1e529eb38f6edcedff323e62f2bfe3eaddd","sig":"bqY5dzifDgFprUxrwmS49u6qUlJaaIMFQtLPGaBpoN2gv99CWse6eDK33Rs2BtBTXssz0kIYT0a7UPkmNPITqR+E7UYqMHT+QWwAn5GKMnjN3vU6EgkFN5Cru/YNFUZ4xws8Fbcn5m35UEJ+ohBw0DkT4qimZqzEH//yTFfTM0CbOh20OLngHg2PMk2/fz1VI2GDIk9XMg1CEfjzQAywvTcBNFTLcxS+ZgA0J6aiEx/Uj7Exxl41Oddp9kGLABzntnW6qznHl4NHZJGhBAxKWuaYEEtPw4fvbMemOylPPdBTamAwnZ30aMYPyQ+LB2blfjsye5d69Z+E3rVtMKydVA=="}],"signed":{"_type":"timestamp","expires":"2021-07-18T16:34:38+08:00","meta":{"/snapshot.json":{"hashes":{"sha256":"142b3e8a28822e665398fa3b68758834426a7768d9e5eac908d13fdadedcce4d"},"length":2300}},"spec_version":"0.1.0","version":14520}}

**Comment by AstroProfundis** [comment]
That's wired, what version of TiUP (`tiup --version`) are you using? And are you able to run `tiup list`?

**Comment by lddlww** [comment]
@AstroProfundis 

```tiup list``` that throw same problem，also

and i used ```curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh``` command to reinstall ```tiup``` which resolve the problem

**Comment by lddlww** [comment]
old timestamp.json content is:
```
{"signatures":[{"keyid":"66d4ea1da00076c822a6e1b4df5eb1e529eb38f6edcedff323e62f2bfe3eaddd","sig":"h6uYziS+d1X0/QjlxZ/G0y+zKqaIMd7JrnhKVvFd/JpU455aNGq5vz5z4WW4X5RUEh8Y8mYx6bKJF4mqZbT3TdSBRxYMRIC0N40qtlnWxJ9yg5wI4OZHcRpfo2bAzF+pIdFI1QAoO+pD4gsY0U36mbcii+26Nm9vSIKcayOxybLlF5UyXACy1/aSYePz8hDxLP+FxmMf7r66vTjLSdWTLPmwUVleyquk46kMKhr9HwcSUWN8UmYRScS/ha3NMKJlFThg2dKMrxy59ysM4hLV8FnbbB7Gj5LeJ5ITwMTeZYpNLnM6LaETFgXKH+thZSJRmIWBt2jp0NnIKttxW/pjBw=="}],"signed":{"_type":"timestamp","expires":"2020-09-23T08:31:48+08:00","meta":{"/snapshot.json":{"hashes":{"sha256":"861312e96e7e0202b0652a84f5a460b99b9137fae9e08de82ee576c704ca379d"},"length":2239}},"spec_version":"0.1.0","version":2935}
```

**Comment by 9547** [comment]
@AstroProfundis There seems to be a problem with the manifest file on the mirror station, the `make test` failed of `invalid signature for file index.json: crypto/rsa: verification error`

```bash
ok  	github.com/pingcap/tiup/pkg/queue	0.006s	coverage: 0.0% of statements [no tests to run]
download x 10 B / 10 B 100.00% ? MiB/sWarn: invalid signature for file index.json: crypto/rsa: verification error
--- FAIL: TestPollutedManifest (0.03s)
    v1_repository_test.go:88: 
        	Error Trace:	v1_repository_test.go:88
        	Error:      	Expected nil, but got: &errors.errorString{s:"component tidb does not exist"}
        	Test:       	TestPollutedManifest
component foo version v2.0.2 is already installed
The component `bar` not found (may be deleted from repository); skipped
component foo version v2.0.1 is already installed
The component `bar` not found (may be deleted from repository); skipped
FAIL
```

Ref https://github.com/pingcap/tiup/pull/1469/checks?check_run_id=2973197477#step:4:224

**Comment by AstroProfundis** [comment]
This should be fixed already, if you see this error again, please feel free to reopen this issue or file a new one.
