### ISSUE TITLE
Display should show the exact store state after executing scale in --force

### ISSUE THREAD

**Issue by rleungx** [pingcap/tiup#1453]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Run `scale in --force` for a TiKV

2. What did you expect to see?

Show the real store state of that TiKV.

3. What did you see instead?

The TiKV disappears in the display list which may mislead the user to do some dangerous operation like clean up the store data. It will cause the unavailable of some regions.
Or we should warn users to prevent using --force AMAP.

4. What version of TiUP are you using (`tiup --version`)?

master

**Comment by breeswish** [comment]
Another problem seems to be "--force" can be very unsafe.

**Comment by AstroProfundis** [comment]
`--force` IS very unsafe, I think we could add a warning for it.
