### ISSUE TITLE
tiup cluster deploy conmmad fail to init env due to SSH login error

### ISSUE THREAD

**Issue by lv-fengxian** [pingcap/tiup#1467]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

type a deploy command : 
tiup cluster deploy tidb-test v5,0,0 ./topology.yaml  -user root

2. What did you expect to see?
deploy successfully

3. What did you see instead?
Error: Failed to initialize TiDB environment on remote host '10.3.72.86' (task.env_init.failed)
  caused by: Failed to create new system user 'root' on remote host
    caused by: Failed to execute command over SSH for 'ser@10.3.72.86:22'
      caused by: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

4. What version of TiUP are you using (`tiup --version`)?
tiup v1.5.2

the command is wrong , lack of one more '-' before '-user'.
but the error report means that tiup parse the word 'ser' as username

**Comment by AstroProfundis** [comment]
Seems you didn't specify correct credentials, using `--user root` without `-p` not `-i` will use the default SSH private key (`~/.ssh/id_rsa` normally) to login.

If you want to login with root password, add `-p` (without any value) argument and it will ask you to input the password. If you use a specific private key, use `-i <path/to/the/key/file>` to specify that.
