### ISSUE TITLE
TiUP produces a Fail when using Red-hat 8.4

### ISSUE THREAD

**Issue by wbkendall** [pingcap/tiup#1472]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Ran TiUP cluster check on a cluster install running RedHat 8.4.

2. What did you expect to see?
That the os-version check would pass as Red-hot 8.4 is higher that RedHat 7.

3. What did you see instead?
OS version check failed.
![image](https://user-images.githubusercontent.com/65571409/124508017-06e1d700-dd9d-11eb-9bea-f9f2a1084206.png)

4. What version of TiUP are you using (`tiup --version`)?
1.5.2

**Comment by AstroProfundis** [comment]
Thanks for the report, however, we do not support RHEL 8 at present.
