### ISSUE TITLE
v1.5.1 - `tiup tidb-lightning:v5.1.0 -check-requirements` parameter support

### ISSUE THREAD

**Issue by glkappe** [pingcap/tiup#1474]
Q1：
![image](https://user-images.githubusercontent.com/21033020/124619918-9fff1380-deab-11eb-820c-c9098430edc6.png)

Q2：
`Error: lightning pre check failed.please fix the check item and make check passed or set --check-requirement=false to avoid this check`
--check-requirement change to --check-requirements

in tiup, --xxx or -xxx ,how do we choose. 

workerload：
tiup tidb-lightning:v5.1.0 -config ./lightning.toml --check-requirements=false
![image](https://user-images.githubusercontent.com/21033020/124624245-4c8ec480-deaf-11eb-9dd1-1a2746453035.png)

**Comment by dveeden** [comment]
I think `tiup playground --monitor=false` and `tiup playground --monitor false` also don't behave the same, similar to `--check-requirements`.

**Comment by AstroProfundis** [comment]
The arguments are passed to the component as it is, you can see that in the first line ("Starting component ...") of output. So this should be an issue about how tidb-lightning handles arguments.
