### ISSUE TITLE
Consider using SHA256 to verify downloaded content

### ISSUE THREAD

**Issue by overvenus** [pingcap/tiup#148]
Currently, TiUP verifies downloaded content via SHA1 which is not safe, please consider using sha256.

https://github.com/pingcap-incubator/tiup/blob/eac13086c307582beb0d65588ec92f8be62bd486/Makefile#L96
https://github.com/pingcap-incubator/tiup/blob/1cfb722c052b39e9f2c25e434b22d0be89e0165a/tests/tiup_mirrors/generate.sh#L5

**Comment by lonng** [comment]
@overvenus Thanks for your advice. We will take account into this.

**Comment by nrc** [comment]
This is covered by the design in #193

**Comment by AstroProfundis** [comment]
It's already done in the new manifest implementation since v1.0.
