### ISSUE TITLE
tiup and lightning not working well together.

### ISSUE THREAD

**Issue by dveeden** [pingcap/tiup#1488]
1. What did you do?

Use `tiup tidb-lightning -backend=tidb -tidb-host=...`

2. What did you expect to see?

Use the specified host

3. What did you see instead?

Usage info

4. What version of BR and TiDB/TiKV/PD are you using?

```
Release Version: v5.1.0
Git Commit Hash: f2fcbfa5a9783e33ff44b696920d8bbe6a19eaa6
Git Branch: heads/refs/tags/v5.1.0
Go Version: go1.16.4
UTC Build Time: 2021-06-24 07:09:26
Race Enabled: false
```

`tiup -- tidb-lightning -backend=tidb -tidb-host=...` does work.

This might be causing issue if people follow https://docs.pingcap.com/tidbcloud/public-preview/migrate-data-into-tidb#step-2-import-data-to-your-tidb-cluster and use `tiup` instead of manually downloading and updating binaries.

This is a copy of https://github.com/pingcap/br/issues/1350 as I can't move issue between repos.

**Comment by AstroProfundis** [comment]
I don't quite get the problem, do you mean the `-tidb-host` argument is not correctly passed to lightning?

**Comment by dveeden** [comment]
yes indeed

**Comment by AstroProfundis** [comment]
I think it's an issue with `cobra` not handling solo dash style long arguments the same way as `flag`. We may need to find a way to deal that.

**Comment by AstroProfundis** [comment]
dupe w/ #862

**Comment by dveeden** [comment]
> dupe w/ #862

Yes indeed, let's close this one as duplicate.
