### ISSUE TITLE
The name of the file exported by node_exporter using metric tools does not have a cluster name

### ISSUE THREAD

**Issue by glkappe** [pingcap/tiup#1503]
flow：
1. use https://metricstool.pingcap.com/#backup-with-dev-tools
2. output node_exporter page
3. The file name does not contain the cluster name
4. use https://metricstool.pingcap.com/viz/index.html#!/
5. I still can’t see the cluster name, and I can’t distinguish it well when I export node_exporter of multiple clusters.

This design does not conform to the name of tidb as a large cluster

@lucklove @breeswish 
I understand this is a problem of cooperation between metric tools and node_exporter template

**Comment by AstroProfundis** [comment]
metric tool is not developed by us, please refer @kennytm

**Comment by AstroProfundis** [comment]
And we have another diagnostic data collector in demo, please contact me in private and I'll share you the document.

**Comment by glkappe** [comment]
ok，I will communicate with kennytm, please do not close this issue yet.
We need an issue to solve this problem, although this is not a tiup problem
