### ISSUE TITLE
Add command to delete Down instance 

### ISSUE THREAD

**Issue by mianhk** [pingcap/tiup#1505]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Why the featue is needed:**

Sometimes instance may down and can't up when host down or other reasons, we don't want to reuse host again, but instances always display when use `tiup cluster display` .

Now we can only delete then from file meta.yaml.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by AstroProfundis** [comment]
I believe `tiup cluster scale-in -N xxx --force` will do the trick.

**Comment by mianhk** [comment]
got it, thanks!
