### ISSUE TITLE
Unable to update configuration when the cluster is stopped

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tiup#1507]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I deploy a cluster that uses patched version TiKV that adds new configurations. So I:
- deploy the cluster with default packages;
- patch the cluster with my packages offline;
- edit-config to adjust new configurations
- reload the cluster to make the configuration takes affect.

2. What did you expect to see?
The cluster uses new configuration to start.

3. What did you see instead?
I can't reload the cluster as it's not started. I have to start it and then reload it. To make it worse,
the new configuration must be changed before the cluster is initialized, so I can't start it first.

Or, I should be able to deploy the cluster with the patched version in the very beginning.

4. What version of TiUP are you using (`tiup --version`)?
```
1.5.3 tiup
Go Version: go1.16.5
Git Ref: v1.5.3
GitHash: 222bd4d460eaa3fb6feec6ddeb8612fe0870ffd3
```

**Comment by AstroProfundis** [comment]
You may try `reload` with `--skip-restart`, and maybe also `--ignore-config-check`

**Comment by BusyJay** [comment]
> You may try reload with --skip-restart

It doesn't work.

```
{"level":"warn","ts":"2021-08-05T16:52:45.206+0800","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000178000/#initially=[127.0.0.1:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}

Error: context deadline exceed
```
