### ISSUE TITLE
unable to update nightly ctl

### ISSUE THREAD

**Issue by tabokie** [pingcap/tiup#1514]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
pingcap@ip-172-16-5-32:/data4/tabokie$ tiup update ctl --nightly
Updated successfully!
pingcap@ip-172-16-5-32:/data4/tabokie$ tiup ctl tikv --version
Found ctl newer version:

    The latest version:         v5.1.1
    Local installed version:    v5.0.0-rc
    Update current component:   tiup update ctl
    Update all components:      tiup update --all

Starting component `ctl`: /home/pingcap/.tiup/components/ctl/v5.0.0-rc/ctl tikv --version
TiKV Control (tikv-ctl)
Release Version:   5.0.0-rc
Edition:           Community
Git Commit Hash:   901f62d0ebe67db5d59402b31603b9aa903eb3e1
Git Commit Branch: heads/refs/tags/v5.0.0-rc
UTC Build Time:    2021-01-12 12:23:13
Rust Version:      rustc 1.49.0-nightly (b1496c6e6 2020-10-18)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb
Profile:           dist_release
```

2. What did you expect to see?

ctl can be updated to nightly.

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?
```
pingcap@ip-172-16-5-32:/data4/tabokie$ tiup --version
1.5.4 tiup
Go Version: go1.16.6
Git Ref: v1.5.4
GitHash: b629670276269cd1518eb28f362a5180135cc985
```

**Comment by AstroProfundis** [comment]
The latest nightly version of `ctl` is `"v5.0.0-nightly-20210809"` in the repository, which is even with `v5.0.0-rc` in semver compare, so the update does not actually download it. You can use `tiup list ctl` to get the actual version of latest nightly and install it manually.

cc @zhouqiang-cl I think the nightly versions should be bumped.

**Comment by tabokie** [comment]
I double checked and failed to reproduce with latest tiup. Seems a mistake on my end, closing this now.
