### ISSUE TITLE
tiup scale out cluster with TiCDC, cdc's data-dir does not work

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiup#1526]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

tiup cluster scale-out a cluster with CDC component

2. What did you expect to see?

data-dir config works correctly

3. What did you see instead?

data-dir does not work

4. What version of TiUP are you using (`tiup --version`)?

v1.5.4

**Comment by nexustar** [comment]
close as cannot recurrent
