### ISSUE TITLE
memory limit seems doesn't work

### ISSUE THREAD

**Issue by hicqu** [pingcap/tiup#1528]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Deploy a cluster, limit TiKV resource usage with
```
tikv_servers:
  - host: 172.16.4.78
    resource_control:
      memory_limit: 8G
      cpu_quota: 1000%
```

2. What did you expect to see?

The resource limit can work correctly.

3. What did you see instead?

The systemd unit file:
```
[Service]
MemoryLimit=8G
CPUQuota=1000%
LimitNOFILE=1000000
LimitSTACK=10485760
User=root
ExecStart=/data2/qupeng/clusters/one-tikv/deploy/tikv-60003/scripts/run_tikv.sh
```

However the tikv-server process's cgroup file:
cat /proc/<pid>/cgroup:
```
11:hugetlb:/
10:cpuset:/
9:perf_event:/
8:memory:/system.slice
7:freezer:/
6:net_prio,net_cls:/
5:blkio:/system.slice/tikv-60003.service
4:cpuacct,cpu:/system.slice/tikv-60003.service
3:pids:/system.slice/tikv-60003.service
2:devices:/system.slice/tikv-60003.service
1:name=systemd:/system.slice/tikv-60003.service
```
Seems the memory sub-system is mounted in a wrong position.

And tikv's log is
```
["cgroup quota: memory=ReadableSize(9223372036854771712), cpu=Some(10.0)
```
Seems only cpu limit works but memory limit doesn't.

I'm not sure whether it's a bug of tiup or my systemd has a problem.

4. What version of TiUP are you using (`tiup --version`)?
```
1.5.1 tiup
Go Version: go1.16.5
Git Ref: v1.5.1
GitHash: f00aeb0783f56c0766c39aa765d183a566f8f0d6
```

**Comment by AstroProfundis** [comment]
This seems to be a problem with `systemd`, The service file generated is as expected. Please feel free to reopen if there's any new information available.
