### ISSUE TITLE
The response code for TiUP bench is not correct

### ISSUE THREAD

**Issue by qqqdan** [pingcap/tiup#1533]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
The response code for TiUP bench is not correct，it should return non- 0 value.
![image](https://user-images.githubusercontent.com/19526717/130765728-92d06449-62a1-43f3-8513-4e6dd5a5fb8b.png)

2. What did you expect to see?

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?

**Comment by AstroProfundis** [comment]
I think #1557 also fixes this, please reopen or file a new issue if it does not.
