### ISSUE TITLE
Tiup mandatory scaling needs to add judgment rules

### ISSUE THREAD

**Issue by xiaoyangwang5** [pingcap/tiup#1541]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When a customer expands multiple nodes at the same time and shrinks multiple nodes at the same time, it is easy to use the forced shrinking command, resulting in data loss
**Describe the feature you'd like:**

tiup forced shrinkage --force parameter, need to judge the label situation, need to have prompt or prohibit function

**Why the featue is needed:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by AstroProfundis** [comment]
`--force` is designed to be **unsafe** and data loss is expected.

Could you describe more details about the **safe** process that we might be able to implement on normal scaling operations?

**Comment by qqqdan** [comment]
We already add more significant warning when --force argument is set for scale-in command in tiup-cluster (#1629, @AstroProfundis)
