### ISSUE TITLE
tiup deleted the ssh public key before `tiup cluster prune` task sucess.

### ISSUE THREAD

**Issue by imoyakin** [pingcap/tiup#1546]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
tiup cluster prune

2. What did you expect to see?

don't delete ssh-key until all mission success.

3. What did you see instead?

```
Stopping component blackbox_exporter
        Stopping instance  *.*.*.6
Failed to stop blackbox_exporter-9115.service: Unit blackbox_exporter-9115.service not loaded.

Failed to stop blackbox_exporter-9115.service: Unit blackbox_exporter-9115.service not loaded.

        Stop *.*.*.6 success
Destroying monitored  *.*.*.6
        Destroying instance  *.*.*.6
Destroy monitored on  *.*.*.6 success
Delete public key  *.*.*.6
Delete public key  *.*.*.6 success
Stopping component tikv
        Stopping instance  *.*.*.7

Error: failed to destroy tombstone: failed to stop tikv: failed to stop:  *.*.*.7 tikv-20160.service, please check the instance's log(/
```

try it again

afater
```
Error: failed to destroy tombstone: failed to stop tikv: failed to stop: *.*.*.6 tikv-20160.service, please check the instance's log(/tidb-deploy/tikv-20160/log) for more detail.: executor.ssh.execute_failed: Failed to execute command over SSH for 'tidb@*.*.*.6:22' {ssh_stderr: , ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/usr/bin:/usr/sbin /usr/bin/sudo -H bash -c "systemctl daemon-reload && systemctl stop tikv-20160.service"}, cause: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

```
4. What version of TiUP are you using (`tiup --version`)?
 1.5.5

**Comment by AstroProfundis** [comment]
The SSH key will be deleted when the last instance on host is destroyed. When you have unreachable host (e.g., broken hardware or already deleted VMs) in your cluster and you are deleting it, you could try the `--force` argument.

The `--force` argument ignores any errors occurs during the deleting process, so only use it when some of the hosts are already unreachable, but not when some operation like transferring data timeouts.

**Comment by AstroProfundis** [comment]
Oh, my fault, the `--force` argument is not available for `prune` subcommand, I'll fix that.
