### ISSUE TITLE
When deploying a TiDB cluster offline on one machine, it sometimes fails

### ISSUE THREAD

**Issue by jebter** [pingcap/tiup#1547]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Deploying a TiDB cluster offline on a machine sometimes fails

2. What did you expect to see?
![image](https://user-images.githubusercontent.com/4425235/131789357-c4e20e3f-c528-4343-9c6d-e8d0c0e336a0.png)

3. What did you see instead?
![image](https://user-images.githubusercontent.com/4425235/131789648-65cd453e-fded-48ee-8aac-43bf8a1875f1.png)

4. What version of TiUP are you using (`tiup --version`)?
1.5.6 tiup
Go Version: go1.16.7
Git Ref: v1.5.6
GitHash: 1d1478dbec0d06ef5e909d3323331914538d4cb0

**Comment by qqqdan** [comment]
@jebter would you please provide related log?

**Comment by qqqdan** [comment]
close as no feedback.
