### ISSUE TITLE
Unable to address `epoll-exclusive  Fail    epoll exclusive is not supported` failure against CentOS 7

### ISSUE THREAD

**Issue by yahonda** [pingcap/tiup#1550]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

- Installed tiup 1.5.6
```
% tiup --version
1.5.6 tiup
Go Version: go1.16.7
Git Ref: v1.5.6
GitHash: 1d1478dbec0d06ef5e909d3323331914538d4cb0
```
- Configure topology.yml to deploy TiDB 5.2 on CentOS 7 boxes created via "CentOS 7 (x86_64) - with Updates HVM" AMI at AWS. And the kernel version is `3.10.0-1160.41.1.el7.x86_64` after `yum -y update` executed.
```
Linux ip-172-31-41-208.us-east-2.compute.internal 3.10.0-1160.41.1.el7.x86_64 #1 SMP Tue Aug 31 14:52:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
-  Execute tiup cluster check command as follows
```
$ tiup cluster check ./topology.yaml --user centos -i "/home/centos/.ssh/keys/tiuptest.pem" | grep Fail
```
2. What did you expect to see?

All of check item should pass.

3. What did you see instead?

I was unable to address `epoll-exclusive  Fail    epoll exclusive is not supported` failures.

```
$ tiup cluster check ./topology.yaml --user centos -i "/home/centos/.ssh/keys/tiuptest.pem" | grep Fail
Starting component `cluster`: /home/centos/.tiup/components/cluster/v1.5.6/tiup-cluster check ./topology.yaml --user centos -i /home/centos/.ssh/keys/tiuptest.pem
172.31.43.48   epoll-exclusive  Fail    epoll exclusive is not supported
172.31.43.115  epoll-exclusive  Fail    epoll exclusive is not supported
172.31.37.212  epoll-exclusive  Fail    epoll exclusive is not supported
172.31.32.241  epoll-exclusive  Fail    epoll exclusive is not supported
172.31.18.210  epoll-exclusive  Fail    epoll exclusive is not supported
172.31.28.159  epoll-exclusive  Fail    epoll exclusive is not supported
172.31.34.224  epoll-exclusive  Fail    epoll exclusive is not supported
172.31.40.88   epoll-exclusive  Fail    epoll exclusive is not supported
172.31.44.182  epoll-exclusive  Fail    epoll exclusive is not supported
172.31.41.208  epoll-exclusive  Fail    epoll exclusive is not supported
172.31.21.61   epoll-exclusive  Fail    epoll exclusive is not supported
$
```

4. What version of TiUP are you using (`tiup --version`)?

```
$ tiup --version
1.5.6 tiup
Go Version: go1.16.7
Git Ref: v1.5.6
GitHash: 1d1478dbec0d06ef5e909d3323331914538d4cb0
```

**Comment by Defined2014** [comment]
I think it's caused by this [commit](https://github.com/pingcap/tidb-insight/commit/7f51e6264708eaeecea20c5840965099dcb7a1ee#diff-3a4b47f3a82c1fff6fe963bf57a89a541a38197bb644cdd8616b576c513b7d40L10). Disabled cgo will let checkEpollExclusive always return false. 💔

**Comment by AstroProfundis** [comment]
We have updated the `insight` package `v0.4.1` (which is used to collect information about hosts) and the epoll exclusive check should be working as expected now.

For some circumstances, you may need to delete the `insight-v0.4.1-linux-amd64.tar.gz` in the `~/.tiup/storage/clusters/packages/` on the console server and try `check` again.

**Comment by yahonda** [comment]
Thanks let me try and will open a new case if necessary.
