### ISSUE TITLE
tiup needs to determine whether the executable file exists

### ISSUE THREAD

**Issue by glkappe** [pingcap/tiup#1555]
When executing tiup update cluster, the compressed file was not decompressed into an executable file due to insufficient disk space, causing the execution of the tiup cluster command to fail
When this happens, it is recommended that tiup needs to check whether the executable file exists, not whether the compressed file exists, and when it is judged that the disk space is sufficient, it needs to be downloaded and decompressed again;
![image](https://user-images.githubusercontent.com/21033020/133387733-97b3e632-2a2f-418b-889c-f4f832e8c1e5.png)

**Comment by nexustar** [comment]
when you install cluster, is there any output?

**Comment by AstroProfundis** [comment]
It's not about checking executable file, it should be that `tiup` don't mark a component as installed if it has not finished the whole installation process.
