### ISSUE TITLE
Support set plugin-dir and plugin-load with tiup

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tiup#1564]
## Feature Request

**Is your feature request related to a problem? Please describe:**
TiDB has some plugin tools like (audit log, whitelist and so on), but tiup not support set plugin-dir and plugin-load to use them.

**Describe the feature you'd like:**
Add plugin-dir and plugin-load to TiDBSpec

**Why the featue is needed:**
Enable audit log by tiup

**Describe alternatives you've considered:**
None

**Teachability, Documentation, Adoption, Migration Strategy:**
Add plugin-dir and plugin-load to TiDBSpec

**Comment by AstroProfundis** [comment]
I'd prefer this to be added by component themselves in their config files, though.

**Comment by Defined2014** [comment]
> I'd prefer this to be added by component themselves in their config files, though.

TiDB config files has `Plugin`, maybe I can use it. Thx
