### ISSUE TITLE
TiUP does not supoort TiDB cluster with TLS

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tiup#1568]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

deploy TiDB cluster with TLS according to 
https://docs.pingcap.com/zh/tidb/v5.0/enable-tls-between-components#%E9%85%8D%E7%BD%AE%E5%BC%80%E5%90%AF%E5%8A%A0%E5%AF%86%E4%BC%A0%E8%BE%93

2. What did you expect to see?
start cluster successfully

3. What did you see instead?
start cluster failed

4. The Problem
The PD start script generated by TiUP is wrong. All the `http` should replace to `https`.

```
exec bin/pd-server \
    --name="pd" \
    --client-urls="http://0.0.0.0:2379" \
    --advertise-client-urls="http://127.0.0.1:2379" \
    --peer-urls="http://0.0.0.0:2380" \
    --advertise-peer-urls="http://127.0.0.1:2380" \
```

**Comment by AstroProfundis** [comment]
The TLS support is enabled with `global.enable_tls: true` in `topology.yaml` provided to the `deploy` command. Do not manually configure the component configs for that.
