### ISSUE TITLE
tiup playground with tiflash bin path generates wrong config causing indefinite table replicate

### ISSUE THREAD

**Issue by ichn-hu** [pingcap/tiup#1576]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

using

```
$ tiup playground nightly --kv 1 --pd 1 --db 1 --tiflash 1 --tiflash.binpath /home/ichn/Projects/pingcap/tics/build/dbms/src/Server/tiflash
```

to start a playground using my own tiflash binary

2. What did you expect to see?

`alter table t set tiflash relpica 1;` should succeed

3. What did you see instead?

`select * from information_schema.tiflash_repica;` always shows that the replication process is 0

however, if I create the cluster without specifying my own binary, the cluster will work, and if I kill the tiflash and start it again using my own tiflash binary with the tiup generated configuration, everything works.

so I compared the configuration file generated between specifying and not specifying tiflash binary, it shows difference that might caused the problem.

![image](https://user-images.githubusercontent.com/29735669/136885168-83527d02-9ef3-4001-aec5-fd0c70bc9f60.png)

4. What version of TiUP are you using (`tiup --version`)?

```
tiup --version
1.6.0 tiup
Go Version: go1.17.1
Git Ref: v1.6.0
GitHash: 0295c073463edc68696542f4ec9c9f5b4c07c5c1
```

**Comment by LittleFall** [comment]
and then this issue will be resolved.
![image](https://user-images.githubusercontent.com/30543181/136904725-b1b365ba-63d1-4873-bc94-55d19c81a6ed.png)
