### ISSUE TITLE
component ctl doesn't support platform darwin/arm64

### ISSUE THREAD

**Issue by maxshuang** [pingcap/tiup#1584]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

using tiup ctl cdc to manager cdc cluster on macos. 
Command is :  tiup ctl cdc capture list --pd=http://127.0.0.1:2379

2. What did you expect to see?
Can control cdc cluster normally, including create changefeed, get changefeed status, etc

3. What did you see instead?
Failed to start component `ctl`
Error: component ctl doesn't support platform darwin/arm64

4. What version of TiUP are you using (`tiup --version`)?
1.5.5 tiup
Go Version: go1.16.7
Git Ref: v1.5.5
GitHash: 01df6de49dbf23af1a3e9d6f71d383c407cdb810

**Comment by AstroProfundis** [comment]
@zhouqiang-cl PTAL

**Comment by lilyjazz** [comment]
'ctl' does not support M1 now. 
You can make a feature request.

**Comment by qqqdan** [comment]
close as this is duplicate with Tiup support ctl component on platform darwin/arm64 #1586
