### ISSUE TITLE
Support increaseScheduleLimit when using TiKV scale out 

### ISSUE THREAD

**Issue by mianhk** [pingcap/tiup#1589]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Related to PR: https://github.com/pingcap/tiup/pull/1161 

**Describe the feature you'd like:**

Add option to the command of scale-out to increaseScheduleLimit and store limit add-peer&remove-peer.

**Why the featue is needed:**

It may need too much time for TiKV clusters to balance store regions and leaders when scaling out TiKV with many regions. We need to increase leader-schedule-limit/region-schedule-limit/add-peer/remove-peer manually every time after scaling out TiKV.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by srstack** [comment]
What you mean is that you want to speed up the data balance time after expanding TiKV. The upgrade operation is a rolling upgrade, and you will wait for the data to be balanced, but the expansion operation will not wait for the data to be balanced. In summary, we are more inclined to actively modify the leader/region schedulelimit before expanding TiKV.
