### ISSUE TITLE
Support brew install TiUP

### ISSUE THREAD

**Issue by qqqdan** [pingcap/tiup#1599]
## Feature Request

**Is your feature request related to a problem? Please describe:**

User can install tiup using brew, and it provides an easier start.
brew install tiup

**Describe the feature you'd like:**

**Why the featue is needed:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by yahonda** [comment]
I also wanted this feature and found this public repository https://github.com/pingcap/homebrew-brew/ , which is little bit old but there is a formula for https://github.com/pingcap/homebrew-brew/blob/master/Formula/tiup.rb
