### ISSUE TITLE
TiUP cluster Scale-out action can be divided into 2 steps

### ISSUE THREAD

**Issue by qqqdan** [pingcap/tiup#1603]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Customer installed cluster in version 5.1.1, and they patched ticdc with a hotfix package from a local file.
In this case, when the customer wants to scale out the ticdc , the tiup mirror only has the package of 5.1.1 version. It needs much extra work to package the local patch file and upload to tiup mirror before customer can scale out the ticdc. 

**Describe the feature you'd like:**

We need provide a way to patch the new node during the scale out action.
Current scale out way : 
-- tiup cluster scale-out <cluster-name> scale-out.yaml

Proposed way:
-- 1: Scale-out new nodes with the package in the mirror use a special parameter , then the scale-out action will only deploy the new nodes but not start them.
-- 2:  use patch command to patch the new nodes with local file.
-- 3.   start the new nodes .

**Why the feature is needed:**

Provide a way for user to scale out the ticdc  and patch from local file. 

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by srstack** [comment]
TiUP cluster Scale-out action can be divided into 2
1. tiup cluster scale-out <cluster-name> scale-out.yaml  --no-start
2.  tiup cluster start <cluster-name>
