### ISSUE TITLE
make test failed with v1.3.2

### ISSUE THREAD

**Issue by zhaopei05** [pingcap/tiup#1604]
## Bug Report

1. What did you do?
make test

2. What did you expect to see?
All tests pass

3. What did you see instead?
--- FAIL: TestPollutedManifest (0.01s)
    v1_repository_test.go:88: 
        	Error Trace:	v1_repository_test.go:88
        	Error:      	Expected nil, but got: read manifest from mirror(mock) failed: manifest timestamp.json has expired at: 2021-05-26T11:18:30+08:00
        	Test:       	TestPollutedManifest
...

--- FAIL: TestPollutedManifest (0.01s)
    local_manifests_test.go:66: 
        	Error Trace:	local_manifests_test.go:66
        	Error:      	Should be true
        	Test:       	TestPollutedManifest

4. What version of TiUP are you using (`tiup --version`)?

v1.3.2

**Comment by AstroProfundis** [comment]
This was fixed in #1387, which is available in releases v1.4.0 and later. However, as released codes should be immutable, legacy releases may still failing.

You can try to `cherry-pick` that fix to older versions if it's a must for you to run tests on old codes.

**Comment by zhaopei05** [comment]
@AstroProfundis Thanks Allen for the response. I tried with v1.4.0 and still saw the same issues.

**Comment by AstroProfundis** [comment]
My fault, it seems the commit is only available in v1.4.4 https://github.com/pingcap/tiup/commits/release-1.4

And there is another related test error was fixed in #1473 and is available since v1.5.3.

**Comment by zhaopei05** [comment]
> My fault, it seems the commit is only available in v1.4.4 https://github.com/pingcap/tiup/commits/release-1.4
> 
> And there is another related test error was fixed in #1473 and is available since v1.5.3.

Thanks Allen for the confirmation. I manually ported the changes you mentioned in #1387 to v1.3.2 and it worked.
