### ISSUE TITLE
 Error: no check results found for 172.xxx.xxx.xxx

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tiup#1611]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
`tiup cluster deploy aws-test-v530 v5.3.0 /home/centos/aws-test/topo.yaml -i /home/centos/aws-test/id_rsa -u centos -y`

2. What did you expect to see?

The cluster would be deployed successfully.

3. What did you see instead?

`Error: no check results found for 172.xxx.xxx.xxx\n\nVerbose debug logs has been written to /home/centos/.tiup/logs/tiup-cluster-debug-2021-11-04-07-54-49.log.\n', 'tiup cluster deploy aws-test-v530 v5.3.0 /home/centos/aws-test/topo.yaml -i /home/centos/aws-test/id_rsa -u centos -y')`

4. What version of TiUP are you using (`tiup --version`)?
```
1.6.1 tiup
Go Version: go1.17.2
Git Ref: v1.6.1
GitHash: 1f6ca2b18e5c96c075efb4c08084d6dc8659050b
```

**Comment by AstroProfundis** [comment]
This should have been fixed in #1610
