### ISSUE TITLE
Tiup dm display miss one dm-worker info after upgrade dm (scale dm cluster while upgrade) 

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/tiup#1613]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

- install dm 2.0.7 with 2 worker, create source, start-task, start relay for each source
- use tiup to upgrade dm to 5.3.0, at the same time, scale-out the dm-cluster
- use dm display to check the dm-cluster

2. What did you expect to see?
all compontent display correct

3. What did you see instead?
one bouned dm-worker missed.

{"code": 1, "error": "failed to restart: 172.16.6.5 dm-worker-8100.service, please check the instance's log(/data1/dm-deploy/dm-worker-8100/log) for more detail.: executor.ssh.execute_failed: Failed to execute command over SSH for 'tidb@172.16.6.5:22' {ssh_stderr: Failed to restart dm-worker-8100.service: Unit not found.\n, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin /usr/bin/sudo -H bash -c \"systemctl daemon-reload && systemctl restart dm-worker-8100.service\"}, cause: Process exited with status 5", "errorVerbose": "executor.ssh.execute_failed: Failed to execute command over SSH for 'tidb@172.16.6.5:22' {ssh_stderr: Failed to restart dm-worker-8100.service: Unit not found.\n, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin /usr/bin/sudo -H bash -c \"systemctl daemon-reload && systemctl restart dm-worker-8100.service\"}, cause: Process exited with status 5\n at github.com/pingcap/tiup/pkg/cluster/executor.(*EasySSHExecutor).Execute()\n\tgithub.com/pingcap/tiup/pkg/cluster/executor/ssh.go:174\n at github.com/pingcap/tiup/pkg/cluster/executor.(*CheckPointExecutor).Execute()\n\tgithub.com/pingcap/tiup/pkg/cluster/executor/checkpoint.go:85\n at github.com/pingcap/tiup/pkg/cluster/module.(*SystemdModule).Execute()\n\tgithub.com/pingcap/tiup/pkg/cluster/module/systemd.go:98\n at github.com/pingcap/tiup/pkg/cluster/operation.systemctl()\n\tgithub.com/pingcap/tiup/pkg/cluster/operation/action.go:395\n at github.com/pingcap/tiup/pkg/cluster/operation.restartInstance()\n\tgithub.com/pingcap/tiup/pkg/cluster/operation/action.go:317\n at github.com/pingcap/tiup/pkg/cluster/operation.upgradeInstance()\n\tgithub.com/pingcap/tiup/pkg/cluster/operation/upgrade.go:150\n at github.com/pingcap/tiup/pkg/cluster/operation.Upgrade()\n\tgithub.com/pingcap/tiup/pkg/cluster/operation/upgrade.go:108\n at github.com/pingcap/tiup/pkg/cluster/manager.(*Manager).Upgrade.func1()\n\tgithub.com/pingcap/tiup/pkg/cluster/manager/upgrade.go:201\n at github.com/pingcap/tiup/pkg/cluster/task.(*Func).Execute()\n\tgithub.com/pingcap/tiup/pkg/cluster/task/func.go:34\n at github.com/pingcap/tiup/pkg/cluster/task.(*Serial).Execute()\n\tgithub.com/pingcap/tiup/pkg/cluster/task/task.go:85\n at github.com/pingcap/tiup/pkg/cluster/manager.(*Manager).Upgrade()\n\tgithub.com/pingcap/tiup/pkg/cluster/manager/upgrade.go:205\n at github.com/pingcap/tiup/components/dm/command.newUpgradeCmd.func1()\n\tgithub.com/pingcap/tiup/components/dm/command/upgrade.go:31\n at github.com/spf13/cobra.(*Command).execute()\n\tgithub.com/spf13/cobra@v1.2.1/command.go:856\n at github.com/spf13/cobra.(*Command).ExecuteC()\n\tgithub.com/spf13/cobra@v1.2.1/command.go:974\n at github.com/spf13/cobra.(*Command).Execute()\n\tgithub.com/spf13/cobra@v1.2.1/command.go:902\n at github.com/pingcap/tiup/components/dm/command.Execute()\n\tgithub.com/pingcap/tiup/components/dm/command/root.go:222\n at main.main()\n\tgithub.com/pingcap/tiup/components/dm/main.go:23\n at runtime.main()\n\truntime/proc.go:255\n at runtime.goexit()\n\truntime/asm_amd64.s:1581\nfailed to restart: 172.16.6.5 dm-worker-8100.service, please check the instance's log(/data1/dm-deploy/dm-worker-8100/log) for more detail.\ngithub.com/pingcap/tiup/pkg/cluster/operation.toFailedActionError\n\tgithub.com/pingcap/tiup/pkg/cluster/operation/action.go:607\ngithub.com/pingcap/tiup/pkg/cluster/operation.restartInstance\n\tgithub.com/pingcap/tiup/pkg/cluster/operation/action.go:318\ngithub.com/pingcap/tiup/pkg/cluster/operation.upgradeInstance\n\tgithub.com/pingcap/tiup/pkg/cluster/operation/upgrade.go:150\ngithub.com/pingcap/tiup/pkg/cluster/operation.Upgrade\n\tgithub.com/pingcap/tiup/pkg/cluster/operation/upgrade.go:108\ngithub.com/pingcap/tiup/pkg/cluster/manager.(*Manager).Upgrade.func1\n\tgithub.com/pingcap/tiup/pkg/cluster/manager/upgrade.go:201\ngithub.com/pingcap/tiup/pkg/cluster/task.(*Func).Execute\n\tgithub.com/pingcap/tiup/pkg/cluster/task/func.go:34\ngithub.com/pingcap/tiup/pkg/cluster/task.(*Serial).Execute\n\tgithub.com/pingcap/tiup/pkg/cluster/task/task.go:85\ngithub.com/pingcap/tiup/pkg/cluster/manager.(*Manager).Upgrade\n\tgithub.com/pingcap/tiup/pkg/cluster/manager/upgrade.go:205\ngithub.com/pingcap/tiup/components/dm/command.newUpgradeCmd.func1\n\tgithub.com/pingcap/tiup/components/dm/command/upgrade.go:31\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.2.1/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.2.1/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.2.1/command.go:902\ngithub.com/pingcap/tiup/components/dm/command.Execute\n\tgithub.com/pingcap/tiup/components/dm/command/root.go:222\nmain.main\n\tgithub.com/pingcap/tiup/components/dm/main.go:23\nruntime.main\n\truntime/proc.go:255\nruntime.goexit\n\truntime/asm_amd64.s:1581"}

-------------------------
2021-11-09T17:22:22.928+0800    INFO    Execute command finished        {"code": 1, "error": "dm cluster `dm-test` not exists", "errorVerbose": "dm cluster `dm-test` not exists\ngithub.com/pingcap/tiup/pkg/cluster/manager.(*Manager).meta\n\tgithub.com/pingcap/tiup/pkg/cluster/manager/manager.go:67\ngithub.com/pingcap/tiup/pkg/cluster/manager.(*Manager).GetClusterTopology\n\tgithub.com/pingcap/tiup/pkg/cluster/manager/display.go:231\ngithub.com/pingcap/tiup/pkg/cluster/manager.(*Manager).Display\n\tgithub.com/pingcap/tiup/pkg/cluster/manager/display.go:83\ngithub.com/pingcap/tiup/components/dm/command.newDisplayCmd.func1\n\tgithub.com/pingcap/tiup/components/dm/command/display.go:50\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.2.1/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.2.1/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.2.1/command.go:902\ngithub.com/pingcap/tiup/components/dm/command.Execute\n\tgithub.com/pingcap/tiup/components/dm/command/root.go:222\nmain.main\n\tgithub.com/pingcap/tiup/components/dm/main.go:23\nruntime.main\n\truntime/proc.go:255\nruntime.goexit\n\truntime/asm_amd64.s:1581"}

4. What version of TiUP are you using (`tiup --version`)?
# tiup --version
1.5.5 tiup
Go Version: go1.16.7
Git Ref: v1.5.5
GitHash: 01df6de49dbf23af1a3e9d6f71d383c407cdb810

**Comment by qqqdan** [comment]
It is a very special case.

**Comment by qqqdan** [comment]
Please feel free to reopen if the issue reproduce.
