### ISSUE TITLE
Support delete all TiKV or PD servers when there are other TiKV or PD servers not in local storage.

### ISSUE THREAD

**Issue by mianhk** [pingcap/tiup#1616]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

Support delete all TiKV or PD servers when there are other TiKV or PD servers not in local storage. 
**Why the featue is needed:**

When I migrate from TiDB cluster managed by TiUP to K8s, I need to scale in all components origin TiDB cluster, But meet error when scaling in the last TiKV or PD component. Ref: 
https://github.com/pingcap/tiup/blob/ab0e748bd7cd3058f23b621ced9249e3094a873f/pkg/cluster/operation/scale_in.go#L112-L119

Maybe we can check "all" by PD API  or add a parameter to controll it?  

Ref to document of TiDB Operator: https://docs.pingcap.com/tidb-in-kubernetes/stable/migrate-tidb-to-kubernetes#step-3-scale-in-the-tidb-nodes-of-the-source-cluster

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by AstroProfundis** [comment]
Maybe we could skip these checks if `--force` is set.
