### ISSUE TITLE
`tiup clean` need support clean up audit log

### ISSUE THREAD

**Issue by glkappe** [pingcap/tiup#1620]
## Feature Request

**Is your feature request related to a problem? Please describe:**

NO
**Describe the feature you'd like:**

`tiup clean --log` clean up normal logs,
add command `tiup clean --audit-log` clean up audit logs

**Why the featue is needed:**

The `tiup` tool needs to adapt to business functions
The audit log is an independent log system and needs to be retained for a long time. When the user uses the --log parameter to clean up the log to free up space, the `*.log` cleanup rule cannot meet the demand

**Describe alternatives you've considered:**

Add a set of independent log control methods to tidb-server to automatically clean up the audit log

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by glkappe** [comment]
add a point：
1. Add double confirmation, whether to allow cluster restart, whether to allow deletion of files, increase security

**Comment by srstack** [comment]
audit log example

```shell
[tidb@node4107 tidb-24000]$ cd log/
[tidb@node4107 log]$ ll
total 12444
-rw-r--r-- 1 tidb tidb 1024621 Oct 27 10:25 tidb-audit-2021-10-27T10-25-06.614.log
-rw-r--r-- 1 tidb tidb 1046034 Oct 27 10:25 tidb-audit-2021-10-27T10-25-29.310.log
-rw-r--r-- 1 tidb tidb 1046034 Oct 27 10:25 tidb-audit-2021-10-27T10-25-56.968.log
-rw-r--r-- 1 tidb tidb 1046034 Oct 27 10:26 tidb-audit-2021-10-27T10-26-19.533.log
-rw-r--r-- 1 tidb tidb 1046034 Oct 27 10:26 tidb-audit-2021-10-27T10-26-41.873.log
-rw-r--r-- 1 tidb tidb 1046034 Oct 27 10:27 tidb-audit-2021-10-27T10-27-04.445.log
-rw-r--r-- 1 tidb tidb 1046034 Oct 27 10:27 tidb-audit-2021-10-27T10-27-27.142.log
-rw-r--r-- 1 tidb tidb 1046034 Oct 27 10:27 tidb-audit-2021-10-27T10-27-49.878.log
-rw-r--r-- 1 tidb tidb 1046052 Oct 27 10:28 tidb-audit-2021-10-27T10-28-12.360.log
-rw-r--r-- 1 tidb tidb 1048487 Nov 25 04:03 tidb-audit-2021-11-25T04-03-35.169.log
-rw-r--r-- 1 tidb tidb  547168 Nov 30 08:46 tidb-audit.log
-rw-r--r-- 1 tidb tidb  586201 Nov 30 06:07 tidb.log
-rw-r--r-- 1 tidb tidb  539300 Nov 30 06:07 tidb_slow_query.log
-rw-r--r-- 1 tidb tidb  593504 Nov 10 09:20 tidb_stderr.log
```

**Comment by srstack** [comment]
tiup cluster clean <cluster-name> --audit-log
