### ISSUE TITLE
Tiup cluster check should support check before expanding the instance

### ISSUE THREAD

**Issue by jt20190617** [pingcap/tiup#1621]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Expansion of a PD instance can be successful if the PD instance already exists in another cluster and is running. As a result, the two TIDB clusters have the same PD instance.

**Describe the feature you'd like:**
When running tiup cluster scale-out command, you can check the ports and directories of the target machine, or add the -check option to the tiup cluster scale-out command.

**Why the featue is needed:**
O&m personnel may write wrong instance objects when performing capacity expansion operations. A check action can avoid this problem

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by srstack** [comment]
use this command to check before expanding the instance
```shell
tiup cluster check  scale-out.yml  cluster-name --cluster 
```
