### ISSUE TITLE
`tiup cluster push` shouldn't  rename file when i end with the table of contents

### ISSUE THREAD

**Issue by glkappe** [pingcap/tiup#1626]
![image](https://user-images.githubusercontent.com/21033020/142147941-23dd497f-f8d8-460c-9215-f18f31120261.png)

**Comment by AstroProfundis** [comment]
That's because the `qh_new` directory is not exist on the remote server, so the last part of the path (`qh_new`) is treated as filename.

You may use `tiup cluster exec` to create that directory before `push`.
