### ISSUE TITLE
playground `db.host`,`db.port`,`pd.host` changed to `db.Host`, `db.Port` and `pd.Host`

### ISSUE THREAD

**Issue by zhangyangyu** [pingcap/tiup#1632]
In commit 6ee8abc38, the three playground opts were change to capitalized. Not sure this is intentional but seems not consistent with other opts and docs.

**Comment by AstroProfundis** [comment]
The code change was intentional otherwise telemetry message of playground could not be properly marshaled. However, I didn't expect the user facing arguments to change, we'll try to sort that out.
