### ISSUE TITLE
use Tiup deploy alertmanager component，But listening on a specific IP

### ISSUE THREAD

**Issue by Jayjlchen** [pingcap/tiup#1633]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
use Tiup deploy alertmanager component

例子:
#以此配置扩容一个alertmanager组件
  alertmanager_servers:
  - host: 192.168.159.134
    ssh_port: 22
    web_port: 9093
    cluster_port: 9094
    deploy_dir: /tidb-deploy/alertmanager-9093
    data_dir: /tidb-data/alertmanager-9093
    log_dir: /tidb-deploy/alertmanager-9093/log
    arch: amd64
    os: linux

2. What did you expect to see?
Listening at 0.0.0.0

#查看节点生成的run_alertmanager.sh脚本
#希望生成的脚本的IP都为0.0.0.0

exec > >(tee -i -a "/tidb-deploy/alertmanager-9093/log/alertmanager.log")
exec 2>&1
exec bin/alertmanager/alertmanager \
    --config.file="conf/alertmanager.yml" \
    --storage.path="/tidb-data/alertmanager-9093" \
    --data.retention=120h \
    --log.level="info" \
    --web.listen-address="192.168.159.134:9093" \
    --cluster.peer="192.168.159.134:9094" \
    --cluster.listen-address="192.168.159.134:9094

3. What did you see instead?
Listen at a specific IP

[root@pd-3 scripts]# netstat -tunlp |grep 9093
tcp        0      0 192.168.159.134:9093    0.0.0.0:*               LISTEN      11488/bin/alertmana

4. What version of TiUP are you using (`tiup --version`)?
1.5.4 tiup
Go Version: go1.16.6
Git Ref: v1.5.4
GitHash: b629670276269cd1518eb28f362a5180135cc985

**Comment by srstack** [comment]
add new field listen_host to Alertmanager
