### ISSUE TITLE
The tiup cluster check command is added to print the results of the check for  cpufreq module and  I/O scheduler

### ISSUE THREAD

**Issue by Jayjlchen** [pingcap/tiup#1636]
## Feature Request

**Is your feature request related to a problem? Please describe:**
When using tiup cluster check command, there are two important check items that are not printed

**Describe the feature you'd like:**
I hope that after the tiup cluster check command is executed, the  cpufreq module and the I/O scheduler configuration information  will be printed out, whether it is correct or not.

**Why the featue is needed:**
Do not print this information, it is easy to miss to check

**Describe alternatives you've considered:**
Pass the parameter check and print pass, if it fails, print the current value and mark it as warn

**Teachability, Documentation, Adoption, Migration Strategy:**
none

**Comment by srstack** [comment]
Now tiup cluster check does not check the disk io scheduler, you can submit a new issue to support  it.

**Comment by srstack** [comment]
Currently tiup cluster check does not support checking io scheduler settings, please submit a new issue to support him. 
The problem of cpufreq check result output will be completed in this issue.
