### ISSUE TITLE
Can't monitor DM-Worker status 

### ISSUE THREAD

**Issue by mizuki-masuda** [pingcap/tiup#1653]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Cannot monitor DM-worker from Node_exporter.

----- topology.yml -----
global:
  user: "tidb"      ##DM Master,Workerノードに作成されるOSユーザ
  ssh_port: 22    ##SSHで利用するポート
  deploy_dir: "/dm/deploy"   ##deployフォルダが作成されるパス
  data_dir: "/dm/data"           ##dataフォルダが作成されるパス

monitored:            # 各ノードのCPU、メモリ、Disk容量などを監視する場合に必要な設定
  node_exporter_port: 19100
  blackbox_exporter_port: 19115
  deploy_dir: /home/tidb/dm/deploy/monitor-19100
  data_dir: /dm/data/monitor-19100
  log_dir: /dm/deploy/monitor-19100/log

master_servers:
  - host: 172.36.20.137  ##DM Masterノード1のプライベート IPv4 アドレスを記載

worker_servers:
  - host: 172.36.20.97   ##DM Workerノードのプライベート IPv4 アドレスを記載

monitoring_servers:
  - host: 172.36.20.137  ##DM Masterノードのプライベート IPv4 アドレスを記載

grafana_servers:
  - host: 172.36.20.137  ##DM Masterノードのプライベート IPv4 アドレスを記載

alertmanager_servers:
  - host: 172.36.20.137  ##DM Masterノードのプライベート IPv4 アドレスを記載    
-----------------------------

----- prometheus.yml -----
    - targets:
      - '172.36.20.137:19100'
      labels:
        group: 'node_exporter'
-----------------------------

2. What did you expect to see?

Can monitor DM-worker from Node_exporter.

3. What did you see instead?

No, can't see it.

4. What version of TiUP are you using (`tiup --version`)?

1.5.6 tiup
Go Version: go1.16.7
Git Ref: v1.5.6
GitHash: 1d1478dbec0d06ef5e909d3323331914538d4cb0

**Comment by AstroProfundis** [comment]
In https://github.com/pingcap/tiup/blob/5e972221f0f66bece272995eb36d57b26fab5020/pkg/cluster/spec/monitoring.go#L267  the dm worker and master nodes are not added to the uniqueHost set, where node_exporter configs are generated from. (and there is a typo in the function name as well...)
