### ISSUE TITLE
SSH issue when deploy TiDB cluster

### ISSUE THREAD

**Issue by 206227087** [pingcap/tiup#1658]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I'm just trying to deploy a cluster demo for TiDB by TiUP on a single server,

`tiup cluster deploy tidb-dev v5.3.0 /home/topo.yaml --user chaos -p`

It throws ssh issue as below:

`Error: executor.ssh.execute_failed: Failed to execute command over SSH for 'tidb@192.168.0.10:22' {ssh_stderr: , ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin /usr/bin/sudo -H bash -c "test -d /tidb-deploy || (mkdir -p /tidb-deploy && chown tidb:$(id -g -n tidb) /tidb-deploy)"}, cause: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`

But when I run the command `ssh tidb@myhost` in terminal, it run good and can also run `su root`.

And I have already try to use `tiup cluster deploy tidb-dev v5.3.0 /home/topo.yaml --user chaos -i ~/.ssh/id_rsa`, it doesn't works too.

So I want to ask, whether I missed some important config about ssh or not? It's hard to find on your documents website.

`https://docs.pingcap.com/zh/tidb/stable/quick-start-with-tidb#Linux`

And another question, if the high OpenSSH or Linux system version will be influence the result? 
I‘m using Fedora 35 and Open SSH 8.7.

Here is the log file:
[tiup-cluster-debug-2021-12-08-16-21-16.log](https://github.com/pingcap/tiup/files/7674651/tiup-cluster-debug-2021-12-08-16-21-16.log)

By the way, this question blocked me two days, and I'm tried to search on internet, but they all doesn't work for me.
Could you please help me to resolve it or you guys can give me some specific document links about this issue.
I will be very appreciate.

2. What did you expect to see?

TiDB cluster deploy succeed.

3. What did you see instead?

`ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`

4. What version of TiUP are you using (`tiup --version`)?

1.8.0 tiup
Go Version: go1.17.3

**Comment by onlyacat** [comment]
I guess it might be helpful to run the command with a specific ssh type. Try this one:
```
tiup cluster deploy ... ... --ssh system
```

**Comment by AstroProfundis** [comment]
This is a dupe with #1609 and we have to wait the Go team to fix that. Before the new default cypher in OpenSSH 8.7+ are supported the workaround would be using `tiup-cluster` with `--ssh=system` argument.

**Comment by 206227087** [comment]
> This is a dupe with #1609 and we have to wait the Go team to fix that. Before the new default cypher in OpenSSH 8.7+ are supported the workaround would be using `tiup-cluster` with `--ssh=system` argument.

Yes, it works. Thanks.
