### ISSUE TITLE
Support declarative yaml for TiDB Cluster `scale-out` and `scale-in`

### ISSUE THREAD

**Issue by yahonda** [pingcap/tiup#1662]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When users want to scale out TiDB cluster, they need to create another yaml file which adds servers to be added. 
Also for `scale-in` operation, we need to provide node name to be removed as command line arguments. 
Both of them are not declarative.

**Describe the feature you'd like:**
I want tiup supports declarative yaml for TiDB Cluster `scale-out` and `scale-in`.
Instead of creating another yaml file for `scale-out`, just updating the existing yaml file for the TiDB cluster.

This feature allows users to manage only one YAML file per TiDB cluster. 
If the customer manages the yaml file under source control like git, they can see follow the differences between commits.

Also for `scale-in` operation, we need to provide node name to be removed as command line arguments.
`tiup cluster scale-in tidb-test --node <IP address for TiDB server>:20160`
Command line options are unlikely managed under source control, many of users are unable to track TiDB scale-in configuration changes.
If tiup supports declarative scale in, they can just delete the entries from the YAML file. It would be much easier to track the configuration changes.

**Why the featue is needed:**

Compared with Kubernetes(K8s) configuration whose YAML files are defined declaratively, tiup scale-in and scale-out operations are imperative.

**Describe alternatives you've considered:**

I attempt to see if `tiup cluster edit-config <cluster-name>` already supports declarative operations for scale-out, actually it does not.

1. Create a TiDB 5.3.0 cluster named `tidb-test` using tiup 1.8.0

2. Execute `tiup cluster edit-config tidb-test` and add these TiKV servers to scale out TiKV servers from 3 to 5.

```
- host: 172.31.3.34
  ssh_port: 22
  port: 20160
  status_port: 20180
  deploy_dir: /tidb-deploy/tikv-20160
  data_dir: /tidb-data/tikv-20160
  log_dir: /tidb-deploy/tikv-20160/log
  arch: amd64
  os: linux
- host: 172.31.11.7
  ssh_port: 22
  port: 20160
  status_port: 20180
  deploy_dir: /tidb-deploy/tikv-20160
  data_dir: /tidb-data/tikv-20160
  log_dir: /tidb-deploy/tikv-20160/log
  arch: amd64
  os: linux
```

3. Saved the file then it shows this `New topology could not be saved: immutable field changed: added` error.

```
Starting component `cluster`: /home/centos/.tiup/components/cluster/v1.8.0/tiup-cluster edit-config tidb-test
New topology could not be saved: immutable field changed: added TiKVServers.3.Host with value '172.31.3.34', added TiKVServers.3.ssh_port with value '22', added TiKVServers.3.Port with value '20160', added TiKVServers.3.StatusPort with value '20180', added TiKVServers.3.DeployDir with value '/tidb-deploy/tikv-20160', added TiKVServers.3.DataDir with value '/tidb-data/tikv-20160', added TiKVServers.3.LogDir with value '/tidb-deploy/tikv-20160/log', added TiKVServers.3.Arch with value 'amd64', added TiKVServers.3.OS with value 'linux', added TiKVServers.4.Host with value '172.31.11.7', added TiKVServers.4.ssh_port with value '22', added TiKVServers.4.Port with value '20160', added TiKVServers.4.StatusPort with value '20180', added TiKVServers.4.DeployDir with value '/tidb-deploy/tikv-20160', added TiKVServers.4.DataDir with value '/tidb-data/tikv-20160', added TiKVServers.4.LogDir with value '/tidb-deploy/tikv-20160/log', added TiKVServers.4.Arch with value 'amd64', added TiKVServers.4.OS with value 'linux'
Do you want to continue editing? [Y/n]: (default=Y)
```

**Teachability, Documentation, Adoption, Migration Strategy:**

I have no this information yet.

**Comment by AstroProfundis** [comment]
It was by design not to use a declarative yaml to manage the cluster, the files passed to commands are actually "rich-text arguments" instead of a "configuration" and they all are only used for one time. Users can safely delete all the files they used to in command arguments after the operation finished.

The main problem of declarative configurations are:
1. we'll need to maintain a state machine and generate workflow for configuration changes, and that's much more complex as what we have implemented now
2. they user may need to keep their configuration somewhere safe, and remember to make it synced with the actual state

**Comment by yahonda** [comment]
Thanks for the detailed explanation. I still want tiup supports declarative yaml but I do not have other use cases to request it. 
Let me close this issue. if someone else has some use cases to request declarative yaml, feel free to reopen it.
