### ISSUE TITLE
tikv oom with numa setting problems on memory

### ISSUE THREAD

**Issue by tier-cap** [pingcap/tiup#1670]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
a. Tiup deploy tikv with numa_node setting.
b. Test with sysbench prepare.

2. What did you expect to see?
a. cpu bind and mem bind should be set separately.
b. we shoud let the mem preferred be the default allocate strategy.

3. What did you see instead?
a. After setting numa_node, during the stress test, the frequency of tikv oom increased significantly.
b. The reason for the analysis may be that after the core is tied, there are some internal memory parameter settings in tikv. The default settings are set according to the percentage of the total system memory. After the core is tied to the memory, the actual usable size of the memory is reduced proportionally. The default parameter of tikv is still full memory.

4. What version of TiUP are you using (`tiup --version`)?
nightly

**Comment by srstack** [comment]
PD changed the return struct of store api.  PD will fix this.
