### ISSUE TITLE
tiup cluster display has two pd leaders(two L)

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiup#1675]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

- tiup cluster deploy xxx v5.4.0-nightly-20211210 xxx.yaml ->deploy one pd
- tiup cluster start xxx
- tiup cluster scale-out xxx ->scale out to 3 pd

2. What did you expect to see?

3. What did you see instead?
![aHczZVdbv1](https://user-images.githubusercontent.com/78345569/146150447-b45a1f7c-32d7-4287-92d4-052cba748616.png)
/pd-ctl memeber list only display one pd leader(172.16.6.5)

4. What version of TiUP are you using (`tiup --version`)?
```$ tiup --version
1.7.0 tiup
Go Version: go1.17.3
Git Ref: v1.7.0
GitHash: ce8eb0a645cc3ead96a44d67b1ecd5034d112cf0
```$tiup cluster --version
Starting component `cluster`: /root/.tiup/components/cluster/v1.8.0/tiup-cluster --version
tiup version 1.8.0 tiup
Go Version: go1.17.3
Git Ref: v1.8.0
GitHash: ff08d402711bca996c2b7d27f45ff4623ed794de

**Comment by srstack** [comment]
/pd-ctl memeber list only display one pd leader(172.16.6.5)

**Comment by srstack** [comment]
It may be that the PD leader switch occurred during the process of tiup obtaining the PD status. 
It may be necessary to add a detection mechanism to tiup. If two leaders are found, the PD status will be reacquired

**Comment by srstack** [comment]
The PD cluster is split, and it is suspected that there is an abnormality in the scale-out operation.

**Comment by srstack** [comment]
Waiting to reproduce in the customer environment

**Comment by qqqdan** [comment]
close as no feedback for a month.
