### ISSUE TITLE
tiup dumpling --filter usage

### ISSUE THREAD

**Issue by glkappe** [pingcap/tiup#1681]
tiup dumpling:v5.0.4 --host 172.16.4.20 --port 24000 --user root  --filter='cdctest.*' --threads 4 --rows 50000 --filesize 512MiB --tidb-mem-quota-query 1073741824  -o ./cmd/

Why do `--filter` and parameter value need to add `=`

error log：
![image](https://user-images.githubusercontent.com/21033020/146478103-e86d7ba4-7871-4730-b912-a6357379bf69.png)

v1.8.0

**Comment by nexustar** [comment]
error is the same when run it without tiup
