### ISSUE TITLE
tiup cluster scale-in two TiKV, when the two TiKV become Tomestone status, tiup cluster restart, the two tikv come back to cluster again

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiup#1685]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

- scale-in two TiKV, we can see the regions in them are decreasing.
- When the two TiKV become Tomestone status, restart cluster: tiup cluster restart <cluster name>
- Check cluster status and TiKV granfa.

2. What did you expect to see?

- The two scaled-in TiKV will not add to TiDB cluster.

3. What did you see instead?

- The two scaled-in TiKV status become UP again.
- The two scaled-in TiKV acquired region again. From pd log, the two stores are still there.
![9nvDFLRpca](https://user-images.githubusercontent.com/78345569/146723818-54779a14-37d9-4d89-8d64-5e9c34a992f3.png)

4. What version of TiUP are you using (`tiup --version`)?

**Comment by rleungx** [comment]
We may also need to improve the `prune`'s log. See https://github.com/pingcap/tiup/issues/1148.

**Comment by srstack** [comment]
PD changed the return struct of store api.  PD will fix this.

**Comment by rleungx** [comment]
> * status

Would you like to comment more details on this issue so that we can know why changing the API of PD will cause this problem?

**Comment by rleungx** [comment]
> PD changed the return struct of store api. PD will fix this.
 
Would you like to comment more details on this issue so that we can know why changing the API of PD will cause this problem?

**Comment by srstack** [comment]
> > PD changed the return struct of store api. PD will fix this.
> 
> Would you like to comment more details on this issue so that we can know why changing the API of PD will cause this problem?

https://github.com/tikv/pd/pull/4485 

Because TiUP cannot judge the task status of scaled-in TiKV based on the PD return value
