### ISSUE TITLE
tiup should deploy ng-monitoring by default when TiDB cluster version >= v5.4.0

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tiup#1689]
## Feature Request

tiup should deploy [ng-monitoring](https://github.com/pingcap/ng-monitoring) by default when TiDB cluster version >= v5.4.0

**Why the featue is needed:**

TiDB TopSQL feature will be enable by default when TiDB version >= v5.4.0. And TiDB TopSQL feature depends on [ng-monitoring](https://github.com/pingcap/ng-monitoring).

**Describe alternatives you've considered:**

N/A

**Teachability, Documentation, Adoption, Migration Strategy:**

N/A

**Comment by qqqdan** [comment]
Duplicate with https://github.com/pingcap/tiup/issues/1690 ， close this issue  and will follow up in 1690
