### ISSUE TITLE
run tiup playgroud error in mac m1

### ISSUE THREAD

**Issue by flowly** [pingcap/tiup#1707]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

run tiup playgroud error with mac M1

2. What did you expect to see?
start cluster success

3. What did you see instead?

Using the version v5.3.0 for version constraint "".

If you'd like to use a TiDB version other than v5.3.0, cancel and retry with the following arguments:
	Specify version manually:   tiup playground <version>
	Specify version range:      tiup playground ^5
	The nightly version:        tiup playground nightly

Playground Bootstrapping...
Start pd instance
The component `pd` version v5.3.0 is not installed; downloading from repository.
download https://tiup-mirrors.pingcap.com/pd-v5.3.0-darwin-amd64.tar.gz 41.66 MiB / 41.66 MiB 100.00% 9.99 MiB/s
Start tikv instance
The component `tikv` version v5.3.0 is not installed; downloading from repository.
download https://tiup-mirrors.pingcap.com/tikv-v5.3.0-darwin-amd64.tar.gz 19.86 MiB / 19.86 MiB 100.00% 10.80 MiB/s
Start tidb instance
The component `tidb` version v5.3.0 is not installed; downloading from repository.
download https://tiup-mirrors.pingcap.com/tidb-v5.3.0-darwin-amd64.tar.gz 19.21 MiB / 46.08 MiB 41.69% 10.78 MiB/s                                                                                        tikv quit: signal: illegal instruction
download https://tiup-mirrors.pingcap.com/tidb-v5.3.0-darwin-amd64.tar.gz 46.08 MiB / 46.08 MiB 100.00% 8.98 MiB/s
Waiting for tidb instances ready
127.0.0.1:4000 ... Error
The component `prometheus` version v5.3.0 is not installed; downloading from repository.
download https://tiup-mirrors.pingcap.com/prometheus-v5.3.0-darwin-amd64.tar.gz 19.16 MiB / 89.44 MiB 21.42% 3.79 MiB/s                                                                                   download https://tiup-mirrors.pingcap.com/prometheus-v5.3.0-darwin-amd64.tar.gz 89.44 MiB / 89.44 MiB 100.00% 3.60 MiB/s
download https://tiup-mirrors.pingcap.com/grafana-v5.3.0-darwin-amd64.tar.gz 47.11 MiB / 47.11 MiB 100.00% 2.67 MiB/s
To view the dashboard: http://127.0.0.1:2379/dashboard
PD client endpoints: [127.0.0.1:2379]
To view the Prometheus: http://127.0.0.1:9090

4. What version of TiUP are you using (`tiup --version`)?

1.8.1 tiup
Go Version: go1.17.5
Git Ref: v1.8.1
GitHash: 559b99d0acb7d07acddbb8cda0304b0f27c6ec1e

**Comment by srstack** [comment]
Can you provide more log information?

**Comment by flowly** [comment]
Playground Bootstrapping...
Start pd instance
Start tikv instance
Start tidb instance
Waiting for tidb instances ready
127.0.0.1:4000 ... Done
tikv quit: signal: illegal instruction
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x18e6c34]

goroutine 84 [running]:
main.(*monitor).wait(0x0)
	github.com/pingcap/tiup/components/playground/monitor.go:78 +0x14
main.(*Playground).bootMonitor.func1()
	github.com/pingcap/tiup/components/playground/playground.go:1034 +0x2d
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92

**Comment by nexustar** [comment]
fixed by #1712

**Comment by flowly** [comment]
Hello, i use the latest version and it failed again

Using the version v5.3.0 for version constraint "".

If you'd like to use a TiDB version other than v5.3.0, cancel and retry with the following arguments:
	Specify version manually:   tiup playground <version>
	Specify version range:      tiup playground ^5
	The nightly version:        tiup playground nightly

Playground Bootstrapping...
Start pd instance
Start tikv instance
Start tidb instance

Waiting for tidb instances ready
127.0.0.1:4000 ... Error
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x18e6c34]

goroutine 117 [running]:
main.(*monitor).wait(0xc00049cd88)
	github.com/pingcap/tiup/components/playground/monitor.go:78 +0x14
main.(*Playground).bootMonitor.func1()
	github.com/pingcap/tiup/components/playground/playground.go:1034 +0x2d
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
Error: run `/Users/minghang.zmh_1_2/.tiup/components/playground/v1.8.1/tiup-playground` (wd:/Users/minghang.zmh_1_2/.tiup/data/SuAUFtJ) failed: exit status 2
