### ISSUE TITLE
the error info for redo "tiup cluster start --init" should be enhanced

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tiup#1708]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
redo "tiup cluster start --init" 
+ [ Serial ] - UpdateTopology: cluster=677
Started cluster `677` successfully
failed to set root password of TiDB database to '69zw548%BH#2i-VZ@C'

Error: Error 1045: Access denied for user 'root'@'172.16.5.101' (using password: NO)

2. What did you expect to see?

 Failed to reset the password for user 'root'@'172.16.5.101'  as the root user already set password (not empty).

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?

master

**Comment by qqqdan** [comment]
Fixed
