### ISSUE TITLE
the info after deploy success should add "--init"

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tiup#1709]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
[tidb@101 ~]$ /home/tidb/tiup_master/bin/tiup-cluster --version
tiup-cluster version 1.8.1 tiup
Go Version: go1.16
Git Ref: master
GitHash: 99bbe1d-dirty
[tidb@101 ~]$ 

[tidb@101 ~]$ /home/tidb/tiup_master/bin/tiup-cluster deploy 677 v5.4.0 tiup-config/677default.yaml -p
Enabling component blackbox_exporter
	Enabling instance 172.16.6.77
	Enable 172.16.6.77 success
Cluster `677` deployed successfully, you can start it with command: `tiup-cluster start 677`

2. What did you expect to see?

you can start it with command: `tiup-cluster start 677 --init`

3. What did you see instead?

you can start it with command: `tiup-cluster start 677`

4. What version of TiUP are you using (`tiup --version`)?

master

**Comment by AstroProfundis** [comment]
done in #1710
