### ISSUE TITLE
tiup cluster: ngm needs to be notified when change pd topology

### ISSUE THREAD

**Issue by zhongzc** [pingcap/tiup#1731]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
a. deploy a nightly cluster with 1 pd, 1 db, 1 kv, 1 ngm
b. scale-out a pd
c. scale-in the original pd

2. What did you expect to see?
a. the config of ngm is modified to the new pd topology.
b. notify ngm by sending a SIGHUP to it, and ngm logs as follow:
    ```
    [2022/01/19 03:17:18.891 +00:00] [INFO] [config.go:294] ["received SIGHUP and ready to reload config"]
    ```

3. What did you see instead?
Config was changed but ngm wasn't notified.

4. What version of TiUP are you using (`tiup --version`)?
```
1.7.0 tiup
Go Version: go1.17.3
Git Ref: v1.7.0
GitHash: ce8eb0a645cc3ead96a44d67b1ecd5034d112cf0
```

**Comment by AstroProfundis** [comment]
Are you using `tiup-playground` or `tiup-cluster`?

**Comment by zhongzc** [comment]
> Are you using tiup-playground or tiup-cluster?

`tiup-cluster`
