### ISSUE TITLE
A way to set password of TiDB database in `tiup cluster deploy`

### ISSUE THREAD

**Issue by zzxwill** [pingcap/tiup#1764]
I wonder whether there is a way to set the password of TiDB database in `tiup cluster deploy`?

Currently, the password of TiDB database will be automatically generated, it's difficult for a deployment tool to catch the password.

``` shell
Started cluster `db` successfully
The root password of TiDB database has been changed.
The new password is: '@7#^X64dC50TZ2ezx*'.
Copy and record it to somewhere safe, it is only displayed once, and will not be stored.
The generated password can NOT be get and shown again.
```

**Comment by srstack** [comment]
cc https://docs.pingcap.com/zh/tidb/stable/production-deployment-using-tiup#%E7%AC%AC-7-%E6%AD%A5%E5%90%AF%E5%8A%A8%E9%9B%86%E7%BE%A4

**Comment by zzxwill** [comment]
@srstack 不失为一种方案：）

是不是暂时没有提供用户自己设置数据库密码的方式？

**Comment by srstack** [comment]
> 

yes  : (

**Comment by nexustar** [comment]
> @srstack 不失为一种方案：）
> 
> 是不是暂时没有提供用户自己设置数据库密码的方式？

`tiup cluster start --init` is basicaly `tiup cluster start` and sql `SET PASSWORD FOR 'root'@'%%' = '%s'; FLUSH PRIVILEGES;`
if you need to catch the password, you cloud use `tiup cluster start` and set password like this

**Comment by zzxwill** [comment]
@nexustar Great!

**Comment by Perusae** [comment]
> > [@srstack](https://github.com/srstack) 不失为一种方案：）
> > 是不是暂时没有提供用户自己设置数据库密码的方式？
> 
> `tiup cluster start --init` is basicaly `tiup cluster start` and sql `SET PASSWORD FOR 'root'@'%' = 'new password'; FLUSH PRIVILEGES;` if you need to catch the password, you cloud use `tiup cluster start` and set password like this

I like to inform a small update on this:

> Started cluster `cluster01` successfully
> Failed to set root password of TiDB database to 'xxxxxxxxxxx'
> Initializing is only working when the root password is empty
> Did you already set root password before?
> 
> Error: Error 1045 (28000): Access denied for user 'root'@'100.100.100.100' (using password: NO)

If this error shows up, you do not solve it with:

> mysql -h 100.100.100.100 -P 4000 -u root
> SET PASSWORD FOR 'root'@'%' = 'xxxxxxxxxxxxx'; FLUSH PRIVILEGES;

As that is the impression given by the above post. That password command allows you to connect to the DB but not to the UI.

You are required for the UI to set a password directly to the host IP.

> SET PASSWORD FOR 'root'@'100.100.100.100' = 'xxxxxxxxxxxxx'; FLUSH PRIVILEGES;

And reload the UI in the browser, as there is a bug where reloading the failed login page, will keep it stuck on that failed login.

Hope this helps some people.
