### ISSUE TITLE
tiup cluster check topology --apply bug

### ISSUE THREAD

**Issue by tongtongyin** [pingcap/tiup#1766]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/37565148/154608436-144bef00-b4ba-48f8-871d-9cd946e4b25f.png">
stdout and stderr are written backwards

2. What did you expect to see?

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?
1.8.2

**Comment by qqqdan** [comment]
It is by design.
