### ISSUE TITLE
Tiup should ignore deprecated components

### ISSUE THREAD

**Issue by Fullstop000** [pingcap/tiup#177]
![image](https://user-images.githubusercontent.com/12471960/79682558-df652400-8255-11ea-9c66-2418bd8758f3.png)

Since the `tpc` has been integrated into `bench`,  I think it should not fire a `NOT FOUND` error. And it can be more user friendly to support cleaning up deprecated components automatically.

**Comment by lonng** [comment]
@Fullstop000 Nice catch, can you submit a PR to fix it?

**Comment by nrc** [comment]
Long term, this is covered by the design in #193 (called yanked, rather than deprecated)

**Comment by AstroProfundis** [comment]
Yanked component is already implemented in #574 and we should adjust existing manifests to set values for them. cc @lucklove
