### ISSUE TITLE
tiup playground panic

### ISSUE THREAD

**Issue by maxshuang** [pingcap/tiup#1771]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

tiup  playground  nightly --tag newest   --db 1 --kv 3 --pd 1  --ticdc 1 

2. What did you expect to see?
set up cluster normally

3. What did you see instead?
➜  530 tiup  playground  nightly --tag newest   --db 1 --kv 3 --pd 1  --ticdc 1 
Found playground newer version:

    The latest version:         v1.9.1
    Local installed version:    v1.8.0
    Update current component:   tiup update playground
    Update all components:      tiup update --all

Starting component `playground`: /Users/maxshuang/.tiup/components/playground/v1.8.0/tiup-playground nightly --tag newest --db 1 --kv 3 --pd 1 --ticdc 1
Using the version v5.5.0-nightly-20220220 for version constraint "nightly".
		
If you'd like to use a TiDB version other than v5.5.0-nightly-20220220, cancel and retry with the following arguments:
	Specify version manually:   tiup playground <version>
	Specify version range:      tiup playground ^5
	The nightly version:        tiup playground nightly

Playground Bootstrapping...
Start pd instance
The component `pd` version v5.5.0-nightly-20220220 is not installed; downloading from repository.
component pd version v5.5.0-nightly-20220220 is already installed
Start tikv instance
The component `tikv` version v5.5.0-nightly-20220220 is not installed; downloading from repository.
component tikv version v5.5.0-nightly-20220220 is already installed
Start tikv instance
The component `tikv` version v5.5.0-nightly-20220220 is not installed; downloading from repository.
component tikv version v5.5.0-nightly-20220220 is already installed
Start tikv instance
The component `tikv` version v5.5.0-nightly-20220220 is not installed; downloading from repository.
component tikv version v5.5.0-nightly-20220220 is already installed
Start tidb instance
The component `tidb` version v5.5.0-nightly-20220220 is not installed; downloading from repository.
component tidb version v5.5.0-nightly-20220220 is already installed
Start ticdc instance
The component `cdc` version v5.5.0-nightly-20220220 is not installed; downloading from repository.
component cdc version v5.5.0-nightly-20220220 is already installed
Waiting for tidb instances ready
127.0.0.1:61608 ... Error
The component `prometheus` version v5.5.0-nightly-20220220 is not installed; downloading from repository.
component prometheus version v5.5.0-nightly-20220220 is already installed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1050dd2e0]

goroutine 127 [running]:
main.(*monitor).wait(0x0)
	github.com/pingcap/tiup/components/playground/monitor.go:78 +0x20
main.(*Playground).bootMonitor.func1()
	github.com/pingcap/tiup/components/playground/playground.go:1034 +0x30
golang.org/x/sync/errgroup.(*Group).Go.func1(0x140004b6370, 0x140005c8190)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x60
Error: run `/Users/maxshuang/.tiup/components/playground/v1.8.0/tiup-playground` (wd:/Users/maxshuang/.tiup/data/newest) failed: exit status 2

4. What version of TiUP are you using (`tiup --version`)?
1.5.5 tiup
Go Version: go1.16.7
Git Ref: v1.5.5
GitHash: 01df6de49dbf23af1a3e9d6f71d383c407cdb810

**Comment by nexustar** [comment]
it has been fixed in tiup-playground v1.8.2, please update your playground with `tiup update playground`
