### ISSUE TITLE
when upgrade tidb or add new component to tidb，alertmanager and prometheus config was override？

### ISSUE THREAD

**Issue by lddlww** [pingcap/tiup#1772]
altermanager config and prometheus config was override when add component to tidb like ticdc，or upgrade tidb to newly version

that‘s very confuse to users which result in alert missing

**Comment by qqqdan** [comment]
TiUP will override the config for grafana/alertmanager/prometheus.
please refer to this doc about how to add some customized config ：https://docs.pingcap.com/zh/tidb/dev/customized-montior-in-tiup-environment
