### ISSUE TITLE
Automatically backup meta.yaml to etcd

### ISSUE THREAD

**Issue by qqqdan** [pingcap/tiup#1783]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Even though we will provide a backup command to backup meta.yaml ,but it needs some manual action or extra script to regular backup. 
Suggest to backup meta.yaml to etcd daily and then user can restore it from etcd after the original file is deleted. 

**Describe the feature you'd like:**

**Why the featue is needed:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by c4pt0r** [comment]
I don't think it's a good idea, although the tiup cluster currently does in fact implicitly depend on its cluster's etcd, this dependency is based on *known* individual cluster addresses and configuration information (we know exactly where the pd is).

So imagine a multi-cluster scenario: where the whole tiup's meta backups should be stored in which cluster's etcd?

If this feature is added, then tiup clusters will now rely on an etcd, increasing the mental burden of deployment for users

I think it is reasonable to provide export (backup) / import (restore) of metadata, as mentioned here: https://github.com/pingcap/tiup/issues/1782

Then let the user decide how and where to store the backup files, and at most provide a post-hook to execute the command after the backup is done, as in this example:
https://github.com/dreamer/scrot/blob/master/src/options.c#L285

You can refer to scrot's `-e` parameter

**Comment by nexustar** [comment]
> I don't think it's a good idea, although the `tiup cluster` currently does in fact implicitly depend on its cluster's etcd, this dependency is based on _known_ individual cluster addresses and configuration information (we know exactly where the pd is).
> 
> So imagine a multi-cluster scenario: where the whole tiup's meta backups should be stored in which cluster's etcd?
> 
> If this feature is added, then tiup clusters will now rely on a specific etcd to store backup metadata, increasing the mental burden of deployment for users
> 
> I think it is reasonable to provide export (backup) / import (restore) of metadata, as mentioned here: #1782
> 
> Then let the user decide how and where to store the backup files, and at most provide a post-hook to execute the command after the backup is done, as in this example: https://github.com/dreamer/scrot/blob/master/src/options.c#L285
> 
> You can refer to scrot's `-e` parameter

what about backing up each  meta.yaml to its onw cluster's etcd?
