### ISSUE TITLE
Tiup check oracle linux shows os version failed

### ISSUE THREAD

**Issue by Buddy-Yuan** [pingcap/tiup#1787]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

os version return an fail status when I execute the tiup check command。
<img width="925" alt="image" src="https://user-images.githubusercontent.com/23466348/157414344-b5ec1ace-3206-4ed2-ba11-6130c79b3e06.png">

The customer os is oracle linux 。 
![image](https://user-images.githubusercontent.com/23466348/157416168-9e2f34c8-02b6-4115-a16b-5281976d0aa8.png)

2. What did you expect to see?
I'm expecting show the status as pass。

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?
```
1.6.1 tiup  
Go Version: go1.17.2  
Git Ref: v1.6.1  
GitHash: 1f6ca2b18e5c96c075efb4c08084d6dc8659050b  
```

**Comment by srstack** [comment]
https://github.com/pingcap/tiup/pull/1786
