### ISSUE TITLE
Fail to run `tiup playground`

### ISSUE THREAD

**Issue by fengid** [pingcap/tiup#1792]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

tiup playground

2. What did you expect to see?
run success

3. What did you see instead?

fengid@fengid-MBP ~ % tiup playground       
tiup is checking updates for component playground ...
Starting component `playground`: /Users/fengid/.tiup/components/playground/v1.9.2/tiup-playground /Users/fengid/.tiup/components/playground/v1.9.2/tiup-playground
Using the version v5.4.0 for version constraint "".
		
If you'd like to use a TiDB version other than v5.4.0, cancel and retry with the following arguments:
	Specify version manually:   tiup playground <version>
	Specify version range:      tiup playground ^5
	The nightly version:        tiup playground nightly

Playground Bootstrapping...
Start pd instance:v5.4.0
Start tikv instance:v5.4.0
Start tidb instance:v5.4.0
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
Waiting for tidb instances ready
127.0.0.1:4000 ... Done
Force tidb(43643) to quit...
tidb quit
Force tikv(43642) to quit...
tikv quit
Force pd(43641) to quit...
pd quit
prometheus quit
ng-monitoring quit
Error: Playground bootstrapping failed: exit status 1

4. What version of TiUP are you using (`tiup --version`)?

1.9.2 tiup
Go Version: go1.17.7
Git Ref: v1.9.2
GitHash: d90f3eb81e145621c3880c320b88bf10c6f03a70

OS: macOS 12.2.1,m1

**Comment by pangsq** [comment]
Same problem in my m1 mbp.
There is a broken symbolic link in `https://tiup-mirrors.pingcap.com/grafana-v5.4.0-darwin-arm64.tar.gz` which caused an error in tiup's installing grafana procedure.
After removing the link `~/.tiup/components/grafana/v5.4.0/plugins-bundled/internal/input-datasource/node_modules/.bin/grafana-toolkit`, tiup playground succeeded.

**Comment by fengid** [comment]
Thank you very much!

**Comment by fengid** [comment]
> Same problem in my m1 mbp. There is a broken symbolic link in `https://tiup-mirrors.pingcap.com/grafana-v5.4.0-darwin-arm64.tar.gz` which caused an error in tiup's installing grafana procedure. After removing the link `~/.tiup/components/grafana/v5.4.0/plugins-bundled/internal/input-datasource/node_modules/.bin/grafana-toolkit`, tiup playground succeeded.

You  are right, thank you!
