### ISSUE TITLE
When scale-in a node by tiup, the dashboard still retains the information of the node

### ISSUE THREAD

**Issue by wxiaoke** [pingcap/tiup#1804]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

tiup cluster scale-in tidb-cluster -N XX

2. What did you expect to see?
the node  offline and disappear in dashboard

3. What did you see instead?
The node still exists in the dashboard, and the status is inaccessible, this information is easy to mislead customers

4. What version of TiUP are you using (`tiup --version`)?
 tiup --version
1.9.2 tiup
Go Version: go1.17.7
Git Ref: v1.9.2
GitHash: d90f3eb81e145621c3880c320b88bf10c6f03a70

**Comment by chenmin1992** [comment]
Is there any plan to fix this bug ? @nexustar @qqqdan

**Comment by nexustar** [comment]
fixed by #2011 released on v1.10.3
