### ISSUE TITLE
after abnormally stopped reload cluster ,pd scheduler leave over evict-leader-scheduler

### ISSUE THREAD

**Issue by keeplearning20221** [pingcap/tiup#1855]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

1) tiup cluster reload t2
2)when reload tikv , execute ctrl + c 
3)pd-ctl scheduler config evict-leader-scheduler --pd

2. What did you expect to see?
tiup cluster reload does not introduce any persistent configuration

3. What did you see instead?
After abnormally stopped reload cluster , do not affect any configuration of the cluster unless the configuration is modified by the user

4. What version of TiUP are you using (`tiup --version`)?
[tidb2@localhost ~]$ tiup --version
1.9.3 tiup
Go Version: go1.17.7
Git Ref: v1.9.3
GitHash: f523cd5e051d0001e25d5a8b2c0d5d3ff058a5d5

**Comment by qqqdan** [comment]
currently this is only a special case in test scenario, no customer report this issue.
