### ISSUE TITLE
Can tiup specify a package when scale-out occurs.

### ISSUE THREAD

**Issue by jiaqizho** [pingcap/tiup#1872]
## Feature Request

**Is your feature request related to a problem? Please describe:**
When I do `tiup cluster scale-out cluster-name scale-out.yaml`, I want specify a special version of TIDB/TIKV/TIFlash package.

But seem like `tiup` not supported for like. Only can use  `--stage1` replace it.

**Describe the feature you'd like:**

Is it possible to add an arg which name `--package`. may also need add an arg which name `--package-type` to specify which role need be change package.

**Why the featue is needed:**

more user friendly.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by srstack** [comment]
The first requirement for a cluster is to use a special  version of a component, which is supported by Tiup Patch

With scale-out, we need to keep the cluster version consistent, so we don't know how to use a special version of scale-out.



Try the following

1. scale-out --stage1

2. patch

3. scale-out --stage2

**Comment by jiaqizho** [comment]
> The first requirement for a cluster is to use a special version of a component, which is supported by Tiup Patch
> 
> Scale-out, however, we need to keep the cluster version consistent, so we do not support the use of a special version of scale-out.
> 
> Try the following
> 
> 1. scale-out --stage1
> 2. patch --offline
> 3. scale-out --stage2

@srstack sure, I mean can we use a simple way to replace these three step:

```
scale-out --stage1
patch --offline
scale-out --stage2
```
