### ISSUE TITLE
May I know why I can NOT find `client` package in the TiDB v6.0 offline component package ?

### ISSUE THREAD

**Issue by shawn0915** [pingcap/tiup#1876]
Can NOT find `client-v1.9.4-linux-amd64.tar.gz` in the TiDB v6.0 offline component package, 
both of  `tidb-community-server-v6.0.0-linux-amd64.tar.gz` and `tidb-community-toolkit-v6.0.0-linux-amd64.tar.gz`,
and doesn't see any explain from official document, 
could you please offer the reason here?
Thanks.

**Comment by shawn0915** [comment]
also, can not find `tiup-server`, but we can see the `bench-v1.9.4-linux-amd64.tar.gz` in the `tidb-community-toolkit-v6.0.0-linux-amd64.tar.gz`.

**Comment by nexustar** [comment]
tiup server is used for tiup-mirror server.And tiup client is only useful for tiup playground

**Comment by shawn0915** [comment]
@nexustar thanks for you reply.

>tiup server is used for tiup-mirror server.

yes, so when we download offline package, and move these pkg into internal network, we need build an internal mirror server with `tiup server`, that's the meaning of `server`, I think. 
so, will we remove `server` and `client` from offline pkg forever?

**Comment by nexustar** [comment]
tiup server is used to reveive package and sign them. for offline package, they are already signed and the "server" is just your hard-drive path, it is no need to use tiup server unless you want to build and maintenance a server that allow other to upload package

**Comment by nexustar** [comment]
tiup client is an sql client that only usable for tiup playground for trail. For production environment, you should use `tiup cluster` to management TiDB and connect with mycql client or other compatible client. So, we will remove server forever, and maybe will add client if people need it
