### ISSUE TITLE
using tiup deploy TiDB cluster but get `Please check for root manifest file`

### ISSUE THREAD

**Issue by dongb0** [pingcap/tiup#1908]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

###  1 What did you do?
Trying to deploy TiDB cluster on a single machine using TIUP tool.

I followed the instruction on [Deploy TiDB using TiUP](https://docs.pingcap.com/zh/tidb/v4.0/production-deployment-using-tiup), everything worked fine until Step 4 execute deployment command, I run `sudo tiup cluster deploy tidb-test v6.0.0 ./topology.yaml --user my-user-name`

I had configured SSH key for the user `my-user-name`, and I did login `my-user-name` without any interaction. 

### 2 What did you expect to see?

I suppose it would print something as the document suggests `Deployed cluster tidb-test successfully`, so that I can move on to the next step.

### 3 What did you see instead?

```
Please check for root manifest file, you may download one from the repository mirror, or try `tiup mirror set` to force reset it.
Error: initial repository from mirror(https://tiup-mirrors.pingcap.com/) failed: error loading manifest root.json: open /var/root/.tiup/bin/root.json: no such file or directory
```

I install TiUP using `curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh`, and it seems that TiUP is installed under `~/.tiup/bin/`, I don't know why it trys to search root.json in `/var/root/.tiup/bin`. Is there any thing I could change its configuration? Thanks in advance.

BTW, I tried [Offline Deploy](https://docs.pingcap.com/zh/tidb/v4.0/production-offline-deployment-using-tiup) as well, and it reported the same error. And my user name on the target machine contains special character `.`, will that cause any problem?

### 4 What version of TiUP are you using (`tiup --version`)?
1.9.6

**Comment by qqqdan** [comment]
Suggest not to use “sudo ” in your deployment command
