### ISSUE TITLE
ssh key is changed by background timed task

### ISSUE THREAD

**Issue by qiuwenhuifx** [pingcap/tiup#1909]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

do tidb cluster upgrade 
2. What did you expect to see?

Permissions 0755 for '/root/.tiup/storage/cluster/clusters/xxxxx-xxxxxx/ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/root/.tiup/storage/cluster/clusters/xxxxx-xxxxxx/ssh/id_rsa": bad permissions

3. What did you see instead?
when I fix this file permissions, it will be changed by background timed task

4. What version of TiUP are you using (`tiup --version`)?

tiup --version
v1.3.2 tiup
Go Version: go1.13
Git Branch: release-1.3
GitHash: 2d88460

**Comment by qqqdan** [comment]
TiUP will not change the permission of the ssh key, please check if there is any other tool impact this.
