### ISSUE TITLE
DM cluster can't start while -hostname use FQDN

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/tiup#1911]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
use FQDN in -hostname area
deploy DM cluster
try to start dm cluster

2. What did you expect to see?
DM cluster can start as expect.

3. What did you see instead?
start dm cluster failed

4. What version of TiUP are you using (`tiup --version`)?
1.9.4

**Comment by XuJianxu** [comment]
Please refer to https://github.com/pingcap/tiflow/issues/5648

**Comment by AstroProfundis** [comment]
Hostname support for instances in `tiup-cluster` and `tiup-dm` is not fully working yet, end users should **not** use hostnames / domain names for deploying. However, we do plan to do so and any test results about using hostnames are welcomed.
