### ISSUE TITLE
tiup cluster commpent "Failed to execute command over SSH" after upgrade from v1.9.6 to v1.10.0

### ISSUE THREAD

**Issue by Haaahei** [pingcap/tiup#1916]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
tiup cluster check topology.yaml
tiup is checking updates for component cluster ...
Starting component `cluster`: /home/admin/.tiup/components/cluster/v1.10.0/tiup-cluster check topology.yaml

+ Detect CPU Arch Name
  - Detecting node xxx Arch info ... Error
  - Detecting node xxx Arch info ... Error
  - Detecting node xxx Arch info ... Error
  - Detecting node xxx Arch info ... Error
  - Detecting node xxx Arch info ... Error
  - Detecting node xxx Arch info ... Error

Error: failed to fetch cpu-arch or kernel-name: executor.ssh.execute_failed: Failed to execute command over SSH for 'admin@xxx:20' {ssh_stderr: , ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin uname -m}, cause: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

2. What did you expect to see?
tiup cluster:v1.9.6 check topology.yaml
Starting component `cluster`: /home/admin/.tiup/components/cluster/v1.9.6/tiup-cluster check topology.yaml

+ Detect CPU Arch
+ Detect CPU Arch
  - Detecting node xxx ... Done
  - Detecting node xxx ... Done
  - Detecting node xxx ... Done
  - Detecting node xxx ... Done
  - Detecting node xxx ... Done
  - Detecting node xxx ... Done

3. What did you see instead?
check failed

4. What version of TiUP are you using (`tiup --version`)?

**Comment by AstroProfundis** [comment]
This should be fixed in `v1.10.1`, please upgrade with `tiup upgrade cluster` and try again.

**Comment by AstroProfundis** [comment]
dupe w/ #1913
