### ISSUE TITLE
tiup edit-config should forbid pd related config

### ISSUE THREAD

**Issue by mayjiang0203** [pingcap/tiup#1918]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Step 1、tiup cluster edit-config modify pd config from  replication-mode.replication-mode: "dr-auto-sync" to replication-mode.replication-mode: "majority";
Step 2、tiup  cluster reload -R pd
Step 3、Check the pd config via pd-ctl 
sh-4.2# tiup ctl:nightly pd -u http://pd1-peer.testbed-tiup-hm-hqwwm:2379 config show replication-mode
Starting component `ctl`: /root/.tiup/components/ctl/v6.2.0-alpha-nightly-20220614/ctl /root/.tiup/components/ctl/v6.2.0-alpha-nightly-20220614/ctl pd -u http://pd1-peer.testbed-tiup-hm-hqwwm:2379 config show replication-mode
{
  "replication-mode": "dr-auto-sync",
  "dr-auto-sync": {
    "label-key": "dc",
    "primary": "dc1",
    "dr": "dc2",
    "primary-replicas": 2,
    "dr-replicas": 1,
    "wait-store-timeout": "1m0s",
    "tikv-sync-timeout-hint": "1m0s",
    "pause-region-split": "false"
  }
}

[root@pd1-0 conf]# cat pd.toml
# WARNING: This file is auto-generated. Do not edit! All your modification will be overwritten!
# You can use 'tiup cluster edit-config' and 'tiup cluster reload' to update the configuration
# All configuration items you want to change can be added to:
# server_configs:
#   pd:
#     aa.b1.c3: value
#     aa.b2.c4: value
[pd-server]
min-resolved-ts-persistence-interval = "2s"

[replication]
location-labels = ["dc", "zone", "host"]

[replication-mode]
replication-mode = "majority"
[replication-mode.dr-auto-sync]
dr = "dc2"
dr-replicas = 1
label-key = "dc"
primary = "dc1"
primary-replicas = 2
wait-store-timeout = "1m"
wait-sync-timeout = "1m"

2. What did you expect to see?
Step 1 failed or Step 3 found the config has been changed.

3. What did you see instead?
Step 1 succeeded, but the pd config has been changed.

5. What version of TiUP are you using (`tiup --version`)?
sh-4.2# tiup --version
1.9.1 tiup
Go Version: go1.17.7
Git Ref: v1.9.1
GitHash: 8c9d75df55c48e3cd645c2eea1fb0c51cfcd92d0

Since for pd, except for the first start，pd will get config from etcd instead of config file, so the config not works.

**Comment by AstroProfundis** [comment]
The `edit-config` is intended to edit the configuration files for components, it does what it is designed: the `pd.toml` **is updated** with the values in topology file.

The problem here is that PD only reads configuration from file the first time it starts, no matter what modification is make to the config file, it won't take affect, this should be an issue of PD, not TiUP Cluster.
