### ISSUE TITLE
Support tidb-lightning

### ISSUE THREAD

**Issue by yeya24** [pingcap/tiup#192]
## Feature Request

It would be nice to have tidb-lightning in tiup as well.

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

We can install and run tidb-lightning via tiup easily

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by AstroProfundis** [comment]
Thank you for the advise, we'll see if we can add lightning support in next major release.

**Comment by lonng** [comment]
Now, you can install tidb-lightning via `tiup install tidb-lightning`.
