### ISSUE TITLE
redhat8.4, tiup cluster deploy fail with "Error: getwd: no such file or directory"

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tiup#1938]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
install tiup1.10.2  on redhat 8.4 os
install tidb cluster and start cluster

2. What did you expect to see?

tidb cluster can be installed and started

3. What did you see instead?
[root@tiup-0 log]# tiup cluster deploy debug v5.0.0 /tmp/2022-06-27T17:24:05+08:00.tiup.yaml --ssh=system -y
tiup is checking updates for component cluster ...
Error: getwd: no such file or directory
[root@tiup-0 log]# ls /tmp/2022-06-27T17:24:05+08:00.tiup.yaml
/tmp/2022-06-27T17:24:05+08:00.tiup.yaml
[root@tiup-0 log]# tiup --version
1.10.2 tiup
Go Version: go1.18.3
Git Ref: v1.10.2
GitHash: 2de5b500c9fae6d418fa200ca150b8d5264d6b19
[root@tiup-0 log]# tiup cluster --version
tiup is checking updates for component cluster ...
Error: getwd: no such file or directory

4. What version of TiUP are you using (`tiup --version`)?

[root@tiup-0 log]# tiup --version
1.10.2 tiup
Go Version: go1.18.3
Git Ref: v1.10.2
GitHash: 2de5b500c9fae6d418fa200ca150b8d5264d6b19

**Comment by qqqdan** [comment]
According to Ting, this issue does not reproduce for tidb v6.0.

**Comment by qqqdan** [comment]
This error is not an operation compatibility issue . It may be caused by deployment environment.
