### ISSUE TITLE
Alertmanager is unavailable/reported as down if deployed using hostname.

### ISSUE THREAD

**Issue by andreifedorov-bolt** [pingcap/tiup#1993]
When deploying a new cluster using tiup and monitoring instance is defined using hostname, alertmanager is not available after starting the cluster.

Example configuration fragment:
>monitoring_servers:
>  - host: ti-andrei-tidb.testdb
>
>grafana_servers:
>  - host: ti-andrei-tidb.testdb
>
>alertmanager_servers:
 > - host: ti-andrei-tidb.testdb

After deploying and starting the cluster:
>[andrei@ti-andrei-manager ~]$ tiup cluster display andrei-test
>Starting component `cluster`: /home/andrei/.tiup/components/cluster/v1.10.2/tiup-cluster display andrei-test
>Cluster type:       tidb
>Cluster name:       andrei-test
>Cluster version:    v6.1.0
>Deploy user:        tidb
>SSH type:           system
>Dashboard URL:      http://ti-andrei-pd.testdb:2379/dashboard
>Grafana URL:        http://ti-andrei-tidb.testdb:3000
>ID                           Role          Host                   Ports        OS/Arch        Status   Data Dir                      Deploy Dir
>--                           ----          ----                   -----        -------        ------   --------                      ----------
>ti-andrei-tidb.testdb:9093   alertmanager  ti-andrei-tidb.testdb  9093/9094    linux/aarch64  Down     /tidb-data/alertmanager-9093  /tidb-deploy/alertmanager-9093
>ti-andrei-tidb.testdb:3000   grafana       ti-andrei-tidb.testdb  3000         linux/aarch64  Up       -                             /tidb-deploy/grafana-3000
>ti-andrei-pd.testdb:2379     pd            ti-andrei-pd.testdb    2379/2380    linux/aarch64  Up|L|UI  /tidb-data/pd-2379            /tidb-deploy/pd-2379
>ti-andrei-tidb.testdb:9090   prometheus    ti-andrei-tidb.testdb  9090/12020   linux/aarch64  Up       /tidb-data/prometheus-9090    /tidb-deploy/prometheus-9090
>ti-andrei-tidb.testdb:4000   tidb          ti-andrei-tidb.testdb  4000/10080   linux/aarch64  Up       -                             /tidb-deploy/tidb-4000
>ti-andrei-tikv.testdb:20160  tikv          ti-andrei-tikv.testdb  20160/20180  linux/aarch64  Up       /tidb-data/tikv-20160         /tidb-deploy/tikv-20160

![image](https://user-images.githubusercontent.com/62988159/180185651-ab017722-9e39-4b0a-ad20-987d03054825.png)

In that case, alertmanager is bound to 127.0.0.1 only and does not listen on external interfaces:
>[root@ti-andrei-tidb scripts]# netstat -aln|grep 9093
>tcp        0      0 127.0.0.1:9093          0.0.0.0:*               LISTEN     
>tcp        0      0 127.0.0.1:9093          127.0.0.1:50426         ESTABLISHED
>tcp        0      0 127.0.0.1:50426         127.0.0.1:9093          ESTABLISHED

Workaround I found is to change **/tidb-deploy/alertmanager-9093/scripts/run_alertmanager.sh** and comment/remove the following line and restart alertmanager service:
`#    --web.listen-address="ti-andrei-tidb.testdb:9093" \
`

**Comment by dveeden** [comment]
This is where this is set: https://github.com/pingcap/tiup/blob/ff88990bccc4fa0f19590f6d59400ba404d4f113/embed/templates/scripts/run_alertmanager.sh.tpl#L22

Could you try with this in the config:
```yaml
alertmanager_servers:
  - host: 10.0.0.1
    listen_host: 0.0.0.0
```

**Comment by dveeden** [comment]
See also: https://github.com/pingcap/tiup/blob/ff88990bccc4fa0f19590f6d59400ba404d4f113/embed/examples/cluster/topology.example.yaml#L318-L319
