### ISSUE TITLE
Initial server-side admin component

### ISSUE THREAD

**Issue by nrc** [pingcap/tiup#200]
Be able to generate file structure and manifests on the server; implement basic admin actions such as yanking components.

In the short term this lets us manage the repo, in the long term this will be the basis for the server-side code

~~Blocked on: https://github.com/pingcap-incubator/tiup/pull/193~~

Tasks:

- [ ] Create and initialise repo (#210)
- [ ] Update a component
- [ ] Yank a component
- [ ] Yank a version

**Comment by nrc** [comment]
I think the best way to implement this is as a new command, `repo` with the following subcommands:

```
init dir                    Initialise a new repository in dir, default is .
owner id name               Create a new owner
component id description    Create a new component
version component platform version file     Add the specified file to the repo 
yank component version      Yank the specified component, if there is no version, yank all versions
delete component version    Delete the specified component, if there is no version, yank all versions
```
All subcommands except `init` assume the repo is at `.`. Init requires the dest directory to be empty.

An example workflow would be:

```
$ tiup repo init 
$ tiup repo owner pingcap PingCAP
$ tiup repo component tikv "A key value store"
$ tiup repo component pd "PD"
$ tiup repo component tidb "A distributed MySQL database"
$ tiup repo version tikv x86_64-unknown-linux 1.0.0 ../tikv1.tar.gz
```

What do you think?

**Comment by nrc** [comment]
I guess some commnands will generate private keys and these should be printed to the command line. We'll also need a subcommand to generate and use a new key pair for timestamp role.

**Comment by AstroProfundis** [comment]
I'm going to add basic command entries now.

> We'll also need a subcommand to generate and use a new key pair for timestamp role.

I think this could be put under the `repo` subcmd, something like `tiup repo genkey`.

**Comment by lonng** [comment]
Done
