### ISSUE TITLE
Cluster upgrade failure: metric tikv_raftstore_region_count{type="leader"} not found

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tiup#2002]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

upgrade tidb cluster from v6.1.0 to v6.2.0

topo:
1 tidb + 3 tikv + 1 PD + 1 Tiflash

2. What did you expect to see?
The cluster was upgraded successfully.

3. What did you see instead?
The cluster failed to be upgraded with error:
`Error: failed to evict store leader tikv-1-peer: metric tikv_raftstore_region_count{type="leader"} not found`

It seems that when there is only 1 PD, Tiup tried to upgrade tikv after PD was upgraded but before it got the necessary information from TiKV.
![origin_img_v2_e7800502-c517-4f66-ac6d-4099d51a24bg](https://user-images.githubusercontent.com/84501897/182173013-c509e1e8-de4f-40c9-97b5-ac1d5f3192ac.jpg)

4. What version of TiUP are you using (`tiup --version`)?
```
1.9.1 tiup
Go Version: go1.17.7
Git Ref: v1.9.1
GitHash: 8c9d75df55c48e3cd645c2eea1fb0c51cfcd92d0
```

**Comment by qqqdan** [comment]
Tiup does not change upgrade logic recently. Will this issue only happened to 6.2.0 ?

**Comment by qqqdan** [comment]
1 PD is not a typical production environment . Remove this check may cause some potential issue. Currently we will not change any tiup logic for it . If there is more similar feedback, we will reopen this issue.

**Comment by Yui-Song** [comment]
In fact, I got the same error in a cluster with 3 PD before and I have also reported it in the incall.
