### ISSUE TITLE
tiup 所在机器彻底挂掉，还能重建吗 ？ 

### ISSUE THREAD

**Issue by xys2015** [pingcap/tiup#2003]
当前集群管理几乎是**必须**使用 tiup ，但是官方文档里没有提供任何关于 tiup 备份，高可用之类的机制，tiup也不像ansible那样可以简单的把文本数据保存在git上，那么问题来了，假如tiup 所在机器彻底挂掉，还有办法重建 tiup 需要的持久化数据吗

**Comment by Smityz** [comment]
我们之前试过，只需要备份一下 `~/.tiup` 这个文件夹就可以了

**Comment by nexustar** [comment]
具体来说只用备份 ~/.tiup/storage/cluster/clusters 。或者使用 `tiup cluster meta backup` 命令

**Comment by xys2015** [comment]
现在是机器已经挂了，无任何备份的情况下，在官方提了个帖子，参考 https://asktug.com/t/topic/873042/2
