### ISSUE TITLE
Support resource limit in playground

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [pingcap/tiup#2013]
## Feature Request

**Is your feature request related to a problem? Please describe:**

now `tiup cluster` support deploys a cluster with resource limitation, but `tiup playground` does not.

**Describe the feature you'd like:**

deploy a local test cluster with resource limitation by `tiup playground`, we can do like
```shell
tiup playground nightlt --db 3 --pd 3 --kv 3 --tiflash 1 --db.memory_limit 10G --kv.cpu_quota 1000
```

**Why the featue is needed:**

limit the resource used by local tidb cluster, and test the behaviour under cgroup conviently. 

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by nexustar** [comment]
You could use tiup cluster to deploy a local cluster. It is not playground's goal to implement all function tiup cluster has.
BTW, playground should be able to run without root. resource limit needs root unless use linux and cgroups v2
