### ISSUE TITLE
refactor update and install

### ISSUE THREAD

**Issue by nrc** [pingcap/tiup#202]
Refactor the update and install commands to take advantage of the new manifest system. #201 does the groundwork for this, this issue is about connecting everything together.

Blocked on: #201

Tasks:

- [x] Install and update components via new manifests
- [x] Install and update flows use the TUF flows

**Comment by nrc** [comment]
The following methods need to be re-implemented to work with v1 manifests, all in `Environment`:

- [ ] update/install
- [ ] self update
- [ ] `SelectInstalledVersion`
- [ ] `DownloadComponentIfMissing`
- [ ] `downloadComponent`

**Comment by nrc** [comment]
#230 contains an initial implementation that tackles some of the first checkbox in OP. The implementations in the above comment are prereqs for the second checkbox. In addition, there are a bunch of follow-ups to #230 that are required before this issue is done:

- [ ] Refine version selection (see TODOs)
- [ ] Cache manifests from disk in FsManifests (currently updating a manifest does a bunch of repetetive disk reads)
- [ ] Report error and continue with other updates, rather than stopping updates on first error
- [ ] Ensure we are doing all necessary validation of signatures and hashes
- [ ] Use `SignatureError` in `verifySignature`
- [ ] Finish unit tests for repository and manifests
- [ ] Validate root manifest

**Comment by july2993** [comment]
> The following methods need to be re-implemented to work with v1 manifests, all in `Environment`:
> 
> * [x]  update/install (#230)
> * [ ]  self update
> * [ ]  `SelectInstalledVersion`
> * [ ]  `DownloadComponentIfMissing` (#252)
> * [ ]  `downloadComponent` (#252)

seems no need for `SelectInstalledVersion`

**Comment by lonng** [comment]
Done
