### ISSUE TITLE
tiup does not support ipv6

### ISSUE THREAD

**Issue by jebter** [pingcap/tiup#2038]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

tiup can deploy ipv6 clusters, but cannot start clusters. The ipv6 format in the deployed run-script(pd/tidb/tikv/cdc/binlog/dm)/yaml(tiflash) is incorrect

2. What did you expect to see?
exec bin/pd-server \
    --name="pd-2401:1d40:f21:5208::19b-2379" \
    --client-urls="http://[::]:2379" \
    --advertise-client-urls="http://[2401:1d40:f21:5208::19b]:2379" \
    --peer-urls="http://[::]:2380" \
    --advertise-peer-urls="http://[2401:1d40:f21:5208::19b]:2380" \
    --data-dir="/home/tidb-02/tidb-data/pd-2379" \
    --initial-cluster="pd-2401:1d40:f21:5208::19b-2379=http://[2401:1d40:f21:5208::19b]:2380" \
    --config=conf/pd.toml \

3. What did you see instead?

exec bin/pd-server \
    --name="pd-2401:1d40:f21:5208::19b-2379" \
    --client-urls="http://0.0.0.0:2379" \
    --advertise-client-urls="http://2401:1d40:f21:5208::19b:2379" \
    --peer-urls="http://0.0.0.0:2380" \
    --advertise-peer-urls="http://2401:1d40:f21:5208::19b:2380" \
    --data-dir="/home/tidb-02/tidb-data/pd-2379" \
    --initial-cluster="pd-2401:1d40:f21:5208::19b-2379=http://2401:1d40:f21:5208::19b:2380" \
    --config=conf/pd.toml \

4. What version of TiUP are you using (`tiup --version`)?
tiup --version
1.10.3 tiup
Go Version: go1.18.5
Git Ref: v1.10.3
GitHash: e198ac54996fa5a29f1961a460d6634ee9e75d26

**Comment by nexustar** [comment]
Does TiDB supports ipv6 now? https://github.com/pingcap/tidb/issues/11701

**Comment by jebter** [comment]
Yes, tidb can work in ipv6
