### ISSUE TITLE
Check the port is not in used before start cluster

### ISSUE THREAD

**Issue by elsa0520** [pingcap/tiup#2048]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I'm having issues with startup failures when starting a cluster via TiUP.
The error is following:
```
Starting component pd
	Starting instance xxxx:2379
	Start instance xxxx:2379 success
Starting component tikv
	Starting instance xxxx:20160

Error: failed to start tikv: failed to start: xxxx tikv-20160.service, please check the instance's log(/tidb-deploy/tikv-20160/log) for more detail.: timed out waiting for port 20160 to be started after 2m0s

Verbose debug logs has been written to /.tiup/logs/tiup-cluster-debug-xxxx.log.
```

Then I checked the TiKV log, but I found from the log that TiKV failed to start because it couldn't connect to PD.

```
[2022/09/28 18:30:47.113 +08:00] [INFO] [util.rs:537] ["PD failed to respond"] [err="Grpc(RpcFailure(RpcStatus { code: 14-UNAVAILABLE, message: \"failed to connect to all addresses\", details: [] }))"] [endpoints=xxxx:2379]
```

So I went to check the PD log again and found that the port required by PD was actually in used.

```
[2022/09/28 18:32:07.270 +08:00] [FATAL] [main.go:117] ["run server failed"] [error="[PD:etcd:ErrStartEtcd]listen tcp 0.0.0.0:2380: bind: address already in use: listen tcp 0.0.0.0:2380: bind: address already in use"] [stack="main.main\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/pd/cmd/pd-server/main.go:117\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"]
```

**Describe the feature you'd like:**

Please check the port is not in used before start cluster.

**Why the featue is needed:**

Otherwise, I need to look at the logs layer by layer to know what caused the cluster startup failure.
And port is in used is actually a very common problem, which can be avoided in advance.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by AstroProfundis** [comment]
1. The `tiup-cluster` component is designed to be used on one console server and manages a set of deployment servers exclusively, anything outside that scope (typically multiple dedicated console servers are managing the same deployment server) is not supported.

2. All subcommands in `tiup-cluster` are idempotent, checking for port binding before starting a component will break that on a second run.
