### ISSUE TITLE
Is it possible to customize the upgrade sequence for different versions of a component?

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/tiup#2166]
## Feature Request

**Is your feature request related to a problem? Please describe:**
We want to change the upgrade order for TiCDC, but we meet some compliable issues for different versions of TiCDC.
If TiCDC < 5.1.0, we want to upgrade tikv/pd first.
If TiCDC >= 5.1.0, we want to upgrade tikv/pd first.

You can see more in [this doc.](https://pingcap.feishu.cn/docx/Nq9sdD44aorYeTxYo2gcZd9LnFU) (In Chinese)

**Describe the feature you'd like:**
Support customizing the upgrade sequence for different versions of a component.
Now we have a fixed order: https://github.com/pingcap/tiup/blob/e1a0855f2debdd1493753a96574649dd798b54dd/pkg/cluster/spec/spec.go#L716

**Why the featue is needed:**
We want to upgrade the ticdc first because the TiKV will make a breaking change. Then TiCDC can not connect to the new TiCDC if we upgrade TiKV first.

**Describe alternatives you've considered:**
None
**Teachability, Documentation, Adoption, Migration Strategy:**
None

**Comment by hi-rustin** [comment]
@nexustar Could you please take a look? What do you think about this feature? Thanks!

**Comment by nexustar** [comment]
1. Which version that TiKV will make a breaking change？

**Comment by hi-rustin** [comment]
> 1. Which version that TiKV will make a breaking change？

For example, https://github.com/pingcap/tiflow/issues/8115 this was caused by an incompliable issue.

> 2\. Is it necessary to make a breading change and not compatible to old TiCDC

We need it to work when rolling upgrade. If TIKV spend to many time to upgrade, we don't want cause a big lag in TiCDC.


> 3\. Some user are using TiDB without TiUP nor operator。What about these users？

We will update the docs to tell them what are best practices.


> 4\. If we have to add those “if”，I think we should add it to public doc first,then tiup-cluster and tidb-operator implement it

Yes, we need to update the docs at the same time. You can see more at [this doc.](https://pingcap.feishu.cn/docx/Nq9sdD44aorYeTxYo2gcZd9LnFU)

**Comment by hi-rustin** [comment]
@nexustar What do you think? Does it make sense to add this support?

**Comment by hi-rustin** [comment]
In terms of compatibility, TiUP and TiDB Operator need to support different upgrade order with 5.1.0 as the boundary.
1. If the current cluster version is greater than or equal to 5.1.0, TiCDC is upgraded first.
2. If the current cluster version is less than 5.1.0, upgrade PD and TiKV first.

**Comment by hi-rustin** [comment]
You can find more information at https://pingcap.feishu.cn/docx/Nq9sdD44aorYeTxYo2gcZd9LnFU.
