### ISSUE TITLE
Upgrade golang version to 1.20

### ISSUE THREAD

**Issue by shawn0915** [pingcap/tiup#2239]
## Feature Request

**Is your feature request related to a problem? Please describe:**

https://github.com/pingcap/tiup/blob/master/go.mod#L3
currently tiup still in use go 1.18, shall we bump version to 1.20, like other components.

**Describe the feature you'd like:**

**Why the featue is needed:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by dveeden** [comment]
Why not 1.21?
https://go.dev/blog/go1.21

**Comment by shawn0915** [comment]
> Why not 1.21? https://go.dev/blog/go1.21

wow, thank you. 👍‍ @dveeden
