### ISSUE TITLE
dead link in the code

### ISSUE THREAD

**Issue by shawn0915** [pingcap/tiup#2244]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

https://github.com/search?q=repo%3Apingcap%2Ftiup%20reference%2Fconfiguration%2Ftidb-server%2Fconfiguration-file%2F&type=code

some links in the code are dead, may we update?

> first record in AskTUG. https://asktug.com/t/topic/1010884

2. What did you expect to see?

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?

**Comment by kaaaaaaang** [comment]
fixed by #2242
