### ISSUE TITLE
miss the component name in deploy directory

### ISSUE THREAD

**Issue by nolouch** [pingcap/tiup#2270]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
run command:

```
 tiup playground v7.3.0  --tiflash=0  --pd.binpath=./pd-server --db.binpath=/Users/nolouch/bins/tidb-server --tag=stats
```

3. What did you expect to see?
tidb and tikv data in seperator dir.

4. What did you see instead?

![image](https://github.com/pingcap/tiup/assets/6428910/b4e5ca74-078e-4705-8b91-4907447d5d88)

5. What version of TiUP are you using (`tiup --version`)?
```
1.13.0 tiup
Go Version: go1.21.0
Git Ref: v1.13.0
GitHash: 0ed23db6f45b03f752c9d675c2431454ac8f82a9
```

**Comment by iosmanthus** [comment]
I did a binary-search on the commit history, it's the pull request: https://github.com/pingcap/tiup/pull/2226 introduced this bug.
