### ISSUE TITLE
tiup cluster patch ${cluster-id}  fail when use “source”

### ISSUE THREAD

**Issue by bob34007** [pingcap/tiup#2307]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

2. What did you expect to see?

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?

**Comment by kaaaaaaang** [comment]
already fixed at https://github.com/pingcap/tiup/pull/2264/files#diff-c07f91942f705838a753d5874472d43f475e0eb5903a7aa13b58619e5e376370L81
