### ISSUE TITLE
cluster display can display numa info of instance

### ISSUE THREAD

**Issue by 7yyo** [pingcap/tiup#2326]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

If the number of servers and instances is very large, it is very troublesome to view numa information through edit config. I hope to display the numa binding situation more intuitively.

**Why the featue is needed:**

If the number of servers and instances is very large, it is very troublesome to view numa information through edit config. I hope to display the numa binding situation more intuitively.

**Describe alternatives you've considered:**

none

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by kaaaaaaang** [comment]
already released at tiup-cluster v1.14.0
