### ISSUE TITLE
TiUP command `cluster` `stop` is not script-safe

### ISSUE THREAD

**Issue by innerr** [pingcap/tiup#240]
What I did in my bash script:
- Deployed, started a cluster
- Stopped the cluster
- Did physical backup by copying each deploy and data dir

What happened:
- The bash command `cp` thrown error message: can't find some file

What I expected:
- The bash command `cp` succeeded

Workaround:
- Added a `sleep 600` after the stop command, all things worked well

My guess:
- The tikv process was not fully stopped, so when I copied files, tikv was still doing compaction and gc so the files I was copying was removed by tikv

**Comment by lucklove** [comment]
It works with the newest cluster: tiup v1.0.7 tidb v4.0.0:
test.yaml:
```yam
global:
  user: test
  deploy_dir: "tidb-deploy"
  data_dir: "tidb-data"

tidb_servers:
  - host: 172.16.5.140

pd_servers:
  - host: 172.16.5.140

tikv_servers:
  - host: 172.16.5.140l
```

test.sh:
```sh
#! /bin/sh

tiup cluster deploy test v4.0.0 /tmp/test.yaml
tiup cluster start test
tiup cluster stop test

ssh root@172.16.5.140 "cp -r /home/test/tidb-deploy /home/test/tidb-back"
```

Maybe it has been fixed in the newest release.
Closing this issue, if you are still in problem, please reopen it.
