### ISSUE TITLE
tiup upgrade failed with error “Error: rename /root/.tiup/storage/cluster/packages/pd-v8.3.0-alpha-nightly-linux-amd64.tar.gz /root/.tiup/storage/cluster/packages/pd-nightly-linux-amd64.tar.gz: no such file or directory”

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiup#2452]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
upgrade from 8.1.1 to nightly

2. What did you expect to see?
upgrade success

4. What did you see instead?
upgrade failed
Error: rename /root/.tiup/storage/cluster/packages/pd-v8.3.0-alpha-nightly-linux-amd64.tar.gz /root/.tiup/storage/cluster/packages/pd-nightly-linux-amd64.tar.gz: no such file or directory

logs：
[tiup-cluster-debug-2024-08-15-13-53-32.log](https://github.com/user-attachments/files/16622708/tiup-cluster-debug-2024-08-15-13-53-32.log)

5. What version of TiUP are you using (`tiup --version`)?
nightly

**Comment by xhebox** [comment]
Root cause: parallel downloads of the same component(nightly version only bug), should be able to workaround by giving downloaded file a temporary suffix/prefix.
