### ISSUE TITLE
tiup becomes tiup.tmp unexpectly 

### ISSUE THREAD

**Issue by Fullstop000** [pingcap/tiup#297]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
- Run `tiup update --self`. And due to my network issue (on WSL2), it hangs connecting to a local proxy for a while.
- I press `<C-c>` during the hanging and then retype `tiup update --self` but Linux complains about `tiup is not found`.
- So I went to `~/.tiup/bin` and found that `tiup` has been altered to `tiup.tmp`
2. What did you expect to see?
`tiup` should still be there

3. What did you see instead?
`tiup` becomes `tiup.tmp`

4. What version of TiUP are you using (`tiup --version`)?
```
tiup version v0.0.5 tiup
Go Version: go1.13
Git Branch: master
GitHash: aab3add
Build Time: 2020-04-24 18:10:16 +0800
```

**Comment by AstroProfundis** [comment]
Hello, sorry for the inconvenience. The binary is renamed to `tiup.tmp` for a backup purpose, but it seems you didn't finished the following process so new binary is not installed.

We'll review the process to see if we can do the rename at a latter timepoint.
