### ISSUE TITLE
Fix the regex pattern for changing selinux config

### ISSUE THREAD

**Issue by hhkbp2** [pingcap/tiup#310]
Hi,

The regex pattern for changing selinux config in

https://github.com/pingcap-incubator/tiup-cluster/blob/master/cmd/cluster/command/check.go#L386

should be updated as in pingcap-incubator/tiup-cluster#361.

**Comment by lucklove** [comment]
The PR 361 has been merged

**Comment by hhkbp2** [comment]
??

Hi, they are different things. It checks the configuration of selinux when running "tiup cluster check", and the related issue is handled in  https://github.com/pingcap-incubator/tiup-cluster/pull/361. While it tries to fix the improper selinux config by changing the config file option when running "tiup cluster check --apply", which is this issue about.

**Comment by lucklove** [comment]
Oh, I got it. Sorry for my misunderstanding.

**Comment by hhkbp2** [comment]
@lucklove PR #541 merged. Close issue.
