### ISSUE TITLE
scale-out failed while scale.yaml contains imported:true

### ISSUE THREAD

**Issue by Win-Man** [pingcap/tiup#312]
I scale-out a tikv but failed.
![image](https://user-images.githubusercontent.com/12085878/79537598-2bc52e00-80b5-11ea-8e5c-dc33d81ca063.png)

scale.yaml content:
![image](https://user-images.githubusercontent.com/12085878/79537811-9c6c4a80-80b5-11ea-80a0-65465b19b32a.png)

I've tried to remove `imported:true` config，and try again. It could scale-out successfully.

**Comment by lucklove** [comment]
Maybe just forbiden setting `imported` field by users. It's reserved by tiup.

**Comment by AstroProfundis** [comment]
It's already implemented that if scaling out an instance with `imported: true` set, report error and not continue doing anything.
