### ISSUE TITLE
scale-in operation don't clean config directory

### ISSUE THREAD

**Issue by Win-Man** [pingcap/tiup#313]
I scale-in a tikv component,found that the `.service` and `.toml` file didn't clean up.
![image](https://user-images.githubusercontent.com/12085878/79538165-624f7880-80b6-11ea-8de3-00dc25fb080f.png)

I think there will be problems if this appears with  [#289](https://github.com/pingcap-incubator/tiup-cluster/issues/289)

1. scale-in a  component
2. scale-out a component with same ip:port ,but scale.yaml file contains `imported:true`
3. It will scale-out successfully with previous config.

**Comment by lonng** [comment]
It's expected to not delete the configuration file if the node has tag `imported: true`.
