### ISSUE TITLE
make useful tool like pd-ctl available

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tiup#314]
When using tidb-ansible, I can run pd-ctl easily as all tools are placed in resource directory. But when using tiup, there seems to be no way to run the command easily. I have to either download it from website or search local cache to find the tar package and extract it. It would be helpful to support it inside tiup cluster.

**Comment by lucklove** [comment]
We can use `tiup ctl xxx` in both online and offline mode now.

**Comment by BusyJay** [comment]
> It seem just download v3.0.x version. I need a version matched the cluster.

So can it match the version automatically?

**Comment by lucklove** [comment]
> So can it match the version automatically?

No, `tiup ctl xxx` work with both `tiup-cluster deployed` cluster and non `tiup-cluster deployed` cluster. It's decoupled.

**Comment by BusyJay** [comment]
What's the point of "decouple" when those should have connections?

I have seen complaint from DBAs in earlier discussions that ctls are not managed by cluster. It's quite natural to expect ctl matches the selected version of a cluster just like tikv-servers or tidb-servers since we use tiup to manage everything.

**Comment by lucklove** [comment]
> It's quite natural to expect ctl matches the selected version of a cluster just like tikv-servers or tidb-servers since we use tiup to manage everything.

As you see, we expect that tiup should manage everything. So user should never execute ctls directly, they should execute it with tiup. However, downloading the *ctls with cluster, extracting the binary file, and pointing out the path of them for users run counter to it.

**Comment by BusyJay** [comment]
> ...user should never execute ctls directly...

On one hand, I have never suggested to execute it directly. What I suggest is **match the version automatically**. Manage *ctl using cluster is a way to do it. For example, `tiup cluster ctl xxx` instead of `tiup ctl xxx`.

On the other hand, tikv-ctl is **required** to be run in local mode sometime. Hence it's unavoidable to allow user to execute tikv-ctl directly.

**Comment by lucklove** [comment]
> tiup cluster ctl xxx

This is ok, I think.

> tikv-ctl is required to be run in local mode sometime.

What is local mode? The command `tiup ctl tikv` is logically equivalent to `tikv-ctl`

**Comment by BusyJay** [comment]
Local mode means run tikv-ctl on the tikv machine. It needs to stop the tikv node first, and then use the tool to modify the data.

**Comment by lucklove** [comment]
> Local mode means run tikv-ctl on the tikv machine.

Then we can install tiup in the tikv machine.

**Comment by AstroProfundis** [comment]
Since `v1.4.0`, it's possible to use `tiup cluster display <cluster-name> --version` to get the cluster version in plain text, and it can be used to combine with other commands
