### ISSUE TITLE
Upgrade idempotent

### ISSUE THREAD

**Issue by kissmydb** [pingcap/tiup#315]
From：likun、qizheng、rongyilong

Phenomenon: The upgrade process failed, such as successful upgrade pd, tikv, tidb upgrade failed. However, upgrade does not support -N -R. Re-executing upgrade will restart the components that have been successfully upgraded again.

Suggestion: add parameters, if upgrade finds that the component has been upgraded, skip

**Comment by AstroProfundis** [comment]
It can now be done with `replay` sub command.
