### ISSUE TITLE
rolling modify port/ip for tikv/tidb

### ISSUE THREAD

**Issue by kissmydb** [pingcap/tiup#317]
Sometimes, users want to adjust the port or address of the online cluster

Use ansible we can do like this：https://tug.gitbook.io/tidb-sop/tidb-yun-wei-shou-ce-sop-xi-lie-v1.0/modify-port

**Comment by lucklove** [comment]
maybe dup with https://github.com/pingcap/tiup/issues/323

**Comment by lucklove** [comment]
IN progress: https://docs.google.com/document/d/1l3P2qrCb_NRoIGxOkc_uq3g4RRouZqS-G7iejFZFooQ/edit#
