### ISSUE TITLE
Unable to change PD address

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tiup#318]
I just deployed a cluster and then PD machine crashed and was brought back automatically with a different IP address. Now seems no way to update the PD address without destroying the cluster. tiup rejected to reload the cluster because PD said:
```
Error: failed to upgrade: failed to evict store leader ip: error requesting http://ip:2379/pd/api/v1/stores?state=0&state=1&state=2, response: "TiKV cluster
 not bootstrapped, please start TiKV first"
, code 500
```

This was a fair error because the cluster was started without turning off the firewall. So it was indeed not bootstrapped.

I tried to stop the whole cluster and reload again, tiup still tried to evit leader, which of cause would not succeed:
```
Error: failed to upgrade: failed to get PD leader ip: Get http://ip:2379/pd/api/v1/leader: dial tcp ip:2379: connect: connection refused
```

So there are two problems:
1. No way to force reloading the cluster like ignore evicting leader completely.
2. No way to update configuration offline.

**Comment by lucklove** [comment]
@BusyJay @lonng What about scale in and scale out? They are indeed two different entities.

**Comment by lonng** [comment]
I have no idea how to fix it.

**Comment by BusyJay** [comment]
Supporting force reload should get around the problem.

**Comment by lucklove** [comment]
I don't like force in any case.

**Comment by lucklove** [comment]
Hi~ After investigating, force reload will not work in this case. You need at least destroy pds and recover them by pd-recover since pd records all members address and ports on disk and that can't be changed.
