### ISSUE TITLE
Tiup download grafana failed

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/tiup#322]
Error: download from https://tiup-mirrors.pingcap.com/grafana-nightly-linux-amd64.tar.gz failed: bad content length

Verbose debug logs has been written to /root/logs/tiup-cluster-debug-2020-04-27-10-41-54.log.
Error: run `/root/.tiup/components/cluster/v0.5.0/cluster` (wd:/root/.tiup/data/RxK6cva) failed: exit status 1

**Comment by lucklove** [comment]
This has been fixed in v1
