### ISSUE TITLE
edit-config change port does not work correct

### ISSUE THREAD

**Issue by aytrack** [pingcap/tiup#323]
After edit-config change port to another and reload cluster. The original service doesn't stop but starts a new one, thus making there are two processes on the target node. This will leave some systemd service file on the node after destroying the cluster.
![image](https://user-images.githubusercontent.com/10184437/80442295-2bdbee00-893f-11ea-9b13-43b37ff09ab2.png)

**Comment by lucklove** [comment]
It does not support changing the port in any way after deploying at current.
Because the deploy directory name and system config file name will contain the port.
If the port changed, we must rename these files and directories. It's risky to changing data directory name if the cluster is running.

**Comment by AstroProfundis** [comment]
Changing port in `edit-config` is forbidden after #609
