### ISSUE TITLE
Deploy data directory is inconsistent

### ISSUE THREAD

**Issue by breeswish** [pingcap/tiup#329]
Currently Tiup will create data directory in `~/` if no `/` prefix is supplied. However each component will recognize the data directory relative to the deploy directory.

Example:

```
data dir: tidb-data
deploy dir: tidb-deploy
created data directory: ~/tidb-data
actual data directory: ~/tidb-deploy/tidb-xxx/tidb-data
```

**Comment by lucklove** [comment]
Can't reproduce with newest tiup(v1.0.7), I think it has been fixed.
