### ISSUE TITLE
Should check port conflict when scale-out

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/tiup#330]
I have a playground, I also have a cluster
If I scale-out cluster to the node that I already run playground. It will success
But after I scale-in the node. It will always fail and display
```
172.16.4.99:20160  tikv        172.16.4.99  20160/20180                      linux/x86_64  Tombstone  /data1/data/tikv-20160       /data1/deploy/tikv-20160

```
TiUP should check if the port is using, and then scale-out

**Comment by lucklove** [comment]
Now the check command will do this.
Before scale-out/deploy, run `tiup cluster check scale.yml/deploy.yml` will check port conflict.
