### ISSUE TITLE
tiup cluster display command can show the version of every component

### ISSUE THREAD

**Issue by Win-Man** [pingcap/tiup#331]
The output of `tiup clusrer display <cluster-name> ` command can't show the every componet's version.Suggest to add a column show the version or add a option like '--full'.

Users may encounter the problem that `tiup cluster display <cluster-name>` displayed a version,but some componets' version are not it.

**Comment by lucklove** [comment]
> Users may encounter the problem that tiup cluster display <cluster-name> displayed a version,but some componets' version are not it.

We should avoid this case because tiup assume the cluster has the same version. The patch command may break this construct. However, the patched component will be notified and we don't encourage to use a different package to patch
