### ISSUE TITLE
Support config user group in topology.yaml

### ISSUE THREAD

**Issue by Win-Man** [pingcap/tiup#332]
Now:
```
global:
  user: "tidb"
  ssh_port: 22
```
Deploying cluster will create a tidb user group and a tidb user account.

Suggest:
The suggestion is add user group config in topology.yaml.

**Comment by lucklove** [comment]
Can you explain more details of the motivation to create a custom group?

**Comment by Win-Man** [comment]
The custom need to make a request for new group, so they want to use a group they already have.
Create a user in a group already exists.

**Comment by Win-Man** [comment]
Fixed in https://github.com/pingcap/tiup/pull/678
