### ISSUE TITLE
run_node_exporter.sh and run_balckbox_exporter.sh disappear after upgrade to v4.0.0

### ISSUE THREAD

**Issue by Win-Man** [pingcap/tiup#404]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
原先使用 tidb-ansible 部署的 v3.0.11 版本集群，使用 import 导入到 tiup 管理，导入的时候备份 tidb-ansible 目录报错，但是导入成功。
![image](https://user-images.githubusercontent.com/12085878/83600484-45f19780-a5a1-11ea-84e6-17b3862179e8.png)

然后通过 tiup 升级到 v4.0.0 版本，一开始升级的时候，在重启 tidb 节点时报错退出了，查看当时重启失败的 tidb 节点 tidb_stderr.log 日志：
![image](https://user-images.githubusercontent.com/12085878/83600650-9963e580-a5a1-11ea-9117-56ba57ba3b15.png)
手动将 tidb 节点停掉之后，重新执行 tiup cluster upgrade 操作升级成功，通过 tiup cluster display 查看集群状态正常，但是通过 Grafana 监控看到有一个节点上的 node_exporter 和 blackbox_exporter 节点状态是 down。经确认是 pump 节点上的 node_exporter 和 blackbox_exporter 进程没有启动
![image](https://user-images.githubusercontent.com/12085878/83600781-e942ac80-a5a1-11ea-9b49-220c08c3e44f.png)

![image](https://user-images.githubusercontent.com/12085878/83600749-d62fdc80-a5a1-11ea-8077-e4aeac6a78b8.png)

查看 /data/deploy/scripts 目录下，没有 run_node_exporter.sh  和 run_blackbox_exporter.sh 脚本
![image](https://user-images.githubusercontent.com/12085878/83600889-2a3ac100-a5a2-11ea-981a-4dee9d976a25.png)

inventory.ini 中配置的 deploy_dir 是 /data/deploy

2. What did you expect to see?

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?
1.0.1

**Comment by lonng** [comment]
This situation may be caused by that the cluster does not deploy exporter at this node before.

**Comment by Win-Man** [comment]
从监控上查看一下了一下 node_expoter 和 blackbox_expoter down 的时间，当时没有做任何操作，应该与 tiup 没有关系
