### ISSUE TITLE
parse enable_binlog config when import from tidb-ansible

### ISSUE THREAD

**Issue by Win-Man** [pingcap/tiup#406]
## Feature Request

**Is your feature request related to a problem? Please describe:**

`tidb-server` will start with `--enable-binlog=true` command line arguments when config `enable_binlog=true` in `inventory.ini`.

After importing tidb-ansible and upgrade/reload cluster, `tidb-server` will start with `enable-binlog=false` ,because tidb.toml doesn't config `binlog.enable=true` . 

**Describe the feature you'd like:**

Support parsing enable_binlog config when import from tidb-ansible.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lucklove** [comment]
So, do we need to add --enable-binlog=true to the command line or just tidb.toml?

**Comment by Win-Man** [comment]
Fixed in https://github.com/pingcap/tiup/pull/652
