### ISSUE TITLE
Reduce memory usage when downloading components

### ISSUE THREAD

**Issue by lonng** [pingcap/tiup#443]
## Feature Request

Currently, we use memory buffer to cache downloaded tarball, which will consume a large of memory if the tarball is huge (e.g: tiflash ~600M). The situation will get worse if we download concurrently (e.g tiup-cluster will download multiple components parallelly, 2G+ memory usage when use tiup-cluster to deploy a production cluster)。

We must reduce memory usage when downloading components.

**Comment by AstroProfundis** [comment]
related, and maybe a dupe of #299

**Comment by lonng** [comment]
@AstroProfundis I think it's better to close the #299
