### ISSUE TITLE
Interrupting updating causes tiup command not found

### ISSUE THREAD

**Issue by Hexilee** [pingcap/tiup#478]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

- Execute `tiup update --self`
- Interrupt it while downloading
- Execute tiup command again

2. What did you expect to see?

3. What did you see instead?

	After updating interrupted, my shell complains `command not found: tiup`.

4. What version of TiUP are you using (`tiup --version`)?

	Reproduced in 
	
	```
	tiup version v1.0.4 tiup
	Go Version: go1.13
	Git Branch: v1.0
	GitHash: 59fb77b
	```

**Comment by lonng** [comment]
If the self-updating process be interrupted, the `~/.tiup/bin/tiup` has been renamed to `~/.tiup/bin/tiup.tmp`. You can choose one of the below workaround:
1. `mv ~/.tiup/bin/tiup.tmp ~/.tiup/bin/tiup`
2. re-install the tiup via ` curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh `

**Comment by AstroProfundis** [comment]
dupe #297
