### ISSUE TITLE
tiup mirror genkey cause panic

### ISSUE THREAD

**Issue by lobshunter** [pingcap/tiup#492]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
`tiup mirror genkey
`
2. What did you expect to see?
successfully generate private.json

3. What did you see instead?

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x90512f]
> 
> goroutine 1 [running]:
> github.com/pingcap/tiup/pkg/environment.(*Environment).Profile(...)
>         github.com/pingcap/tiup@/pkg/environment/env.go:111
> github.com/pingcap/tiup/cmd.newMirrorGenkeyCmd.func1(0xc00012f8c0, 0xedfae8, 0x0, 0x0, 0x0, 0x0)
>         github.com/pingcap/tiup@/cmd/mirror.go:275 +0x3f
> github.com/spf13/cobra.(*Command).execute(0xc00012f8c0, 0xedfae8, 0x0, 0x0, 0xc00012f8c0, 0xedfae8)
>         github.com/spf13/cobra@v1.0.0/command.go:821 +0x56b
> github.com/spf13/cobra.(*Command).ExecuteC(0xc0000e0dc0, 0xc000322580, 0xc000149f20, 0x43b5da)
>         github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
> github.com/spf13/cobra.(*Command).Execute(...)
>         github.com/spf13/cobra@v1.0.0/command.go:887
> github.com/pingcap/tiup/cmd.Execute()
>         github.com/pingcap/tiup@/cmd/root.go:145 +0x31
> main.main()
>         github.com/pingcap/tiup@/main.go:21 +0x20
> 

4. What version of TiUP are you using (`tiup --version`)?
```
tiup version v1.0.4 tiup
Go Version: go1.13
Git Branch: v1.0
GitHash: 59fb77b
```

5. Other informantion
it's caused because subcommand overrides `cobra.Command.PersistentPreRunE` value.
According to [cobra README](https://github.com/spf13/cobra):  `The Persistent*Run functions will be inherited by children if they do not declare their own.`

- I tested on my own machine. The result proves this behavior.
- `tiup mirror genkey` overrides `PersistentPreRunE` of `tiup`, hence the global enviroment isn't set, then caused nil pointer reference panic.
- Earlier version like v1.0.0 doesn't have this problem. 
- Other commands may have same issue.

This bug may be related to [#198 ](https://github.com/pingcap/tiup/issues/198)

**Comment by AstroProfundis** [comment]
Seems to be introduced in #405 

PTAL @lichunzhu

**Comment by lichunzhu** [comment]
ok
