### ISSUE TITLE
Ansible imported into tiup without directory conflict detection

### ISSUE THREAD

**Issue by zhenjiaogao** [pingcap/tiup#499]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Ansible imported into tiup without directory conflict detection. When 
tidb and tikv or pd are deployed together and use the same directory, tiup is used for scale in, this operation will delete the data of other components than the non-target component. 

2. What did you expect to see?

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?
tiup --version
tiup version v1.0.0 tiup
Go Version: go1.13
Git Branch: master
GitHash: 5796405
Build Time: 2020-05-28 18:15:15 +0800

**Comment by lucklove** [comment]
This will be fixed in v1.0.6
