### ISSUE TITLE
Support non rolling upgrade for tiup cluster patch command

### ISSUE THREAD

**Issue by Connor1996** [pingcap/tiup#523]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When testing, I need to deploy with my self-built binary, so I use tiup cluster patch to upgrade the cluster. But patch command will do rolling upgrade every time which wastes a lot of time.

**Describe the feature you'd like:**

Support non rolling upgrade for tiup cluster patch command.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lucklove** [comment]
Will be fixed in https://github.com/pingcap/tiup/pull/1096
