### ISSUE TITLE
Support ssh LDAP extension

### ISSUE THREAD

**Issue by lucklove** [pingcap/tiup#528]
## Feature Request

**Is your feature request related to a problem? Please describe:**

At current we only support standard ssh tunnel. However, some people/companies use LDAP as the extension of ssh to manage their machines, in this case, tiup will not work. So they can't upgrade their cluster to v4 since tidb-ansible don't support tidb v4 and tiup can't work in their case.

GanttStart: 2020-07-20 
GanttDue: 2020-08-10 
GanttProgress: 100%

**Comment by uglyengineer** [comment]
Issues belong to 5.0/P0 need to have start/end date. Please reveal the dates.

**Comment by lucklove** [comment]
> Issues belong to 5.0/P0 need to have start/end date. Please reveal the dates.

Done

**Comment by AstroProfundis** [comment]
We need to set default value of `-i` and `-p` to empty for native (system) SSH executor, to let the `ssh` command really being able to invoke whatever extended authentication method available.

In this circumstance, it's better to implement #693 as the argument style.
