### ISSUE TITLE
Support import for existed tidb cluster deployed by tiup

### ISSUE THREAD

**Issue by hunterlxt** [pingcap/tiup#551]
## Feature Request

**Describe the feature you'd like:**
we can use as `tiup cluster import /path_to_existed_cluster`. Now tiup only support importing from ansible cluster. But if we have a local cluster in single machine, it's convenient to import directly.

**Comment by lonng** [comment]
I think you can use playground to run a local cluster in the single machine.

**Comment by hunterlxt** [comment]
Sometimes we need bench and investigate problems

**Comment by hunterlxt** [comment]
For example, I need test using a huge cluster. And for convenience, I backup this cluster and try to start multiple. If tiup cluster support import from local cluster, we can test more conveniently.

**Comment by lonng** [comment]
@hunterlxt  Do you want to import the data from the local cluster? Or import the topology?

**Comment by hunterlxt** [comment]
from the local cluster. that means I only have a tidb directory in which `data` and `deploy` exists.

**Comment by lonng** [comment]
@AstroProfundis PTAL

**Comment by AstroProfundis** [comment]
I believe it's safe to just copy `~/.tiup/storage/cluster/clusters/<your-cluster-name>` to the same path on the new system.

It should be working if the deploy servers unchanged. However, if you want to use the same "local" cluster on another server, you'll need to manually edit the `meta.yaml` under your cluster's dir to change the host IPs. And you may need to backup `~/.ssh/authorized_keys` from the old server to new one, to make sure tiup has proper permission to login to the new host.
