### ISSUE TITLE
How to import a binary deployed tidb cluster to tiup？

### ISSUE THREAD

**Issue by lddlww** [pingcap/tiup#553]
tidb cluster deployed by binary，how can i transfer to tiup management without  import/export data？

**Comment by lucklove** [comment]
What do you mean by `tidb cluster deployed by binary`?
Do you deploy the cluster manually?

**Comment by lddlww** [comment]
1、Do you deploy the cluster manually?
```
yes
```
2、call tiup cluster deploy <cluster-name> <version> topology.yaml
```
does it overrid the old tidb data？
```

**Comment by lucklove** [comment]
It doesn't override old data (If you think it's risky, you can back up the old data before taking any action). 

However, it does override configs and start scripts. I suggest that you stop all instances and back up these stuff.

Things will be overridden:
- /etc/systemd/system/{tidb/tikv/pd/xxx}-{port}.service   // I don't know if you have this since you deploy manually
- /deploy/dir/bin/{tidb/tikv/xxx}-server // the binary
- /deploy/dir/scripts/run_xxx.sh  // the start script

The data directory will not be override, tiup just use mkdir -p to make sure it exists

**Comment by lddlww** [comment]
@lucklove thanks

**Comment by AstroProfundis** [comment]
**Please backup your data before performing any operation**

It's not officially supported to import a binary deployed cluster into tiup, but it is possible with some manual process. Please keep in mind that this is not a recommended practice and do backup your data before going further.

0. Stop the cluster and **backup your data**

1. You'll need to write a topology file that match your current cluster.
  - The `user` in global options **must** be the owner of your current deployed files, and they should be the same on all deploy servers
  - The `data_dir`, `deploy_dir` and `log_dir` of instance **must** be absolute path
  - The `imported` field of **every** instance **must** be `true`

2. Run `tiup deploy` with the topology file normally, with the same version as your current deployment

3. Check file paths on deploy servers to see if they are in proper location, e.g., binary files should be at `<deploy_dir>/bin/xx-server`, and it should be the same as your previous (manual) deployment, and also check the `data_dir` are correct, they should be the same in `deploy_dir>/conf/xxx.toml` or in `/etc/systemd/system/<component>-<port>.service` as your previous (manual) deployment

4. Run `tiup start <cluster-name>` to start the cluster, if it started, login to see if data are accessible.

After import, all process will be managed by `systemd`, so your deployment server must be running some OS that using systemd as the init service. And if you used to use other method to manage processes, they should **not** be used anymore.

**Comment by lddlww** [comment]
@AstroProfundis 
ok，thanks for your patience

**Comment by lddlww** [comment]
when i set imported:true；tiup raise error：
```
Error: 'imported' is set to 'true' for new instance, this is only used for instances imported from tidb-ansible and make no sense when deploying new instances, please delete the line or set it to 'false' for new instances
```

**Comment by lucklove** [comment]
> Error: 'imported' is set to 'true' for new instance

This is used for importing cluster from tidb-ansible cluster, in your case, you shouldn't use it

**Comment by lddlww** [comment]
@lucklove thanks for reply
