### ISSUE TITLE
please help Integrate pd-recover in tiup

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tiup#561]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When customer pd instance failed, We need use pd-recover recover pd.   tiup not Integrate pd-recover tool

**Describe the feature you'd like:**

please help Integrate pd-recover in tiup. 

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

When customer pd instance failed, We need use pd-recover recover pd

**Comment by lucklove** [comment]
This has been supported.
Try it:
```
tiup pd-recover
```
