### ISSUE TITLE
Support offline upgrade/patch

### ISSUE THREAD

**Issue by lonng** [pingcap/tiup#563]
## Feature Request

Currently, the cluster must be running when upgrading, we should support offline upgrade.

**Comment by lucklove** [comment]
I always think that it's the same with `--force`. But --force has an issue here:  https://github.com/pingcap/tiup/issues/566

**Comment by lonng** [comment]
@lucklove I think there are some trivial differences.

**Comment by lucklove** [comment]
> @lucklove I think there are some trivial differences.

Can you explain more detail about it?

**Comment by lucklove** [comment]
BTW. https://github.com/pingcap/tiup/issues/566 is not an obstacle now.
