### ISSUE TITLE
offline on upgrade

### ISSUE THREAD

**Issue by liuxuefeng12** [pingcap/tiup#564]
计划性停机下快速升级，tiup 现在版本貌似不支持，升级时候会先检查 pd 连通性；
tiup version v1.0.7 tiup
Go Version: go1.13
Git Branch: v1.0
GitHash: 7f51794

![image](https://user-images.githubusercontent.com/63033738/86313025-ad5d3e80-bc56-11ea-9d43-4bb442dae412.png)

**Comment by lonng** [comment]
#563
