### ISSUE TITLE
tiup playground auto clean data when pressing ctrl+c?

### ISSUE THREAD

**Issue by tohghua** [pingcap/tiup#572]
我觉得应该保留。需要时可用clean命令清除数据。

另外目前tiup playground启动时无法正常启动grafana，因为找不到文件grafana，只有grafana-server

**Comment by lonng** [comment]
@tohghua 
You must specify a tag for playground instance explicitly if you want to retain the data. eg: `tiup  -T xxx playground `

**Comment by lucklove** [comment]
> 另外目前tiup playground启动时无法正常启动grafana，因为找不到文件grafana，只有grafana-server

Can you provide the version of tiup (with `tiup --version`)?
And it's better to paste the error message.

**Comment by tohghua** [comment]
hgh@hgh-VirtualBox:~$ tiup --version
v1.0.7 tiup
Go Version: go1.13
Git Branch: v1.0
GitHash: 7f51794
hgh@hgh-VirtualBox:~$ tiup -T d1 playground
Starting component `playground`: /home/hgh/.tiup/components/playground/v1.0.7/tiup-playground
Playground Bootstrapping...
Starting component `prometheus`: /home/hgh/.tiup/components/prometheus/v4.0.2/prometheus/prometheus --config.file=/home/hgh/.tiup/data/d1/prometheus/prometheus.yml --web.external-url=http://127.0.0.1:9090 --web.listen-address=0.0.0.0:9090 --storage.tsdb.path='/home/hgh/.tiup/data/d1/prometheus/data'
start grafana:  tiup grafana --homepath /home/hgh/.tiup/data/d1/grafana --config /home/hgh/.tiup/data/d1/grafana/conf/custom.ini
Start pd instance...
Start tikv instance...
Start tidb instance...
................
Waiting for tikv 127.0.0.1:20160 ready 
Waiting for tiflash 127.0.0.1:3930 ready 
CLUSTER START SUCCESSFULLY, Enjoy it ^-^
To connect TiDB: mysql --host 127.0.0.1 --port 4000 -u root
To view the dashboard: http://127.0.0.1:2379/dashboard
To view the Prometheus: http://127.0.0.1:9090
To view the Grafana: http://127.0.0.1:3000
Grafana quit: exit status 1

**Comment by tohghua** [comment]
If I run this, grafana will start as wish:
```
hgh@hgh-VirtualBox:~$ cd .tiup/components/grafana/v6.7.1/bin
hgh@hgh-VirtualBox:~/.tiup/components/grafana/v6.7.1/bin$ ln grafana-server grafana
```

**Comment by lucklove** [comment]
We will fix it in next version.

**Comment by july2993** [comment]
> ```
> hgh@hgh-VirtualBox:~$ tiup --version
> v1.0.7 tiup
> Go Version: go1.13
> Git Branch: v1.0
> GitHash: 7f51794
> hgh@hgh-VirtualBox:~$ tiup -T d1 playground
> Starting component `playground`: /home/hgh/.tiup/components/playground/v1.0.7/tiup-playground
> Playground Bootstrapping...
> Starting component `prometheus`: /home/hgh/.tiup/components/prometheus/v4.0.2/prometheus/prometheus --config.file=/home/hgh/.tiup/data/d1/prometheus/prometheus.yml --web.external-url=http://127.0.0.1:9090 --web.listen-address=0.0.0.0:9090 --storage.tsdb.path='/home/hgh/.tiup/data/d1/prometheus/data'
> start grafana:  tiup grafana --homepath /home/hgh/.tiup/data/d1/grafana --config /home/hgh/.tiup/data/d1/grafana/conf/custom.ini
> Start pd instance...
> Start tikv instance...
> Start tidb instance...
> ................
> Waiting for tikv 127.0.0.1:20160 ready 
> Waiting for tiflash 127.0.0.1:3930 ready 
> CLUSTER START SUCCESSFULLY, Enjoy it ^-^
> To connect TiDB: mysql --host 127.0.0.1 --port 4000 -u root
> To view the dashboard: http://127.0.0.1:2379/dashboard
> To view the Prometheus: http://127.0.0.1:9090
> To view the Grafana: http://127.0.0.1:3000
> Grafana quit: exit status 1
> ```

when not specified version it will run the newest version, grafana:v6.7.1 is a wrongly distributed version.
currently, you can run it with specified version like `tiup playground v4.0.2`

**Comment by tohghua** [comment]
@july2993 Got it. Thanks!
