### ISSUE TITLE
check the log_dir of pd during deployment

### ISSUE THREAD

**Issue by together-wang** [pingcap/tiup#586]
check the log_dir of pd during deployment

![image](https://user-images.githubusercontent.com/44355590/86900785-5c5db680-c13e-11ea-8182-82dfde16b85c.png)

Deploy successfully, but start fails without log, execute run_pd.sh print [error="log directory Shouldn't be the subdirectory of Data Directory "]

Please add check the log_dir of pd during deployment.

**Comment by AstroProfundis** [comment]
Done in #1093
