### ISSUE TITLE
升级版本后， 监控相关改动同步到新版本中

### ISSUE THREAD

**Issue by ojhtyy** [pingcap/tiup#590]
## Feature Request
现在每次升级 ， 
1：alertmanager 的数据都会被初始化， 升级结束后都需要重新配置告警通知
2：prometheus 额外配置了自定义的alertmanager ，升级后 自定义的alertmanger也要重新手动配置到prometheus 中 
       prometheus之前的监控数据也没带入到新版本中
3：大版本升级后（3.0.2-->4.0.1） grafana 也被初始化 ， 配置的账号也消失，又要重新配置
       但4.0.1升级到4.0.2 ， 账号还在 

以上3点， 希望在版本升级时， 可以把相关信息都带入到新版本中  
**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lucklove** [comment]
https://docs.pingcap.com/zh/tidb/stable/tiup-cluster#%E6%9B%B4%E6%96%B0%E9%85%8D%E7%BD%AE
