### ISSUE TITLE
PD leader should be reload last

### ISSUE THREAD

**Issue by lucklove** [pingcap/tiup#597]
## Feature Request

At this time, in upgrade operation, we will reload pd one by one regardless of their role. At the same time, we will `EvictPDLeader` of upgrading PD.

It's very likely that we choose a leader to upgrade, evicting the leader to another pd, and then upgrading another pd and it's the leader too.

The better way to do this is that we should upgrade non-leader PDs first, so we only need to transfer leader once.

**Comment by AstroProfundis** [comment]
Related to #1086

**Comment by AstroProfundis** [comment]
The `reload` command executes `operator.Upgrade()` to rolling restart the cluster, and as deferring PD leader is implemented in the `operator.Upgrade()` function, this should already be done.
