### ISSUE TITLE
tiup cluster upgrade config check failed

### ISSUE THREAD

**Issue by cyliu0** [pingcap/tiup#598]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Deploy and start a v4.0.1 cluster with config `experimental.allow-auto-random = true`
`tiup cluster upgrade $cluster_name nightly`

tidb has removed the configuration on master.

Workaround: Use `cluster edit-config` remove the configuration and then upgrade.

2. What did you expect to see?
Upgrade successfully

3. What did you see instead?
Upgrade failed because of tidb-server config check failed

4. What version of TiUP are you using (`tiup --version`)?
1.0.7

**Comment by lonng** [comment]
The TiUP won't guarantee all configuration user-configured valid, all configuration will be converted to the toml format directly.

**Comment by cyliu0** [comment]
How did we deal with a situation like this during the past? The components may abandon some configurations occasionally. And if we do not have a solution for this inside tiup or the components, maybe it will bring a lot of OnCall cases or upgrade document work.

**Comment by lonng** [comment]
The components have changed the behaviors of treating abandoned configurations, print some warnings instead of panic, this rule can be applied to >= 4.0.2.
