### ISSUE TITLE
Topology is not updated after `tiup playground scale-in

### ISSUE THREAD

**Issue by Fullstop000** [pingcap/tiup#603]
## Bug Report

1. What did you do?

- `tiup playground --db 2 --tiflash 0`
- `tiup playground scale-in --pid <one of tidb pid>`
- Fetch topology from PD

2. What did you expect to see?
The removed tidb info should be deleted from topology info

3. What did you see instead?
Topology fetched is not updated

4. What version of TiUP are you using (`tiup --version`)?
```
~ tiup --version
v1.0.8 tiup
Go Version: go1.13
Git Branch: master
GitHash: 4276089
```

**Comment by lucklove** [comment]
Hi~ Can you provide the steps and show the result of `Fetch topology from PD`?

**Comment by lonng** [comment]
@Fullstop000 Thanks for your feedback. There are two ways to retrieve the topology:

1. Dashboard
2. The system table `information_schema.cluster_info`

Which one did you use to retrieve the topology?

**Comment by Fullstop000** [comment]
I use the dashboard. Maybe this is a dashboard bug. I'll check it later.
