### ISSUE TITLE
restart not-leader first when upgrading pd

### ISSUE THREAD

**Issue by july2993** [pingcap/tiup#608]
## Feature Request

**Is your feature request related to a problem? Please describe:**

currently, may evict leader for every pd instance.

A(L) B C
after evict leader of A and restart A
A B(L) C
then when upgrade B will need to evict leader again..

**Describe the feature you'd like:**

restart not-leader first when upgrading pd

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by AstroProfundis** [comment]
duplicate with #597
