### ISSUE TITLE
UCP: Integrate Grafane into playground

### ISSUE THREAD

**Issue by lonng** [pingcap/tiup#63]
## Description

Currently, the playground has integrated `TiKV/TiDB/PD/Prometheus`, but the Grafana doesn't been integrated. It's better to start Grafana if the `--monitor` specified.

e.g: `tiup playground --monitor`

## Score

* 300

## Mentor(s)

* @lucklove 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Go
* Grafana

## Learning Materials

Reference the playground implementation.

**Comment by lucklove** [comment]
This has been done.
