### ISSUE TITLE
Need to test the fsync performance of target disk

### ISSUE THREAD

**Issue by innerr** [pingcap/tiup#633]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

A disk's performance spec includes:
* Read brandwidth
* Write brandwidth
* Read IOPS
* Write IOPS
* Fsync performance

We have tests in ansible to use `fio` to test these specs, but the fsync-performance is not included.
So we need to do the fsync test in `tiup` (use newest version of fio, or use pgsql's tool `pg_test_fsync`)

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lucklove** [comment]
Can you provide the qualified score of `fsync performance`? And it's better to give a command about how to test `fsync performance`.

**Comment by innerr** [comment]
I checked that fio support the fsync benchmark in all versions I meet, so I was wrong about `fsync-performance is not included`

**Comment by lucklove** [comment]
We have enabled `fdatasync` all the time: https://github.com/pingcap/tiup/blob/0267fbc491ee982b1c123e8f532efbb9625dd659/pkg/cluster/task/check.go#L170
