### ISSUE TITLE
Can't find where dashboard is though `tiup cluster display` command

### ISSUE THREAD

**Issue by Win-Man** [pingcap/tiup#637]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Deploy a new v4.0.3 cluster via tiup.

2. What did you expect to see?
I expect to find where dashboard is through `tiup cluster display` command.

3. What did you see instead?
![image](https://user-images.githubusercontent.com/12085878/88748119-d227d180-d182-11ea-89c2-9750b5ff64ca.png)
![image](https://user-images.githubusercontent.com/12085878/88748129-d5bb5880-d182-11ea-990c-ea48bf94479b.png)

![image](https://user-images.githubusercontent.com/12085878/88748141-dd7afd00-d182-11ea-9337-86ed3ce86be4.png)

4. What version of TiUP are you using (`tiup --version`)?

```

[tidb@localhost gangshen]$ tiup --version
v1.0.8 tiup
Go Version: go1.13
Git Branch: master
GitHash: 4276089
```

**Comment by lonng** [comment]
Seems the PD has changed the protocol, @AstroProfundis  PTAL.
