### ISSUE TITLE
Tiup create user should distinguish users and user groups

### ISSUE THREAD

**Issue by superlzs0476** [pingcap/tiup#653]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When deploying cluster, TiUP create user such as tidb, that will create the same name as a group.

**Describe the feature you'd like:**

Tiup create user should distinguish users and user groups.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lucklove** [comment]
This has been supported now
