### ISSUE TITLE
tiup cluster patch -R grafana error

### ISSUE THREAD

**Issue by xujiyou** [pingcap/tiup#663]
![image](https://user-images.githubusercontent.com/16862201/89639565-5e9f6600-d8e0-11ea-8b6e-0b98ed3eeda9.png)

**Comment by xujiyou** [comment]
发现 TiDB 安装的 Grafana 版本有点低，但是使用 tiup 升级不了。

使用了一个野路子：

下载官方最新版本的  Grafana，然后解压把其中的 bin 目录和 public 目录复制到tiup安装的 Grafana 目录中，即 /tidb-deploy/grafana-3000/bin 目录中即可，ps：记得备份原来的 bin 和 public 目录。

然后使用 tiup 重启集群即可。

**Comment by lonng** [comment]
We must use the same layout as the previous tarball.
The tarball you downloaded directly from Grafana homepage cannot patch directly because the distribution from TiUP contains some special files.
