### ISSUE TITLE
Support native cmd for ssh/scp

### ISSUE THREAD

**Issue by vagetablechicken** [pingcap/tiup#711]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Nope.
**Describe the feature you'd like:**

tiup cluster executor can use native ssh. That's nice. But it can only use "ssh"(in PATH). We can't define the command we want to use.
https://github.com/pingcap/tiup/blob/91c5f94a3e53e63a5e917fffc32ad06ab4ec9d36/pkg/cluster/executor/ssh.go#L304
**Describe alternatives you've considered:**
What if we use other ssh tools to connect the hosts? e.g. some ssh tools which contain security permissions.

Use `alias` could solve it. But it's not a good method.

I think supporting native cmd is a good way.
**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by AstroProfundis** [comment]
I think we could support that by adding a new argument to specify the path of alternative SSH executable binary, something like `--ssh-path` or so.

**Comment by vagetablechicken** [comment]
> I think we could support that by adding a new argument to specify the path of an alternative SSH executable binary, something like `--ssh-path` or so.

Agree entirely. I'd want `--scp-path` too. If `--ssh-path`/`--scp-path` is not specified, it will use "ssh"/"scp".

**Comment by 9547** [comment]
if `--ssh-path` or `--scp-path` is specified, seem too much code has to refactor!  Or should we set two global envars, such as `TIUP_NATIVE_SSH_PATH` to specify the alternative ssh executable binary, and fetch it before
https://github.com/pingcap/tiup/blob/91c5f94a3e53e63a5e917fffc32ad06ab4ec9d36/pkg/cluster/executor/ssh.go#L304 

```go
ssh := "ssh"

isExec := func(mode os.FileMode) bool { return mode&0111 == 0111 }
if env := os.Getenv(localdata.EnvNameNativeSSHPath); env != "" {
    if info, err := os.Stat(env); err == nil && !info.IsDir() && isExec(info.Mode()) {
        ssh = env
    }
}

args := []string{ssh, "-o", "StrictHostKeyChecking"}
```

**Comment by vagetablechicken** [comment]
@9547 Good advice. It's not a universal need, so ENV is OK.

**Comment by lucklove** [comment]
@9547 Do you have any interest on this? If so, you'd better do it after #699 been merged (in case of conflicts). Otherwise I will do it in #699

**Comment by 9547** [comment]
> @9547 Do you have any interest on this? If so, you'd better do it after #699 been merged (in case of conflicts). Otherwise I will do it in #699 

I will send an PR tonight

**Comment by lucklove** [comment]
> > @9547 Do you have any interest on this? If so, you'd better do it after #699 been merged (in case of conflicts). Otherwise I will do it in #699
> 
> I will send an PR tonight

Ok, then I'll not merge #699 util your PR is merged
