### ISSUE TITLE
Support inheriting enable_binlog setting when importing TiDB Ansible cluster to TiUP

### ISSUE THREAD

**Issue by Arthas18** [pingcap/tiup#714]
## Feature Request

**Is your feature request related to a problem? Please describe:**
TiDB Binlog is enabled by setting `enable_binlog ` to true in TiDB Ansible inventory, but the setting is lost when TiDB cluster is imported to TiUP. It may lead to binlog service closed unexpectedly and synchronization interruption after
subsequent operations such as version upgrade.

**Describe the feature you'd like:**
When import inventory.ini configuration to TiUP, check enable_binlog setting and inherit it in TiUP topology file.

**Describe alternatives you've considered:**
Add additional instructions in documents.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by july2993** [comment]
should be fixed by #652 but not released yes cc @AstroProfundis
