### ISSUE TITLE
Add an option to skip the forced cluster start operation during scaling out

### ISSUE THREAD

**Issue by AstroProfundis** [pingcap/tiup#729]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We observed a case (#730) that the "start cluster" might fail on some certain environment if the cluster has large amount instances, and if it fails to start the cluster, the whole scale out process is interrupted.

**Describe the feature you'd like:**

If the cluster can be confirmed to be already started, the "start cluster" operation could be safely skipped, but we don't have that option for user now.

**Describe alternatives you've considered:**

It's also possible to use a `-f/--force` flag to skip all operations that not critically necessary during an operation, like various checks or preparations. This could be a more generic solution.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lucklove** [comment]
We don't auto-start the cluster since https://github.com/pingcap/tiup/pull/848
