### ISSUE TITLE
UCP: Support zsh/bash auto-completion for TiUP

### ISSUE THREAD

**Issue by lonng** [pingcap/tiup#73]
## Description

Support zsh/bash auto-completion for TiUP, make the tiup easy to use. We should support component auto-completion if possible.

## Score

* 605

## Mentor(s)

* @lonng

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang

**Comment by Renkai** [comment]
pick up unformally

**Comment by lucklove** [comment]
@Renkai Does it go well? Or do you need any help?

**Comment by Renkai** [comment]
> @Renkai Does it go well? Or do you need any help?

Sorry I found Cobra(https://github.com/spf13/cobra)'s document is hard to understand so I dropped🕊 this task after several tries.

**Comment by lucklove** [comment]
@Renkai That's all right, thanks for trying.

**Comment by yeya24** [comment]
I can take it if no one is working on it.

**Comment by STRRL** [comment]
Hi @yeya24 , it seems there is no completion about `tiup playground`. 

Does it will be consider in the future?

**Comment by yeya24** [comment]
@STRRL I am still investigating how to integrate that. I think it is okay to have another issue to track it.
