### ISSUE TITLE
remove root form "sudo -H -u root bash -c" 

### ISSUE THREAD

**Issue by jacktd9** [pingcap/tiup#731]
tiup 运维使用中有写定 sudo root 一类指令，
在用户实际环境下含 root 的调用指令存在安全规范问题，如果 tiup 写定了root 就用不了。
![image](https://user-images.githubusercontent.com/63033738/91656403-0f1d1600-eaeb-11ea-9861-7f2f8399862d.png)
了解应是可以去除 root 吧
sudo bash -c xxx 等价于 sudo -u root bash xxx

**Comment by lucklove** [comment]
Fixed by https://github.com/pingcap/tiup/pull/738
