### ISSUE TITLE
UCP: Add tldr man pages for TiUP

### ISSUE THREAD

**Issue by lonng** [pingcap/tiup#74]
## Description

Add tldr man pages for TiUP, see: https://github.com/tldr-pages/tldr

## Score

* 100

## Mentor(s)

* @lonng

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Go

**Comment by lucklove** [comment]
What's the status of this issue? Do we need this still?
