### ISSUE TITLE
tiup parameter --force could delete some host can't access 

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tiup#750]
## Feature Request

**Is your feature request related to a problem? Please describe:**

https://asktug.com/t/topic/36774

Customer use ecs host ,when they delete ecs host, tiup can't access the host. 
Even use --force parameter can't delete host. 
Customer could just edit  ~/.tiup/storage/clusters/cluster//meta.yaml.

**Describe the feature you'd like:**

If could use --force delete host which can't access.

**Describe alternatives you've considered:**

It's no need customer to edit  ~/.tiup/storage/clusters/cluster//meta.yaml, I think customer no need edit this file.

**Comment by AstroProfundis** [comment]
Related to #729
