### ISSUE TITLE
add --subnet in docker/up.sh

### ISSUE THREAD

**Issue by 9547** [pingcap/tiup#752]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

in [docker/up.sh](docker/up.sh) we create the tiops network with hard coded cidr subnet of `172.19.0.0/16`

https://github.com/pingcap/tiup/blob/760091fa22e5f76862fd4a49f796d04b982eebb0/docker/up.sh#L151

this subnet may be conflict with other networks.  Subsequent processes may therefore fail. 

**Describe alternatives you've considered:**

1. support invoke up.sh with option `--subnet` 

```bash
./up.sh --subnet x.x.x.x/x 
```

2. don't hardcode the ip addresses in [docker-compose.sh](https://github.com/pingcap/tiup/blob/master/docker/docker-compose.yml) and [tests](tests) 

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by july2993** [comment]
Good idea.
