### ISSUE TITLE
Help message is inconsistent

### ISSUE THREAD

**Issue by 9547** [pingcap/tiup#753]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

`tiup cluster check -h` will invoke the subprocess of `tiup-cluster`, and the help message print out as below:

![image](https://user-images.githubusercontent.com/29431502/92119653-aefbdc00-ee2a-11ea-8d3d-77b3bee901e3.png)

missing the `cluster` sub command

2. What did you expect to see?

```bash
Usage:
    tiup cluster check <topology.yml | cluster-name> [flags]
```

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?

**Comment by july2993** [comment]
maybe introduce by https://github.com/pingcap/tiup/pull/716
