### ISSUE TITLE
mkdir of deploy command should be idempotent or at least repeatable

### ISSUE THREAD

**Issue by july2993** [pingcap/tiup#763]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

If failed or interrupted after mkdir dir and before chown, a root user directory is leftover
and failed to start the cluster next time after successfully deploy the cluster.
https://github.com/pingcap/tiup/blob/master/pkg/cluster/task/mkdir.go#L55

2. What did you expect to see?

All operations should be idempotent or at least repeatable. If an operation is interrupted, the user can just retry until it succeeds.

3. What did you see instead?
A root user directory is leftover and failed to start the cluster after deploying the cluster.

4. What version of TiUP are you using (`tiup --version`)?
v1.1.1

**Comment by lucklove** [comment]
That's risky to do so because user may config the directory pointed to a system directory or directories belong to other clusters. In that case, the system or other cluster will be risky.
