### ISSUE TITLE
Anisble import TiUP parse inventory.ini exist problems

### ISSUE THREAD

**Issue by WentaoJin** [pingcap/tiup#771]
原始 inventory.ini 文件， 默认部署目录 /home/szy1/deploy 
![image](https://user-images.githubusercontent.com/34805682/92690375-7ea8c600-f373-11ea-8cb2-825f864dd3c8.png)

tiup import 导入后，对比原 inventory.ini 少了一个自定义deploy_dir 的tikv，tidb pd 各有一个节点，deploy_dir 变了，查看 pd 进程，仍然在原始目录运行，与 tiup display 结果不符合 
![image](https://user-images.githubusercontent.com/34805682/92690442-9bdd9480-f373-11ea-8261-225fa8b3605d.png)

tiup version
![image](https://user-images.githubusercontent.com/34805682/92690569-cdeef680-f373-11ea-96d4-a42e75f34b5d.png)

**Comment by AstroProfundis** [comment]
We have diagnosed the issue privately, the cluster was mis-configured with ansible, there're two instances having identical contents in their start scripts. So it's not working before import that one of the instances fails to start.

After fixing the issue and setting up a fully working ansible deployed cluster, the import feature works as expected.
