### ISSUE TITLE
Execute ' tiup dm *s',  extra info displayed in response

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tiup#772]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

[root@localhost ~]# tiup dm *s
Starting component `dm`: /root/.tiup/components/dm/v1.1.1/tiup-dm logs
Error: unknown command "logs" for "tiup"
Verbose debug logs has been written to /root/logs/tiup-cluster-debug-2020-09-09-10-04-32.log.
Error: run `/root/.tiup/components/dm/v1.1.1/tiup-dm` (wd:/root/.tiup/data/SA5H3tx) failed: exit status 1
[root@localhost ~]# tiup --version
v1.0.9 tiup
Go Version: go1.13
Git Branch: master
GitHash: 41fbacf
[root@localhost ~]#

2. What did you expect to see?
     1. 'Verbose debug logs has been written to /root/logs/tiup-cluster-debug-2020-09-09-10-04-32.log. '
this log should not be displayed
     2. param '\*s' should not matched 'logs',  '\*' should not be a Wildcard here. tiup should start 'tiup-dm *s'
     3. there is a spelling mistake in 'Verbose debug logs has been', should be ''Verbose debug logs **have** been'
 
3. What did you see instead?

Starting component `dm`: /root/.tiup/components/dm/v1.1.1/tiup-dm logs
Error: unknown command "logs" for "tiup"
Verbose debug logs has been written to /root/logs/tiup-cluster-debug-2020-09-09-10-04-32.log.
Error: run `/root/.tiup/components/dm/v1.1.1/tiup-dm` (wd:/root/.tiup/data/SA5H3tx) failed: exit status 1

4. What version of TiUP are you using (`tiup --version`)?

[root@localhost ~]# tiup --version
v1.0.9 tiup
Go Version: go1.13
Git Branch: master
GitHash: 41fbacf

**Comment by lucklove** [comment]
I think it's your shell that replace `*s` to `logs` and TiUP can not receive the param `*s` at all.

Try this:

```bash
cat > /tmp/test.go << EOF
package main

import (
        "os"
        "fmt"
)

func main() {
        fmt.Println(os.Args)
}
EOF

go run /tmp/test.go *
```
