### ISSUE TITLE
no selinux check result display

### ISSUE THREAD

**Issue by july2993** [pingcap/tiup#774]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

 tiup cluster check test --cluster

2. What did you expect to see?
should having selinux check result

3. What did you see instead?
no selinux check display

4. What version of TiUP are you using (`tiup --version`)?
7d25cbe8dd7c20805ca668476a894fa50dde2598 master

**Comment by 9547** [comment]
@july2993 If the SELinux is disabled, and no `result.Msg` is set, the result will be filtered out.

https://github.com/pingcap/tiup/blob/169e7cbf7062bd046954bc79152c41d2b8ea1812/components/cluster/command/check.go#L395-L397


If we need to display the SELinux result, set `result.Msg = "SELinux is disabled"` after those lines https://github.com/pingcap/tiup/blob/169e7cbf7062bd046954bc79152c41d2b8ea1812/pkg/cluster/operation/check.go#L440-L442
