### ISSUE TITLE
Listen any IP address by default in playground

### ISSUE THREAD

**Issue by jackysp** [pingcap/tiup#789]
## Feature Request

**Is your feature request related to a problem? Please describe:**

No.

**Describe the feature you'd like:**

The default host is 127.0.0.1, which is not easy to use. Why not change it to 0.0.0.0 by default?
`--host string              Playground cluster host (default "127.0.0.1")`

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lucklove** [comment]
Because tikvs and pds need communicate with each other, and they can't use 0.0.0.0 as advertise address.

**Comment by lucklove** [comment]
Dup with https://github.com/pingcap/tiup/issues/199

You can use --db.host instead
