### ISSUE TITLE
When I modify  isolation-read.engines  in edit-config meet error "New topology could not be saved: types do not match"

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tiup#796]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

(1)  : ["tidb", "tikv"]
![image](https://user-images.githubusercontent.com/55389305/93729189-05706500-fbf6-11ea-80af-21d56ef7d133.png)
![image](https://user-images.githubusercontent.com/55389305/93729205-11f4bd80-fbf6-11ea-93ae-70740272939b.png)

2. What did you expect to see?
when use : ["tidb", "tikv"]  could modify parameter correct.

3. What did you see instead?

all will meet error:
New topology could not be saved: types do not match OR 
![image](https://user-images.githubusercontent.com/55389305/93729233-2933ab00-fbf6-11ea-8a6f-c97f0993621e.png)

after use 
![image](https://user-images.githubusercontent.com/55389305/93729315-8d566f00-fbf6-11ea-9496-d94c27fcad94.png)

modify parameter success. 

4. What version of TiUP are you using (`tiup --version`)?

[tidb@node5169 ~]$ tiup --version
v1.1.1 tiup
Go Version: go1.13
Git Branch: release-1.1
GitHash: 786b6c9

**Comment by july2993** [comment]
this is an expected behavior, pls refer to https://yaml.org/spec/1.2/spec.html#id2759963
note
