### ISSUE TITLE
NodeID of pump/drainer is not import and keep consistent when import from ansible

### ISSUE THREAD

**Issue by july2993** [pingcap/tiup#797]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

import a cluster from ansible.
restart pump or drainer.

2. What did you expect to see?
`./binlogctl -cmd pumps` or `./binlogctl -cmd drainers`
things keep the same as use ansible before.

3. What did you see instead?

new instance of pump/drainer with the new NodeID(the one we see from `tiup cluster display`)

ansible use the {host}:port, and when imported to tiup, we use the {ip:port} and NodeID

4. What version of TiUP are you using (`tiup --version`)?

**Comment by lucklove** [comment]
We can get the real id from `pump` and `drainer` api.
I think we can transform the tiup-node-id to ansible-node-id via these apis before we take any action on pump and drainer.

**Comment by july2993** [comment]
should add a `NodeID` field in spec, and set it when import form ansible

**Comment by glkappe** [comment]
Regarding this improvement, I hope to ensure that the modification of tiup-node-id is consistent with the official document (also consistent with the deployment of tidb-ansible), It is recommended to continue to use `host:port` to set unspecified `pump_node-id`,and avoid secondary learning

https://docs.pingcap.com/zh/tidb/stable/tidb-binlog-configuration-file#node-id

Thanks, please feel free to contact me if you have any questions

**Comment by lucklove** [comment]
@glkappe We want to change it to ip:port because all instances in TiUP is addressed by ip:port pair, if Drainer not, it breaks the consistency.
