### ISSUE TITLE
only check the cluster's status when services are running

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/tiup#805]
## Feature Request

**Is your feature request related to a problem? Please describe:**

before executing `tiup dm start` or after executed `tiup dm stop`, the cluster should not running.

then if we execute `tiup dm display`, we'll get an error message like "Error: no endpoint available, connect: connection refused".

but we know the cluster isn't running, so we should not get this error message.

**Describe the feature you'd like:**

only check the cluster's status when services are running.

or other methods which can improve the message.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by july2993** [comment]
I think we can add a column at the display (systemd status, also uptime)

**Comment by AstroProfundis** [comment]
There should be no more such warning after #977
