### ISSUE TITLE
docs: instructions to run TiUp as a developer are incomplete/incorrect

### ISSUE THREAD

**Issue by nrc** [pingcap/tiup#829]
I followed the instructions in the dev docs and ran:

```
make
TIUP_HOME=. bin/tiup
```

and got the error:

```
Error: initial repository from mirror(https://tiup-mirrors.pingcap.com/) failed: cannot open the initial root.json at /home/nrc/version-controlled/tiup/bin/root.json
```

The docs suggest running `TIUP_HOME=. bin/tiup mirror set https://tiup-mirrors.pingcap.com` (although it is unclear if that is the correct form of the mirror to use), but that gives the same error.

I got things to work by installing TiUp, and copying the json files from ~/.tiup/bin to the working directory. It seems that there should be a better way to generate the manifest files for the default server, or if it exists then it should be properly documented.

**Comment by lonng** [comment]
@lucklove PTAL

**Comment by lucklove** [comment]
I have fix the document in https://github.com/pingcap/tiup/pull/837. PTAL
