### ISSUE TITLE
When you scale-in PD, node_exporter of the PD node is still present

### ISSUE THREAD

**Issue by together-wang** [pingcap/tiup#842]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

There is only pd service on 172.16.5.142, after executing tiup cluster scale-in lwt-cluster -N 172.16.5.142:2494, you can still see node_exporter and blackbox_exporter  exist on 172.16.5.142.

yaml:
![image](https://user-images.githubusercontent.com/44355590/95979660-8ebe3480-0e4e-11eb-8a49-896ef2139beb.png)

tiup cluster scale-in lwt-cluster -N 172.16.5.142:2494
![image](https://user-images.githubusercontent.com/44355590/95978957-7e598a00-0e4d-11eb-88cd-ee411f512172.png)

2. What did you expect to see?
When you deploy without mixing, scale-in needs to clean up node_exporter and blackbox_exporter.

3. What did you see instead?

![image](https://user-images.githubusercontent.com/44355590/95979115-ba8cea80-0e4d-11eb-938e-22212b903727.png)
![image](https://user-images.githubusercontent.com/44355590/95979165-cd072400-0e4d-11eb-85ca-44eeffd58e74.png)

4. What version of TiUP are you using (`tiup --version`)?
[tidb@node5162 ~]$ tiup cluster --version
Starting component `cluster`: /home/tidb/.tiup/components/cluster/v1.2.0/tiup-cluster --version
tiup version v1.2.0 tiup
Go Version: go1.13
Git Branch: release-1.2
GitHash: 1a4fbe7
[tidb@node5162 ~]$ tiup --version
v1.1.2 tiup
Go Version: go1.13
Git Branch: release-1.1
GitHash: 7cb85b9-dirty

**Comment by lonng** [comment]
@together-wang Thanks for your feedback, we will fix in the next version, @AstroProfundis PTAL.

**Comment by 9547** [comment]
@AstroProfundis Are you working on this issue, if not, I'll pick it up?

**Comment by AstroProfundis** [comment]
@9547 I'm not, you can do as you like
