### ISSUE TITLE
Patch command corner case when using a wrong tar.gz file.

### ISSUE THREAD

**Issue by wshwsh12** [pingcap/tiup#846]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Step 1: Patch a tar.gz file build by Jenkins.
             1.   tar tidb-server.tar.gz, it will remove tidb-server binary and create tidb-server directory (There is a directory named tidb-server in tidb repo).
             2.  tidb-server directory can't execute so that tidb will restart failed.

Step 2: Patch a tar.gz file right.
             1. tar can't replace the directory to the right binary file.

2. What did you expect to see?

In Step 1, the bin directory should be polluted if the tar.gz file is invalid.
In Step 2, the file/directory should be replaced successfully.

3. What did you see instead?

Get some tar error.  And it can't back to normal by tiup itself.

4. What version of TiUP are you using (`tiup --version`)?

**Comment by lucklove** [comment]
We should unzip the tar file to a temporary dir, and check if it has correct entry that satisfies TiUP, and then replace the current package with it.
