### ISSUE TITLE
tiup supports config.ini for configuring grafana and prometheus

### ISSUE THREAD

**Issue by sultan8252** [pingcap/tiup#849]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Manually adjust the grafana related configuration after each reload operation or cluster upgrade. Similar problems and prometheus

**Describe the feature you'd like:**
The configuration in config.ini related to grafana and prometheus is supported in tiup.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lucklove** [comment]
Dose [this](https://docs.pingcap.com/zh/tidb/stable/tiup-cluster#%E6%9B%B4%E6%96%B0%E9%85%8D%E7%BD%AE) help on this issue?

**Comment by sultan8252** [comment]
The grafana address is accessed through the nginx reverse proxy and needs to be manually specified after each reload

**Comment by lucklove** [comment]
> The grafana address is accessed through the nginx reverse proxy and needs to be manually specified after each reload

So do you want to config the [domain](https://github.com/pingcap/tiup/blob/master/templates/config/grafana.ini.tpl#L42) filed in topology file?

**Comment by mianhk** [comment]
Configuring Grafana to run behind a reverse proxy need root_url defined refrenced to : https://grafana.com/tutorials/run-grafana-behind-a-proxy/#1
But now when we use reload/scale-in/scale-out command ，the grafana.ini will be refreshed and need to be edit manually.
