### ISSUE TITLE
An error is reported when the tiup tool command uses the -h -B parameter

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tiup#862]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

An error is reported when the tiup tool command uses the -h -B parameter
![image](https://user-images.githubusercontent.com/55389305/96989195-edbf3000-1557-11eb-914e-f993b64036f9.png)

2. What did you expect to see?

Export data to the specified directory

3. What did you see instead?

Error: use `tiup install ryl` to install `ryl` first

4. What version of TiUP are you using (`tiup --version`)?

[tidb@node5169 test]$ tiup --version
v1.2.0 tiup
Go Version: go1.13
Git Branch: release-1.2
GitHash: 1a4fbe7

**Comment by lucklove** [comment]
We can provide a `--` to split the args passed to tiup and the component

**Comment by nexustar** [comment]
a possible solution is to run those tools directly #1587
