### ISSUE TITLE
Move tiup's doc to github repo wiki

### ISSUE THREAD

**Issue by iosmanthus** [pingcap/tiup#889]
## Feature Request

**Is your feature request related to a problem? Please describe:**
With more and more features are added to tiup, we need to make our docs well organized, instead of just a bunch of `tiup help`

**Describe the feature you'd like:**
We could put our documents to github wiki in this repo, make it more like: https://github.com/facebook/rocksdb/wiki.

**Comment by lucklove** [comment]
There is already a document on the web page: https://docs.pingcap.com/zh/tidb/stable/tiup-documentation-guide
If we also maintain it in repo wiki, the doc work will double (BTW, we must translate it ourself instead i18n team), which I think is not feasible.
