### ISSUE TITLE
Utilize TiKV --advertise-status-addr

### ISSUE THREAD

**Issue by breeswish** [pingcap/tiup#892]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now `--advertise-status-addr` is not set, so that TiKV reports a wrong advertise address (which comes from `--status-addr`) when `--status-addr` is set to a wildcard address like `0.0.0.0`.

**Describe the feature you'd like:**

For [TiKV >= 4.0.1](https://github.com/tikv/tikv/commit/511c346a4654f166845ec23fdffc70a94885d360), add `--advertise-status-addr` parameter.

**Describe alternatives you've considered:**

As an alternative, TiKV can infer a correct advertise status address from advertise address. However I have no idea why it is not considered in the [original proposal](https://github.com/tikv/tikv/issues/7920#issuecomment-638579276).

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lucklove** [comment]
Related change: https://github.com/tikv/tikv/issues/7920
