### ISSUE TITLE
 TiUP logs 随执行命令所在目录生成

### ISSUE THREAD

**Issue by buggithubs** [pingcap/tiup#897]
## Feature Request

目前 TiUP logs 随执行命令所在目录生成；
在任意目录执行 TiUP 操作失败后，当前目录会生成 logs 文件夹。
是否可优化成固定路径 logs 目录？

**Comment by liangyuanpeng** [comment]
It sounds pretty good.

**Comment by 9547** [comment]
Sounds good, prefer to `${TIUP_HOME}/logs`

**Comment by lucklove** [comment]
> Sounds good, prefer to `${TIUP_HOME}/logs`

Prefer ${TIUP_HOME}/storage/cluster/clusters/<cluster-name>/logs, so that it will be cleanup after the cluster destroyed.

**Comment by liangyuanpeng** [comment]
> > Sounds good, prefer to `${TIUP_HOME}/logs`
> 
> Prefer ${TIUP_HOME}/storage/cluster/clusters//logs, so that it will be cleanup after the cluster destroyed.

But the log maybe not about `cluster`, so i just agree with `${TIUP_HOME}/logs`

**Comment by lucklove** [comment]
> > > Sounds good, prefer to `${TIUP_HOME}/logs`
> > 
> > 
> > Prefer ${TIUP_HOME}/storage/cluster/clusters//logs, so that it will be cleanup after the cluster destroyed.
> 
> But the log maybe not about `cluster`, so i just agree with `${TIUP_HOME}/logs`

You and @9547 are right. I didn't think about this:

```sh
tiup cluster no-this-command
```

This will leave a log too, but it's not related to any cluster
