### ISSUE TITLE
Expect tiup support arm and x86 mixed deploy

### ISSUE THREAD

**Issue by freyfl** [pingcap/tiup#911]
## Feature Request

**Describe the feature you'd like:**

Now tiup deploy a tidb cluster only can choose one system platform arm or x86_64.

In future expect tiup support deploy a tidb cluster mixed at arm/x86_64.

example:
|  TiDB   | platform  |
|  ----  | ----  |
| tidb-server  | arm |
| tidb-server | arm |
| tikv-server | x86_64 |
| tikv-server | arm |
| tikv-server | x86_64 |
| pd-server | arm |
| pd-server | x86_64 |
| pd-server | x86_64 |

**Comment by AstroProfundis** [comment]
It is already supported by specifying `arch` in each node's specification.

**Comment by meilihao** [comment]
@AstroProfundis 

下载到tidb-community-toolkit-v4.0.8-linux-amd64.tar.gz, 执行bash local_install.sh + source /home/tidb/.bash_profile后成功安装了tiup. 但再将tidb-community-toolkit-v4.0.8-linux-arm64.tar.gz下到, 并执行里面的local_install.sh时报错了.

请问混合arch部署时要如何组织tidb-community-toolkit-v4.0.8-linux-arm64/amd64.tar.gz里的文件? 以及topology.yaml example.

**Comment by 9547** [comment]
> @AstroProfundis
> 
> 下载到 tidb-community-toolkit-v4.0.8-linux-amd64.tar.gz, 执行 bash local_install.sh + source /home/tidb/.bash_profile 后成功安装了 tiup. 但再将 tidb-community-toolkit-v4.0.8-linux-arm64.tar.gz 下到，并执行里面的 local_install.sh 时报错了.
> 
> 请问混合 arch 部署时要如何组织 tidb-community-toolkit-v4.0.8-linux-arm64/amd64.tar.gz 里的文件？以及 topology.yaml example.

@meilihao  You don't need to run `local_install.sh`  in tiup's node, just define the topology as what you want, such as:

```yaml
...
tidb_servers:
  - host: 172.16.5.138
    arch: "amd64"
  - host: 172.16.4.190
    arch: "arm64"
...
```

then the tiup deploy process will deploy amd64's tidb in `172.16.5.138` and arm64's tidb in `172.16.4.190`

**Comment by AstroProfundis** [comment]
下载 tiup 时只需要选择和中控机相同架构的包，部署时在 topology.yaml 中定义每个 node 的架构并按正常流程操作即可混合部署

Just download the tiup binary that matches your console server's arch, and when `deploy` a cluster, define arch per node in the `topology.yaml` specification, then process as normal and you'll get a hybrid cluster.

**Comment by meilihao** [comment]
@AstroProfundis 我这是内网环境, 网络隔离, 因此需要提前下载好文件, 我的中控机是x86, 因此tidb-community-toolkit-v4.0.8-linux-arm64.tar.gz的文件不知要如何处理, 才能让tiup识别到?

**Comment by meilihao** [comment]
@AstroProfundis 而且ssh通的话, tiup应该能自己取到目标机器的arch,  topology.yaml完全可以不用`arch`属性指定的.

**Comment by AstroProfundis** [comment]
@meilihao 目前没有实现自动识别目标机器架构的机制，所以要在部署时指定

至于离线包的问题，现在官网提供的离线包都是单架构的，多架构离线包可以在一台有网络的机器上使用 `tiup mirror` 命令自行手动创建，再复制到离线环境的中控机使用

我们也正在开发多个离线包合并的功能，不过还没有完成 #860

**Comment by freyfl** [comment]
@AstroProfundis  thanks for reply.
