### ISSUE TITLE
use tiup restart tidb fail, can't get detail info about restart fail

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tiup#913]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
 tiup cluster edit-config tc1
 tiup cluster reload tc1 -R tidb
     Restarting component tidb
	Restarting instance 172.16.5.185
        retry error: operation timed out after 2m0s
	172.16.5.185 failed to restart: timed out waiting for port 4000 to be started after 2m0s

           Error: 	172.16.5.185 failed to restart: timed out waiting for port 4000 to be started after 2m0s: timed out waiting for 
          port 4000 to be started after 2m0s

         Verbose debug logs has been written to /home/tidb/tiup-cluster-config/logs/tiup-cluster-debug-2020-11-17-12-03-00.log.
         Error: run `/home/tidb/.tiup/components/cluster/v1.2.3/tiup-cluster` (wd:/home/tidb/.tiup/data/SGZFm25) failed: exit status 1 

check in tidb node:
[tidblocal1@kv1 scripts]$ ./run_tidb.sh 
[2020/11/17 12:56:46.255 +08:00] [FATAL] [main.go:209] ["value of [tmp-storage-quota](25774456832 byte) exceeds the capacity(25703673856 byte) of the [/tmp/1002_tidb/MC4wLjAuMDo0MDAwLzAuMC4wLjA6MTAwODA=/tmp-storage] directory"] [stack="main.checkTempStorageQuota\n\t/home/jenkins/agent/workspace/tidb_v4.0.8/go/src/github.com/pingcap/tidb/tidb-server/main.go:209\nmain.main\n\t/home/jenkins/agent/workspace/tidb_v4.0.8/go/src/github.com/pingcap/tidb/tidb-server/main.go:170\nruntime.main\n\t/usr/local/go/src/runtime/pro

2. What did you expect to see?

when tidb restart fails, tiup can get real error info and response to use.
currently, in tiup log, can't get the real information

3. What did you see instead?

 Error: 	172.16.5.185 failed to restart: timed out waiting for port 4000 to be started after 2m0s: timed out waiting for 
          port 4000 to be started after 2m0s

4. What version of TiUP are you using (`tiup --version`)?

╰─$ tiup --version
v1.2.3 tiup
Go Version: go1.13
Git Branch: release-1.2
GitHash: df7e28a
╭─tidb@localhost ~/tiup-cluster-config 
╰─$

**Comment by 9547** [comment]
On tiup's side, which just checks the component(tidb)'s port was open or not, and the (re)start was executed before the check phase, which can't judge the real reason of the componet's failure. IMO, you can use `tiup cluster exec -N xxx "cat /path/to/tidb/log/path"` to show the detail reason.

@lucklove OTOH, maybe we can print out some helpful information and tell the user which log file to look at, such as:

```bash
Error: 	172.16.5.185 failed to restart: timed out waiting for port 4000 to be started after 2m0s: timed out waiting for 
   port 4000 to be started after 2m0s
Please login into 172.16.5.185 and find the detail failure from /home/tidb/deploy/tidb-4000/logs
```

**Comment by lucklove** [comment]
> On tiup's side, which just checks the component(tidb)'s port was open or not, and the (re)start was executed before the check phase, which can't judge the real reason of the componet's failure. IMO, you can use `tiup cluster exec -N xxx "cat /path/to/tidb/log/path"` to show the detail reason.
> 
> @lucklove OTOH, maybe we can print out some helpful information and tell the user which log file to look at, such as:
> 
> ```shell
> Error: 	172.16.5.185 failed to restart: timed out waiting for port 4000 to be started after 2m0s: timed out waiting for 
>    port 4000 to be started after 2m0s
> Please login into 172.16.5.185 and find the detail failure from /home/tidb/deploy/tidb-4000/logs
> ```

Good idea
