### ISSUE TITLE
use tiup restart tidb  timed out

### ISSUE THREAD

**Issue by watchpoints** [pingcap/tiup#919]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

replate the   \bin\tidb_server 
or tiup cluster patch  tidb  ./tidb-server.tar.gz  -N 127.0.0.1:4000

tiup cluster restart tidb

Error: failed to start: failed to start tidb:   tidb 127.0.0.1:4000 failed to start: timed out waiting for port 4000 to be started after 2m0s, please check the log of the instance: timed out waiting for port 4000 to be started after 2m0s

2. What did you expect to see?

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?

tiup --version
v1.2.3 tiup
Go Version: go1.13
Git Branch: release-1.2
GitHash: df7e28a

[tidb.log.log](https://github.com/pingcap/tiup/files/5558372/tidb.log.log)
[tiup-cluster-debug-2020-11-18-14-58-00.log](https://github.com/pingcap/tiup/files/5558373/tiup-cluster-debug-2020-11-18-14-58-00.log)

**Comment by 9547** [comment]
Google for the below error message from _tidb.log.log_ 
```bash
[2020/11/18 15:06:48.254 +08:00] [ERROR] [tidb.go:83] ["[ddl] init domain failed"] [error="404 page not found\n"]

```

Seems it may be due to an old version of PD:  https://asktug.com/t/topic/37546/4?u=9547

**Comment by watchpoints** [comment]
i compiler  all code.tikdb pd tidb ,is is ok

**Comment by watchpoints** [comment]
tiup log   not very clear to the err.
