### ISSUE TITLE
scale-in pump/drainer action，prometheus do not update target

### ISSUE THREAD

**Issue by buggithubs** [pingcap/tiup#936]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

使用 tiup cluster scale-in tc1 -N  172.16.4.36:18247 / 172.16.4.36:18259 命令缩容 drainer/pump 节点

  172.16.4.36:18247   drainer       172.16.4.36   18247
  172.16.4.36:18259   pump          172.16.4.36   18259

-----

缩容操作成功后，prometheus 配置文件中未关联更新 drainer/pump target 信息

4. What version of TiUP are you using (`tiup --version`)?

tiup --version
v1.2.3 tiup
Go Version: go1.13
Git Branch: release-1.2
GitHash: df7e28a

**Comment by 9547** [comment]
Reproduce in my local dev, I'll dig into the issue.

**Comment by 9547** [comment]
Not only the pump/drainer but all the other components also can't auto regenerate Prometheus's config.
