### ISSUE TITLE
TiUP cluster display <cluster-name> 等待时间过长

### ISSUE THREAD

**Issue by buggithubs** [pingcap/tiup#942]
## General Question

Before asking a question, make sure you have:

```
tiup --version
v1.2.3 tiup
Go Version: go1.13
Git Branch: release-1.2
GitHash: df7e28a
```

TiUP cluster display <cluster-name> 执行后，等待时间 2 分钟 5 秒

```
  $ tiup cluster display tc1
Cluster type:    tidb
Cluster name:    tc1
Cluster version: v4.0.8
SSH type:        builtin

WARN: get location labels from pd failed: no endpoint available, the last err is: Get http://172.16.4.90:22379/pd/api/v1/config/replicate: dial tcp 172.16.4.90:22379: connect: no route to host

real    2m5.929s
user    0m0.506s
sys     0m0.126s
```

cluster display 操作时，每个组件需要与 PD 通信并确认状态。
集群一般部署三个 PD 节点，每个组件会依次向 PD 发送请求获取信息，即 `组件数量 * PD 数量 * 10s` 后显示集群信息。

// 集群网络或组件异常时，为避免等待时间过长。是否优化为  `TiUP cluster display meta <cluster-name> `，不输出 Status 列，快速查看集群拓扑信息。

```
ID                  Role          Host          Ports        OS/Arch        Data Dir                         Deploy Dir
--                  ----          ----          -----        -------        --------                         ----------
172.16.5.103:3000   grafana       172.16.5.103  3000         linux/x86_64   -                                /opt/tc2/deploy/grafana-3000
172.16.4.90:22379   pd            172.16.4.90   22379/22380  linux/x86_64   /data1/tc2/data/pd-22379         /data1/tc2/deploy/pd-22379
```

**Comment by AstroProfundis** [comment]
For record, current behavior of always showing statuses was introduced in https://github.com/pingcap-incubator/tiup-cluster/pull/50

**Comment by 9547** [comment]
Good idea, I want to support it.

**Comment by lucklove** [comment]
@9547 Do you have any idea? I have a simple strategy:

- at the begin of display, check all pds' status (fetch the status url) and cache it
- in the latter action, if we need get information from pd, check the cached information to find an alive pd
  - if found: access that pd
  - if not, return error directly
- and for pd status in display output, we and use the cached information directly

So the max time we need is <num of pd> * <timeout for single pd(default 10s)>

**Comment by 9547** [comment]
Sounds good to me, very practical strategy. 

> at the begin of display, check all pds' status (fetch the status url) and cache it 

as PD's status will be checked in the beginning, IMO, we just need to cache the alive PD.
