### ISSUE TITLE
Make sure `log_dir` is not the same with `data_dir` for TiKV cluster

### ISSUE THREAD

**Issue by shenli** [pingcap/tiup#947]
## Feature Request

**Is your feature request related to a problem? Please describe:**

If the `log_dir` is set as the same dir with `data_dir`, `clean --log` will remove the data in `data_dir`

**Describe the feature you'd like:**

Add a pre-flight check to make sure the two dirs are not the same one.

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

None

**Comment by 3pointer** [comment]
I think the directory is not the key problem. and we should not delete directory directly. if user choose to cleanup log. we need to make sure all files to be deleted have a suffix `.log`.

**Comment by AstroProfundis** [comment]
There are several improves we would do:

 - [ ] Not allowing deployment of cluster if the log_dir is the same with data_dir or deploy_dir
 - [ ] Not deleting anything if the log_dir is the same as data_dir on `clean` command
 - [ ] Make experimental features with the “experimental” mark more visible
 - [ ] Display list of files / directories to be deleted before the confirmation prompt
 - [ ] Only delete files with .log extension on `clean --log`
