### ISSUE TITLE
Merge {dm,cluster} into cmd

### ISSUE THREAD

**Issue by 9547** [pingcap/tiup#952]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently `tiup-dm` and `tiup-cluster` are two independent binaries, and they are much in common with each other and used widely in our use cases. But the `tiup completion` can't generate the bash/zsh for `tiup-{cluster,dm}`. Should we move [components/cluster](https://github.com/pingcap/tiup/tree/master/components/cluster) and [components/dm](https://github.com/pingcap/tiup/tree/master/components/dm) into [cmd](https://github.com/pingcap/tiup/tree/master/cmd), so they can be sub of the main TiUP's command, and can use the benefit of tiup's completion. 

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by 9547** [comment]
@lucklove @AstroProfundis PTAL

**Comment by lucklove** [comment]
I think it's a product decision that we make tiup-cluster and tiup-dm as a component of TiUP instead of a sub command (cc @lonng).
Basically, there are several groups of people who use TiUP:
- users who don't know TiDB at all and want to have a try (they may choose tiup-playground to get start)
- users who want to deploy production TiDB cluster (they should use tiup-cluster)
- users who want to migrate data from/to TiDB cluster (the should use tiup-dm)
They may be different people, so if we combine all components into one binary, we benefit from tiup's completion but lose the benefit of use on demand. For tiup it self, it's not a deployment manage tool, instead, it's a package manage system.

**Comment by 9547** [comment]
> users who don't know TiDB at all and want to have a try (they may choose tiup-playground to get start)

IMO, if the freshman want to try tiup-playground, his experience will be even better with tab complete :)

How about taking a tradeoff:

* cluster/dm/playground were highly used, let's merge into tiup's main binary;
* in the same time, keep `tiup-{cluster,dm,playground}` as independent processes.

**Comment by lonng** [comment]
I think we can find a way to integrate the auto-completion for both tiup main binary and all components.

**Comment by lucklove** [comment]
> > users who don't know TiDB at all and want to have a try (they may choose tiup-playground to get start)
> 
> IMO, if the freshman want to try tiup-playground, his experience will be even better with tab complete :)
> 
> How about taking a tradeoff:
> 
> * cluster/dm/playground were highly used, let's merge into tiup's main binary;
> * in the same time, keep `tiup-{cluster,dm,playground}` as independent processes.

What I am concerned is not multi-process but multi-binary, `tiup-cluster` and `tiup-dm` are different components while TiUP is a component manager.  And TiUP is not designed for only TiDB, the user may DIY his own `cluster` component (eg. a cluster component to deploy k8s or etcd or some other cluster). In this case, a built-in cluster component will be an OCD killer

**Comment by AstroProfundis** [comment]
I insist my point to keep `tiup` minimal as a pure package manager and components independent.

We have components like `tidb` in different repos, and we have plan to support user uploaded components in the future, it's not a good idea to make those "buildin" components (in tiup's repo) 1st class components than others.

Although not official provided by us, but components like `cluster` can actually be used independently without installing `tiup` at all, this also provides some more possibility and could be flexible for users to integrate our tools or components to their own toolchains.

**Comment by 9547** [comment]
If TiUP's job is responded as a package management tool, the completion or not is the question for each component itself.
 
For each component installed by TiUP, we can ask the user whether to install it as an independent process or not(such as `tiup install cluster --standalone`). If so, the main execute binary will be copy into `~/.tiup/bin` or soft link to `~/.tiup/components/<component>/bin/xxx`. Then we can use `tiup-cluster` directly.
