### ISSUE TITLE
Provide mysql client in tidb-cluster

### ISSUE THREAD

**Issue by Win-Man** [pingcap/tiup#955]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I tested `AUTO_RAMDOM` using `mysql  Ver 15.1 Distrib 10.1.45-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`, but it didn't work.
![image](https://user-images.githubusercontent.com/12085878/100713670-9a11f300-33ef-11eb-8a16-d8928ed9d282.png)
After I change the mysql client to `mysql  Ver 15.1 Distrib 10.1.47-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`, it works fine.

**Describe the feature you'd like:**

I think tiup or tidb could provide a default mysql client. Like `tiup ctl cli`.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by 9547** [comment]
As MySQL is not published by pingcap, maybe it's not ok to include it

**Comment by AstroProfundis** [comment]
Thanks for the suggest, however, we don't currently have any plan on redistributing MySQL client due to license restrictions.
