### ISSUE TITLE
The error message of monitor port conflict is misleading

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tiup#965]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I try to deploy a cluster that has a monitor port conflict with a previous cluster. TiUP tells me that there exists a port conflict between pd and tiflash:
```
>  tiup cluster deploy j2 v4.0.8 topo.yaml 
Error: Deploy port conflicts to an existing cluster (spec.deploy.port_conflict)

The port you specified in the topology file is:
  Port:      9110
  Component: pd 172.16.5.81

It conflicts to a port in the existing cluster:
  Existing Cluster Name: xxx
  Existing Port:         9110
  Existing Component:    tiflash 172.16.5.81

Please change to use another port or another host.
```
But the port 9110 is the port of monitored.node_exporter_port

2. What did you expect to see?

TiUP tells me that there exists a port conflict of monitor port

3. What did you see instead?

TiUP tells me that there exists a port conflict between pd and tiflash

4. What version of TiUP are you using (`tiup --version`)?

v1.2.5 tiup
Go Version: go1.13
Git Branch: release-1.2
GitHash: 5b9cf5d

**Comment by 9547** [comment]
This error message looks strange, but it is not. IMO, it is telling the user what components are running on this node, and two of these components have port conflicts, so it is necessary for the user to detect whether the node is deployed across the two clusters(PD VS TiFlash)

**Comment by JaySon-Huang** [comment]
After seeing that error message, I use the display command to check the tiflash port of cluster xxx and check the pd port defined in my yaml file. Both of them do not contain port 9110. I can not even find port 9110 shown in the display command because the monitor is not a standalone component.

I am very confused and do not know how to solve that conflict.

If the error message tells that port is the monitor's port, I will go check the `monitored` part in my yaml file.
