### ISSUE TITLE
v1.2.5 - tiup br install failed：download stream error INTERNAL_ERROR

### ISSUE THREAD

**Issue by glkappe** [pingcap/tiup#971]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

[tidb@node4107 qihang.li]$ tiup br
The component `br` is not installed; downloading from repository.
download https://tiup-mirrors.pingcap.com/br-v4.0.8-linux-amd64.tar.gz 34.04 MiB / 34.04 MiB 100.00% 31.68 MiB p/s                                                                             
Failed to start component `br`
Error: download from https://tiup-mirrors.pingcap.com/br-v4.0.8-linux-amd64.tar.gz failed: stream error: stream ID 1; INTERNAL_ERROR

2. What did you expect to see?

ERROR

3. What did you see instead?

success

4. What version of TiUP are you using (`tiup --version`)?

v1.2.5

**Comment by glkappe** [comment]
`wget  https://tiup-mirrors.pingcap.com/br-v4.0.8-linux-amd64.tar.gz
tar zxvf  br-v4.0.8-linux-amd64.tar.gz
mkdir ~/.tiup/components/br/v4.0.8
chown -R tidb:tidb ~/.tiup/components/br/v4.0.8 && chmod 755 ~/.tiup/components/br/v4.0.8
mv br ~/.tiup/components/br/v4.0.8`

Help review, whether this step can continue to use tiup br.


The reason for this problem is?

thank you very much for your help！！！

**Comment by AstroProfundis** [comment]
This is an issue of the CDN we use, it typically resolves automatically after a while.

It's ok to manually download the package and put it into `~/.tiup/components/<component>/<version>`, you can use it as normal.

**Comment by glkappe** [comment]
Thank you very much, I will close this issue
