### ISSUE TITLE
deploy failed when init config for prometheus and granfana when remote is using zsh

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiup#974]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

   Follow up deploy procedure in the official document

```bash
$ tiup cluster deploy cdc-cluster-1 v4.0.8 ./topology1.yaml --user tidb
```

2. What did you expect to see?

   deploy successfully

3. What did you see instead?

```
  - Copy prometheus -> 172.16.4.122 ... Error  
  - Copy grafana -> 172.16.4.122 ... Error

Error: init config failed: 172.16.4.122:19090: executor.ssh.execute_failed: Failed to execute command over SSH for 'tidb@172.16.4.122:22' {ssh_stderr: zsh:1: no matches found: /home/tidb/cluster1/deploy/prometheus-19090/conf/*.rules.yml, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/usr/bin:/usr/sbin rm -f /home/tidb/cluster1/deploy/prometheus-19090/conf/*.rules.yml}, cause: Process exited with status 1
```

4. What version of TiUP are you using (`tiup --version`)?

```
➜  tiup --versionv1.2.5 tiup
Go Version: go1.13
Git Branch: release-1.2
GitHash: 5b9cf5d
```

**Comment by amyangfei** [comment]
I was using `/bin/zsh` as default shell, zsh has different behavior with bash

> In bash, by default, if a wildcard pattern doesn't match any file, it's left unchanged. In zsh, by default, you'll get an error, which is usually the safest setting. If you want to pass a wildcard parameter to a command, use quotes. You can switch to the bash behavior with setopt no_nomatch

**Comment by 9547** [comment]
> I was using `/bin/zsh` as default shell, zsh has different behavior with bash when processing wildcard
> 
> > In bash, by default, if a wildcard pattern doesn't match any file, it's left unchanged. In zsh, by default, you'll get an error, which is usually the safest setting. If you want to pass a wildcard parameter to a command, use quotes. You can switch to the bash behavior with setopt no_nomatch

Thanks for you're explaining, I'll try to fix it.
