### ISSUE TITLE
ENV_LABELS_ENV in prometheus‘s alert rules file is not replace to tidb cluster name  

### ISSUE THREAD

**Issue by Damon-Guo** [pingcap/tiup#990]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

When Tiup deploys alertmanager, the defined name is not written into the alarm information in alertmanager, so it is not known the alarm information comes from which cluster.

2. What did you expect to see?
ENV_LABELS_ENV in prometheus‘s alert rules file  is replaced by tidb cluster name

3. What did you see instead?
ENV_LABELS_ENV in prometheus‘s alert rules file is not replace to tidb cluster name

4. What version of TiUP are you using (`tiup --version`)?
1.2.5

**Comment by King-Dylan** [comment]
When Tiup deploys alertmanager, the defined name is not written into the alarm information in alertmanager, so it is not known which cluster the alarm information comes from.

**Comment by buggithubs** [comment]
![image](https://user-images.githubusercontent.com/11624213/112116439-42450500-8bf5-11eb-891e-e6b2555522ab.png)

When multiple clusters have the same receiver, the source cannot be distinguished；Please configure the information correctly “ ENV_LABELS_ENV”
